const BeamLoadUI=(()=>{
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=x=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(2):'',drafts=new Map();let active=null;
 const length=c=>{const a=c.rawA||c.a,b=c.rawZ||c.z;return Math.hypot(b[0]-a[0],b[1]-a[1]);};
 function entry(h){const key=h.floor+'|'+h.selected.token,L=length(h.selected.member),stamp=JSON.stringify([BeamLoads.draft(h.data,L),L]);let d=drafts.get(key);if(!d||d.stamp!==stamp){d={key,stamp,L,value:BeamLoads.draft(h.data,L)};drafts.set(key,d);}d.h=h;return d;}
 const css=`.beam-load-editor{container-type:inline-size;margin:12px 0}.beam-load-editor .bl-modes{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}.beam-load-editor .bl-modes button{padding:8px 10px;font-size:14px}.beam-load-editor button[aria-pressed=true]{background:#176b80;color:#fff}.beam-load-editor .bl-grid{display:grid;grid-template-columns:1.3fr 1.35fr 1fr 1fr .9fr .9fr 32px;gap:6px;align-items:start;border-bottom:1px solid #d8e3e8;padding:10px 0}.beam-load-editor label{font-size:12px;min-width:0}.beam-load-editor input,.beam-load-editor select{box-sizing:border-box;width:100%;min-width:0;padding:7px 4px;font-size:14px;margin-top:4px}.beam-load-editor .bl-grid button{padding:6px;margin-top:20px;min-width:28px}.beam-load-editor .bl-note{color:#637d8b;font-size:12px}.beam-load-editor .bl-self{display:flex;gap:7px;align-items:center;margin:12px 0;font-size:13px}.beam-load-editor .bl-self input{width:18px;margin:0}.beam-load-editor .bl-plot{display:block;width:100%}.beam-load-editor .bl-title{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:16px}.beam-load-editor .bl-title button{padding:6px;font-size:12px}.beam-load-editor .bl-error{color:#a73a26;font-size:13px}.beam-load-editor [hidden]{display:none!important}@container(max-width:600px){.beam-load-editor .bl-grid{grid-template-columns:1fr 1fr}.beam-load-editor input,.beam-load-editor select{font-size:16px;min-height:40px}.beam-load-editor .bl-grid button{margin:0;min-height:40px}}`;
 function field(r,i,k,label){return '<label>'+label+'<input data-bl-field="'+k+'" aria-label="第 '+(i+1)+' 项 '+label+'" '+(k==='name'?'type="text" maxlength="80"':'type="number" step="any" min="0"')+' value="'+esc(k==='name'?r[k]:fmt(['dl','ll'].includes(k)?BeamLoads.up(r[k]):r[k]))+'"></label>';}
 function table(d){return d.value.rows.map((r,i)=>'<div class="bl-grid" data-bl-row="'+i+'">'+field(r,i,'name','名称')+'<label>类型<select data-bl-field="type" aria-label="第 '+(i+1)+' 项类型"><option value="point" '+(r.type==='point'?'selected':'')+'>集中 · kN</option><option value="line" '+(r.type==='line'?'selected':'')+'>线荷载 · kN/m</option></select></label>'+field(r,i,'dl','DL')+field(r,i,'ll','LL')+field(r,i,'a',r.type==='point'?'位置 m':'起点 m')+(r.type==='line'?field(r,i,'b','终点 m'):'<span></span>')+'<button type="button" data-bl-delete="'+i+'" aria-label="删除第 '+(i+1)+' 项">×</button></div>').join('');}
 function body(d){const v=d.value,manual=v.mode==='manual';return '<h4>荷载来源</h4><div class="bl-modes">'+[['auto','自动传荷'],['extra','自动＋补充'],['manual','手动荷载']].map(([k,t])=>'<button type="button" data-bl-mode="'+k+'" aria-pressed="'+(k===v.mode)+'">'+t+'</button>').join('')+'</div><p class="bl-note">'+({auto:'自动接收板、梁及柱传荷。手动表已隐藏；保存后生效。',extra:'下表只填额外荷载，与自动传荷叠加；保存后生效。',manual:'下表替代自动传荷，请包含所需的板、梁、柱及墙荷载。'})[v.mode]+'</p><div '+(v.mode==='auto'?'hidden':'')+'><h4>'+(manual?'手动荷载':'补充荷载')+'</h4><div class="bl-rows">'+table(d)+'</div><button type="button" data-bl-add>＋ 添加荷载</button><p class="bl-note">位置从图中 A 端量起，范围 0–'+fmt(d.L)+' m。DL／LL 向上取两位小数后计算；位置保持输入精度。</p></div><label class="bl-self"><input type="checkbox" data-bl-self '+((!manual||v.self)?'checked':'')+' '+(!manual?'disabled':'')+'>自动计入梁自重'+(manual?'（全截面）':'')+'</label><p class="bl-note">'+(manual?(v.self?'手动 DL 不含梁自重。':'手动 DL 须已包含梁自重。'):'梁按全截面自重；板自重按梁／墙侧面间净面积。DL／LL 向上取两位小数后计算。')+'</p><div class="bl-error" role="alert"></div><div class="bl-title"><h4>荷载图 · DL / LL</h4>'+(!manual?'<button type="button" data-bl-calc>更新自动荷载</button>':'')+'</div><p class="bl-note">'+(manual?'蓝色：手动输入；灰色：梁自重。':'灰色：自动传荷；蓝色：手动补充。自动图按 Section B 口径。')+'</p><svg class="bl-plot" role="img" aria-label="梁荷载位置示意图"></svg><div class="bl-auto-note bl-note"></div><details><summary>自动荷载明细</summary><div class="bl-auto-list bl-note"></div></details>';}
 function render(h,rr){const d=entry(h);active=d;if(rr?.loading&&rr.actions&&rr.input?.mode!=='manual')d.cached={project:JSON.stringify(h.p),loading:rr.loading,errors:rr.loadErrors||[]};setTimeout(()=>{mount(d);if(d.value.mode!=='manual'&&d.cached?.project!==JSON.stringify(h.p))calculate(d);},0);return '<style>'+css+'</style><section class="beam-load-editor" data-bl-key="'+esc(d.key)+'">'+body(d)+'</section>';}
 function root(d){const el=document.querySelector('.beam-load-editor');return el?.dataset.blKey===d.key?el:null;}
 function paint(d){const el=root(d);if(!el)return;el.innerHTML=body(d);draw(d);}
 function draw(d){const el=root(d);if(!el)return;const svg=el.querySelector('svg'),w=Math.max(260,svg.clientWidth),left=28,right=w-28,x=n=>left+(right-left)*n/d.L,mode=d.value.mode;let list=[],notes=[],parts=[],y=18;const cached=d.cached?.project===JSON.stringify(d.h.p)?d.cached.loading:null;
  if(mode!=='manual'&&cached){const l=cached;list=[...(l.automaticLines||[]),...(l.automaticPoints||[])].map(r=>({...r,auto:true}));if(l.sw)list.unshift({start:0,end:d.L,g:l.sw,q:0,label:'梁自重（全截面）',auto:true});}
  if(mode!=='auto')list.push(...d.value.rows.filter(r=>!BeamLoads.errors([r],d.L).length).map(r=>r.type==='point'?{x:r.a,g:r.dl,q:r.ll,label:r.name}:{start:r.a,end:r.b,g:r.dl,q:r.ll,label:r.name}));
  if(mode==='manual'&&d.value.self)list.push({start:0,end:d.L,g:BeamLoads.up(24.5*d.h.selected.member.b*d.h.selected.member.d),q:0,label:'梁自重（全截面）',auto:true});
  list=list.map(BeamLoads.rounded);
  const text=(xx,yy,s,anchor='start')=>'<text x="'+xx+'" y="'+yy+'" text-anchor="'+anchor+'" font-size="12" fill="#244558">'+esc(s)+'</text>',arrow=(xx,yy,c)=>'<path d="M'+xx+','+yy+'v20m-4,-6l4,6l4,-6" stroke="'+c+'" stroke-width="1.6" fill="none"/>';
  for(const r of list){const point=r.x!=null,color=r.auto?'#829fa9':'#176b80',name=String(r.label||'荷载'),maxChars=Math.max(8,Math.floor((w-56)/14)),lines=[name,...[(fmt(r.g)+' / '+fmt(r.q)+' '+(point?'kN':'kN/m'))]];for(const line of lines){for(let off=0;off<line.length;off+=maxChars){parts.push(text(left,y,line.slice(off,off+maxChars)));y+=17;}}const a=point?r.x:r.start,b=point?r.x:r.end;if(point)parts.push(arrow(x(a),y,color));else{parts.push('<path d="M'+x(a)+','+y+'H'+x(b)+'" stroke="'+color+'"/>');const n=Math.max(1,Math.floor((x(b)-x(a))/28));for(let i=0;i<=n;i++)parts.push(arrow(x(a+(b-a)*i/n),y,color));}parts.push(text((x(a)+x(b))/2,y+35,point?fmt(a)+' m':fmt(a)+'–'+fmt(b)+' m',a<.1&&point?'start':a>d.L-.1&&point?'end':'middle'));y+=52;if(r.auto)notes.push(esc(name)+' · '+fmt(r.g)+' / '+fmt(r.q)+' '+(point?'kN':'kN/m')+' · '+(point?fmt(a):fmt(a)+'–'+fmt(b))+' m');}
  const c=d.h.selected.member,cb=c.displayKind==='CB',fixed=document.getElementById('ex-fixedEnd')?.value||d.h.data.fixedEnd,cbRoot=cb?Loading.cbRoot(d.h.p,d.h.result,d.h.floor,c):null,fe=['a','z'].includes(fixed)?fixed:cbRoot?.fixedEnd;
  parts.push('<path d="M'+left+','+y+'H'+right+'" stroke="#244558" stroke-width="4"/>');if(cb){if(fe)parts.push('<path d="M'+(fe==='z'?right:left)+','+(y-16)+'v32" stroke="#244558" stroke-width="5"/>');}else for(const xx of [left,right])parts.push('<path d="M'+xx+','+(y+2)+'l-7,12h14z" stroke="#244558" fill="none"/>');parts.push(text(left,y+35,'A · 0.0 m'),text(right,y+35,'B · '+fmt(d.L)+' m','end'));let reaction=null;const error=mode==='manual'?BeamLoads.errors(d.value.rows,d.L):(!cached?['自动荷载待计算']:d.cached.errors||[]);
  if(mode==='manual'&&Loading.supportSummary(d.h.p,d.h.result,d.h.floor,c).some(s=>/未确认|待确认|失效|未找到/.test(s.text)))error.push('实际支承未完整');
  if(!error.length&&(!cb||fe))try{const points=list.filter(r=>r.x!=null).map(r=>({...r,x:cb&&fe==='z'?d.L-r.x:r.x})),lines=list.filter(r=>r.x==null).map(r=>cb&&fe==='z'?{...r,start:d.L-r.end,end:d.L-r.start}:r);reaction=Loading.actions(d.L,0,0,points,cb,lines);}catch(e){error.push(e.message);}
  y+=58;if(reaction){const A=cb&&fe==='z'?'right':'left',B=cb&&fe==='z'?'left':'right';parts.push(text(left,y,'A: DL '+fmt(reaction.dead[A])+' / LL '+fmt(reaction.live[A])+' kN'));y+=19;parts.push(text(left,y,'B: DL '+fmt(reaction.dead[B])+' / LL '+fmt(reaction.live[B])+' kN'));y+=19;parts.push(text(left,y,'ULS: A '+fmt(reaction[A])+' / B '+fmt(reaction[B])+' kN'));y+=19;if(cb){parts.push(text(left,y,'固定端 M: '+fmt(reaction.M)+' kNm (ULS)'));y+=19;}}
  else{parts.push(text(left,y,'反力待确认：荷载／支承未完整'));y+=19;}
  for(const support of Loading.supportSummary(d.h.p,d.h.result,d.h.floor,c)){const line=support.end+' Support: '+support.text,chunk=Math.max(16,Math.floor((w-56)/12));for(let n=0;n<line.length;n+=chunk){parts.push(text(left,y,line.slice(n,n+chunk)));y+=17;}}
  svg.setAttribute('viewBox','0 0 '+w+' '+(y+12));svg.innerHTML=parts.join('');el.querySelector('.bl-auto-note').textContent=mode!=='manual'&&!cached?'自动荷载尚未更新，图中仅显示手动输入。':mode!=='manual'&&d.cached?.errors?.length?'已识别的荷载如下；传荷／支承待补：'+d.cached.errors.join('；'):cb&&!fe?'CB 固定端尚未确认。':'';el.querySelector('.bl-auto-list').innerHTML=notes.length?notes.join('<br>'):'—';el.querySelector('details').hidden=mode==='manual';el.querySelector('.bl-error').textContent=mode==='auto'?'':BeamLoads.errors(d.value.rows,d.L).join('；');
 }
 function calculate(d){if(!root(d)||d.value.mode==='manual')return;const button=root(d).querySelector('[data-bl-calc]');if(button){button.disabled=true;button.textContent='计算中…';}setTimeout(()=>{if(!root(d))return;try{const p=Engine.clone(d.h.p),ex=Loading.init(p);ex.selected={};const o=ex.members[d.key]??={};Object.assign(o,{mode:'auto',beamLoadMode:'auto',beamLoads:[],points:[],extraDead:0});const row=Loading.run(p,d.h.result,'B').rows.find(r=>r.floor+'|'+r.token===d.key);if(!row?.loading)throw Error('荷载或支承待补');d.cached={project:JSON.stringify(d.h.p),loading:row.loading,errors:row.loadErrors||[]};paint(d);}catch(e){if(root(d)){root(d).querySelector('.bl-error').textContent=e.message;if(button){button.disabled=false;button.textContent='更新自动荷载';}}}},20);}
 let observer=null;
 function mount(d){const el=root(d);if(!el)return;observer?.disconnect();observer=new ResizeObserver(()=>draw(d));observer.observe(el);draw(d);}
 function read(h){const d=entry(h);return BeamLoads.pack(d.value,d.L);}
 document.addEventListener('input',e=>{const el=e.target;if(!el.closest('.beam-load-editor')||!active)return;const k=el.dataset.blField;if(!k||k==='type')return;const r=active.value.rows[Number(el.closest('[data-bl-row]').dataset.blRow)];r[k]=k==='name'?el.value:el.value===''?'':Number(el.value);draw(active);});
 document.addEventListener('change',e=>{const el=e.target;if(!el.closest('.beam-load-editor')||!active)return;if(el.dataset.blField==='type'){active.value.rows[Number(el.closest('[data-bl-row]').dataset.blRow)].type=el.value;paint(active);}if(el.hasAttribute('data-bl-self')){active.value.self=el.checked;paint(active);}});
 document.addEventListener('focusin',e=>{const k=e.target.dataset.blField;if(!active||!k||['name','type'].includes(k))return;const row=e.target.closest('[data-bl-row]');if(row){const v=active.value.rows[Number(row.dataset.blRow)][k]??'';if(e.target.value!==String(v)){e.target.value=v;e.target.select();}}});
 document.addEventListener('focusout',e=>{const k=e.target.dataset.blField;if(!active||!k||['name','type'].includes(k))return;const row=e.target.closest('[data-bl-row]');if(row)e.target.value=fmt(['dl','ll'].includes(k)?BeamLoads.up(active.value.rows[Number(row.dataset.blRow)][k]):active.value.rows[Number(row.dataset.blRow)][k]);});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b?.closest('.beam-load-editor')||!active)return;const d=active;if(b.dataset.blMode){d.value.mode=b.dataset.blMode;paint(d);}if(b.hasAttribute('data-bl-add')){d.value.rows.push({name:'新荷载',type:'line',dl:0,ll:0,a:0,b:d.L});paint(d);}if(b.dataset.blDelete!==undefined){d.value.rows.splice(Number(b.dataset.blDelete),1);paint(d);}if(b.hasAttribute('data-bl-calc'))calculate(d);});

 return {render,read,clear(){drafts.clear();active=null;observer?.disconnect();}};
})();
