window.DeflectionUI=(()=>{
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const n=(x,d=3)=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString('en-US',{maximumFractionDigits:d}):'—';
 let face='B';const key='scheme1',folds={inputs:true,framing:true,columns:false};
 document.addEventListener('toggle',e=>{const id=e.target.dataset?.dfFold;if(id){folds[id]=e.target.open;StudioHost?.repaint?.();}},true);
 const field=(label,k,v,options)=>`<label>${label}${options?`<select data-df="${k}">${options.map(([id,s])=>`<option value="${esc(id)}" ${id===v?'selected':''}>${esc(s)}</option>`).join('')}</select>`:`<input data-df="${k}" type="number" step="any" value="${esc(v??'')}" placeholder="待填写">`}</label>`;
 const arrow='<defs><marker id="df-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7z" fill="#dc7859"/></marker></defs>';
 function profile(r){if(!r.ok)return '';const w=310,h=220,max=r.delta*1000,pts=r.profile.map(p=>[65+(max>0?p.mm/max:0)*160,245-p.z/r.input.height*220]);return `<svg viewBox="0 0 320 280" aria-label="挠度曲线，水平变形已放大"><path d="M65 25V245h210" fill="none" stroke="#b3c5ce"/><polyline points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#248394" stroke-width="3"/><text x="75" y="17" font-size="12" fill="#39697c">Δ = ${n(r.delta*1000,2)} mm</text><text x="14" y="145" font-size="11" fill="#71838d">H ${n(r.input.height)} m</text><text x="67" y="265" font-size="11" fill="#71838d">固定端 · 水平变形放大示意</text></svg>`;}
 function layersUI(r){const v=r.input;if(v.mode!=='LAYERED')return '';const ready=r.bands||[];
  return `<section class="wp-card"><div class="wp-row wp-spread"><h2>${face} 面 · 受风层段</h2><button data-df-action="wind">到 Wind Load Check 修改</button></div><p class="wp-sub">自动读取 Wind Load Check。a、b 为相对固定端的高度；地下未受风部分不计入。${v.sourceMode==='UNIFORM'?'当前为地面以上均布风，按一个实际受风段积分。':''}</p><div class="df-table-wrap"><table class="wp-table df-layer-table"><tr><th>层段</th><th>a · m</th><th>b · m</th><th>q · kPa</th><th>B · m</th><th>Fi · kN</th><th>Δi · mm</th></tr>${(v.layers||[]).map((l,i)=>`<tr><td>${esc(l.id||i+1)}</td><td>${n(l.a)}</td><td>${n(l.b)}</td><td>${n(l.q)}</td><td>${n(l.breadth)}</td><td>${n(ready[i]?.F)}</td><td>${n(ready[i]?.mm,4)}</td></tr>`).join('')}</table></div><p class="wp-sub">Δi = wi × [4H(bi³ − ai³) − (bi⁴ − ai⁴)] / (24EI)。Δ = ΣΔi；全高相同风压时回到原表的 wH⁴ / 8EI。</p></section>`;
 }
 function render(p,result){const B=Deflection.assess(p,result,key,'B'),D=Deflection.assess(p,result,key,'D'),r=face==='B'?B:D,s=r.settings,v=r.input,c=Deflection.compare(B,D),levels=OverallGeometry.levels(p);
  return `<style>.df-layout{display:grid;grid-template-columns:1fr;gap:22px}.df-sketch svg{width:100%;max-height:370px;display:block}.df-walls{max-height:260px;overflow:auto}.df-walls label{display:flex;gap:10px;align-items:center;padding:8px 4px;font-size:13px;border-bottom:1px solid #eef3f5}.df-walls input{width:auto}.df-result{background:#eaf4f5;padding:16px;border-radius:9px}.df-result strong{font-size:25px;color:#236b7e}.df-no-plan{padding:60px 20px;text-align:center;color:#7b8b94}.df-table-wrap{overflow:auto}.df-manual{min-width:560px}.df-manual input{width:76px;max-width:100%;background:#fff9e6}.df-tabs button.active{background:#196a7d!important;color:white!important}.df-status{font-weight:600;color:#246b7f}.df-formula{font-family:Cambria,Georgia,serif;font-size:19px;line-height:1.8}.df-layer-table{min-width:640px}.df-layer-table input{width:86px;padding:7px;background:#fff7db;border:1px solid #d0dfe5;border-radius:4px}.df-foot{border-top:1px solid #e3ecef;padding-top:12px;margin-top:14px}.df-confirm{display:flex;gap:9px;align-items:flex-start;line-height:1.8;font-size:13px}.df-confirm input{margin-top:6px}@media(max-width:1000px){.df-layout{grid-template-columns:1fr}} </style>
  <div class="wp-head"><div><span class="wp-scheme">Scheme 1 · RC</span><h1>Deflection Check</h1><p>墙柱挠度 · 建筑中心线指定轴简化估算，Section A 加入计算抄</p></div></div>
  <div class="wp-row df-tabs">${['B','D'].map(f=>`<button data-df-action="face" data-face="${f}" class="${face===f?'active':''}">${f} 面 · ${f==='B'?'X':'Y'} 向</button>`).join('')}<button data-df-action="copy-core">把当前墙柱选择复制到 ${face==='B'?'D':'B'} 面</button></div>
  <details class="wp-card df-fold" data-df-fold="framing" ${folds.framing?'open':''}><summary>Show Framing</summary><label class="df-column-toggle"><input id="df-show-column" type="checkbox" ${DeflectionFraming91.columns()?'checked':''}> 显示 Column</label><div id="df-framing-host"></div><div class="df-fold-body">  <h3>参与计算的构件 · 所选楼层 ${esc(FloorLevels.name(p,s.floor))}</h3><p class="wp-sub">用上方楼层滑块或上下层按钮选择读取楼层；Wall 默认全选，Column 按需勾选。可在 2D 图上点击墙柱勾选／取消，蓝色虚线框表示已选。隐藏 Column 仅控制显示。</p>
  <div class="df-walls"><h4>Wall</h4>${r.available.map(w=>`<label><input type="checkbox" data-df-select="${esc(w.id)}" ${s.selected.includes(w.id)?'checked':''}><b>${esc(w.id)}</b><span>${n(w.t,0)} mm · (${n(w.x1)}, ${n(w.y1)}) → (${n(w.x2)}, ${n(w.y2)}) m</span></label>`).join('')||'<p>此层没有 Wall</p>'}</div>
  <details class="df-columns" data-df-fold="columns" ${folds.columns?'open':''}><summary>Column · 勾选参与计算</summary><div class="df-walls">${(r.availableColumns||[]).map(c=>`<label><input type="checkbox" data-df-column="${esc(c.id)}" ${(s.selectedColumns||[]).includes(c.id)?'checked':''}><b>${esc(c.id)}</b><span>${n(c.b*1000,0)} × ${n(c.d*1000,0)} mm · (${n(c.x)}, ${n(c.y)}) m</span></label>`).join('')||'<p>此层没有 Column</p>'}</div></details>
  <p class="wp-sub">Column 等级：${esc(v.columnGrade||'—')}；E = ${n(Deflection.grades[v.columnGrade])} GPa。均跟随共同材料。</p>
</div></details>
  <details class="wp-card df-fold" data-df-fold="inputs" ${folds.inputs?'open':''}><summary>风、标高与墙柱</summary><div class="df-fold-body"><div class="df-layout"><div><h2>${face} 面 · 风与高度</h2><p class="wp-sub">风荷载与 Wind Load Check 共用，自动更新。</p><div class="wp-grid"><label>当前风模式<output>${v.sourceMode==='LAYERED'?'逐层风':'均布风'}</output></label><label>受风起点<output>${n(v.windStart)} mPD</output></label><label>平均风压 · Wind Load Check<output data-df-output="wind-q">${n(v.q)} kPa</output></label><label>等效迎风宽度 · 自动读取<output data-df-output="wind-breadth">${n(v.breadth)} m</output></label></div><div class="wp-row"><button data-df-action="wind">到 Wind Load Check 修改</button><button data-df-action="materials">到共同材料设置 Wall 等级</button></div><div class="wp-grid"><label>固定端标高 · 跟随受风面底<output data-df-output="base">${n(v.base)} mPD</output></label><label>楼顶标高 · 自动读取<output>${n(levels.at(-1)?.z)} mPD</output></label></div><div class="df-result">悬臂高度 H <strong>${n(v.height)} m</strong><div class="wp-sub">H = 楼顶 mPD − 固定端 mPD</div></div><div class="wp-grid"><label>Wall 混凝土等级 · 共同材料<output data-df-output="grade">${esc(s.grade||'待设置 Wall 等级')}</output></label><label>弹性模量 E · 原表对应<output data-df-output="E">${n(Deflection.grades[s.grade])} GPa</output></label><label>允许挠度 · 固定 H / 500<output data-df-output="limit">500</output></label><label>风向 · 跟随 ${face} 面<output>${s.direction} 向</output></label></div></div></div>
  <div class="df-foot"><div class="wp-row"><button class="primary" data-df-action="check">Check ${face} 面</button><span data-df-check-status>${r.pending?'待 Check':r.ok?'已 Check · '+r.status:'请补齐资料后重新 Check'}</span></div></div></div></details>

  <section class="wp-card"><div class="wp-row wp-spread"><h2>B / D 挠度比较</h2><span class="df-status">${c.governing?'控制面：'+c.governing+' · '+c.status:c.status}</span></div><table class="wp-table"><tr><th>方向</th><th>顶端 Δ · mm</th><th>允许 H/n · mm</th><th>利用率</th><th>结果</th></tr>${[['B',B],['D',D]].map(([f,q])=>`<tr><td>${f} · ${q.settings.direction} 向</td><td>${q.ok?n(q.delta*1000,2):esc((q.errors||q.missing||['资料未完成']).join('；'))}</td><td>${q.ok?n(q.allow*1000,2):'—'}</td><td>${q.ok?n(q.ratio,3):'—'}</td><td class="${q.status==='OK'&&q.ok?'wp-ok':''}">${q.ok?q.status:`<button data-df-action="trace" data-face="${f}">查看待补输入</button>`}</td></tr>`).join('')}</table><p class="wp-sub">两面均完成后，按挠度利用率比较；Section A 保留比较表，并列出 B、D 的计算过程。</p></section>
  <section class="wp-card"><h2>Wind Load Check · 平均风压与等效均布荷载</h2><p class="wp-sub">自动读取 ${face} 面共用结果；修改 Wind Load Check 后同步更新。</p><div class="wp-grid"><label>受风面积<output data-df-output="wind-area">${n(v.windAverage?.area)} m²</output></label><label>总风力<output data-df-output="wind-force">${n(v.windAverage?.force)} kN</output></label></div><p class="wp-sub">q̄ = Σ(qᵢ Bᵢ hᵢ) / Σ(Bᵢ hᵢ)，B̄ = Σ(Bᵢ hᵢ) / H，w̄ = q̄B̄ = ΣFᵢ / H。保持总风力；不等同逐层挠度积分，也不保证更保守。</p>${v.sourceLayers?.length?`<div class="df-table-wrap"><table class="wp-table"><tr><th>层段</th><th>a–b m</th><th>q kPa</th><th>B m</th><th>F kN</th></tr>${v.sourceLayers.map(l=>`<tr><td>${esc(l.id)}</td><td>${n(l.a)}–${n(l.b)}</td><td>${n(l.q)}</td><td>${n(l.breadth)}</td><td>${n(l.q*l.breadth*(l.b-l.a))}</td></tr>`).join('')}</table></div>`:''}<p>q̄ = ${n(v.q)} kPa；B̄ = ${n(v.breadth)} m；w̄ = ${n(v.q*v.breadth)} kN/m</p></section>
  ${r.errors.length?`<section class="wp-alert"><b>${face} 面还需补齐 / 确认</b><ul>${[...new Set(r.errors)].map(e=>`<li>${esc(e)}</li>`).join('')}</ul></section>`:''}
  ${r.geometry?`<section class="wp-card"><h2>建筑中心线 · 指定轴截面性质</h2><div class="wp-grid">${[['面积 A',r.geometry.area,'m²'],['建筑中心 X',v.axis.x,'m'],['建筑中心 Y',v.axis.y,'m'],['Ixx · 建筑中心线',r.geometry.Ixx,'m⁴'],['Iyy · 建筑中心线',r.geometry.Iyy,'m⁴'],['ΣEI · '+s.direction,r.geometry.EI,'kN·m²']].map(([t,z,u])=>`<label>${t}<output>${n(z,4)} ${u}</output></label>`).join('')}</div><p class="wp-sub">建筑中心线取读取楼层建筑外包范围中点，独立于勾选构件。X 向绕 Y 轴；Y 向绕 X 轴。EI = ΣEᵢ(Ilocal,ᵢ + Aᵢdᵢ²)。墙柱采用各自 E；下表为去除重叠后的矩形分块汇总，重叠归入列表中先出现的构件。</p><div class="df-table-wrap"><table class="wp-table"><tr><th>构件</th><th>E GPa</th><th>A m²</th><th>ΣIlocal m⁴</th><th>ΣAd² m⁴</th><th>EI kN·m²</th></tr>${r.geometry.parts.map(c=>`<tr><td>${esc(c.kind+' '+c.id)}</td><td>${n(c.E)}</td><td>${n(c.area)}</td><td>${n(c.Ilocal,4)}</td><td>${n(c.parallel,4)}</td><td>${n(c.EI,2)}</td></tr>`).join('')}</table></div></section>`:''}

  ${r.ok?`<section class="wp-card"><div class="df-layout"><div><h2>计算过程 · ${face} 面</h2><div class="df-formula">${s.mode==='UNIFORM'?`w = q × B = ${n(r.input.q)} × ${n(r.input.breadth)} = ${n(r.w)} kN/m<br>Δ = wH⁴ / (8EI)<br>= ${n(r.w)} × ${n(r.input.height)}⁴ / (8 × ${n(r.E*1e6)} × ${n(r.I,4)})`:`wi = qi × Bi<br>Δi = wi[4H(bi³ − ai³) − (bi⁴ − ai⁴)] / (24EI)<br>Δ = ΣΔi<br>ΣFi = ${n(r.bands.reduce((a,l)=>a+l.F,0))} kN<br>ΣMbase = ${n(r.bands.reduce((a,l)=>a+l.M,0))} kN·m`}<br>Δ = ${n(r.delta*1000,2)} mm<br>允许值 = H / ${n(r.input.limit,0)} = ${n(r.allow*1000,2)} mm<br>Δ / H = ${r.delta===0?'0':'1 / '+n(r.drift,1)}　${r.status}</div></div><div>${profile(r)}</div></div></section>`:''}
  <label class="df-confirm"><input type="checkbox" data-df-include ${p.deflection?.include!==false?'checked':''}> 加入 Section A · Scheme 1 挠度抄</label><p class="wp-sub">计算采用实际墙柱矩形并集；重叠不重复计入，不同材料重叠时提示核对。</p>`;
 }
 function toggle(host,id){const {p,result}=host.get(),effective=Deflection.input(p,result,key,face).s;host.transact(()=>{const s=Deflection.edit(p,key,face);s.selected=effective.selected.includes(id)?effective.selected.filter(v=>v!==id):[...effective.selected,id];s.selection92=true;delete s.checkSignature94;});}
 function click(e,host){const a=e.target.closest('[data-df-action]'),w=e.target.closest('[data-df-wall]');if(w){toggle(host,w.dataset.dfWall);return true;}if(!a)return false;const {p}=host.get(),action=a.dataset.dfAction;
  if(action==='add-layer')host.transact(()=>{const s=Deflection.edit(p,key,face);let i=1;while(s.layers.some(l=>l.id==='L'+i))i++;s.layers.push({id:'L'+i,a:s.layers.at(-1)?.b??0,b:null,q:null,breadth:null});delete s.checkSignature94;});
  if(action==='remove-layer')host.transact(()=>{const s=Deflection.edit(p,key,face);s.layers.splice(+a.dataset.index,1);delete s.checkSignature94;});
  if(action==='wind'){host.navigate('elevation');}if(action==='materials'){host.navigate('checks');requestAnimationFrame(()=>{const control=document.getElementById('ex-wallFcu');if(control){for(let parent=control.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;control.scrollIntoView({block:'center'});control.focus({preventScroll:true});}});}
  if(action==='face'){face=a.dataset.face;enter(host);WorkspacePages.refresh();}if(action==='check'){host.transact(()=>Deflection.runCheck(p,host.get().result,key,face));}
  if(action==='trace'){folds.inputs=true;face=a.dataset.face;enter(host);WorkspacePages.refresh();requestAnimationFrame(()=>{const input=document.querySelector('[data-df-output=base]');input?.closest('.wp-card')?.scrollIntoView({behavior:'smooth',block:'start'});input?.focus({preventScroll:true});});}
  if(action==='excel'){host.navigate('excel');ExcelSync.generate('Deflection');}
  if(action==='copy-core')host.transact(()=>{const s=Deflection.saved(p,key,face),target=Deflection.edit(p,key,face==='B'?'D':'B');for(const k of ['selected','selectedColumns','selection92','floor94'])target[k]=s[k]===undefined?undefined:JSON.parse(JSON.stringify(s[k]));delete target.checkSignature94;});
  if(action==='add-wall')host.transact(()=>{const s=Deflection.edit(p,key,face);let i=1;while(s.walls.some(w=>w.id==='W'+i))i++;s.walls.push({id:'W'+i,x1:null,y1:null,x2:null,y2:null,t:null});delete s.checkSignature94;});
  if(action==='remove-wall')host.transact(()=>{const s=Deflection.edit(p,key,face);s.walls.splice(+a.dataset.index,1);delete s.checkSignature94;});return true;
 }
 function change(e,host){const t=e.target,{p}=host.get();if(t.id==='df-show-column'){DeflectionFraming91.setColumns(t.checked);host.repaint();return true;}if(t.hasAttribute('data-df-include')){host.transact(()=>Deflection.init(p).include=t.checked);return true;}if(t.dataset.dfColumn){host.transact(()=>{const s=Deflection.edit(p,key,face),a=s.selectedColumns||[];s.selectedColumns=t.checked?[...new Set([...a,t.dataset.dfColumn])]:a.filter(id=>id!==t.dataset.dfColumn);delete s.checkSignature94;});return true;}if(t.dataset.dfSelect){toggle(host,t.dataset.dfSelect);return true;}
  if(t.dataset.dfLayerCell){host.transact(()=>{const s=Deflection.edit(p,key,face);s.layers[+t.dataset.dfLayer][t.dataset.dfLayerCell]=t.value===''?null:Number(t.value);delete s.checkSignature94;});return true;}
  if(t.dataset.dfPressure){host.transact(()=>{const s=Deflection.edit(p,key,face);s.layerPressures??={};s.layerPressures[t.dataset.dfPressure]=t.value===''?null:Number(t.value);delete s.checkSignature94;});return true;}
  if(t.dataset.dfCell){host.transact(()=>{const s=Deflection.edit(p,key,face);s.walls[+t.dataset.dfRow][t.dataset.dfCell]=t.value===''?null:Number(t.value);delete s.checkSignature94;});return true;}
  const k=t.dataset.df;if(['limit','base','grade'].includes(k))return true;if(!k)return false;host.transact(()=>{const s=Deflection.edit(p,key,face);s[k]=t.type==='checkbox'?t.checked:t.type==='number'||k==='floor'?(t.value===''?null:Number(t.value)):t.value;delete s.checkSignature94;if(k==='floor')s.selected=[];});return true;
 }
 function setFloor(host,floor){const {p,result}=host.get();if(!result.floors[floor-1])return;const current=Deflection.input(p,result,key,face).s;if(current.floor===floor&&Deflection.saved(p,key,face).floor94===floor)return;host.transact(()=>{const s=Deflection.edit(p,key,face);s.floorSelections94??={};s.floorSelections94[current.floor]={selected:current.selected,selectedColumns:current.selectedColumns||[],selection92:true};const prior=s.floorSelections94[floor];s.floor94=floor;s.selected=prior?.selected||[];s.selectedColumns=prior?.selectedColumns||[];s.selection92=!!prior;delete s.checkSignature94;});}
 function enter(host){const {p,result,floor}=host.get(),s=Deflection.saved(p,key,face);const target=result.floors[s.floor94-1]?s.floor94:floor;setFloor(host,target);host.viewFloor(target);}
 function pick(host,hit){if(!hit||!['WALL','COL'].includes(hit.kind))return;const {p,result,floor}=host.get();setFloor(host,floor);if(hit.kind==='WALL'){toggle(host,hit.id);return;}const available=Deflection.modelColumns(p,result,floor);if(hit.f&&hit.f!==floor||!available.some(c=>c.id===hit.id)){host.toast('此柱仅为邻层显示，请切换到对应楼层选择');return;}host.transact(()=>{const s=Deflection.edit(p,key,face),a=s.selectedColumns||[];s.selectedColumns=a.includes(hit.id)?a.filter(id=>id!==hit.id):[...a,hit.id];delete s.checkSignature94;});}
 function overlay(ctx,plot,host){if(!plot)return;const {p,result,floor}=host.get(),s=Deflection.saved(p,key,face);if(s.floor94!==floor)return;const walls=s.selection92?s.selected:Deflection.modelWalls(p,result,floor).map(w=>w.id);ctx.save();ctx.strokeStyle='#008ec7';ctx.lineWidth=2;ctx.setLineDash([4,3]);for(const h of plot.hits||[]){if(h.f&&h.f!==floor||!(h.kind==='WALL'?walls:(s.selectedColumns||[])).includes(h.id))continue;const r=h.r;ctx.strokeRect(plot.ox+(r.x-r.w/2)*plot.scale-3,plot.oy+(r.y-r.d/2)*plot.scale-3,r.w*plot.scale+6,r.d*plot.scale+6);}ctx.restore();}

 return {render,click,change,enter,setFloor,pick,overlay};
})();