function ExplorerUI(host){
 const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=x=>x===null||x===undefined?'—':typeof x==='number'?Number(x.toFixed(3)):esc(x),options=(arr,v)=>arr.map(x=>`<option value="${esc(x)}" ${String(x)===String(v)?'selected':''}>${esc(x)}</option>`).join('');
 let output=null,stamp='',chosen='',chosenFloor=0,busy=false,calculation=null,reportSection='A',reportDocument='';
 const btn=(label,action,extra='')=>`<button data-ex="${action}" ${extra}>${label}</button>`,field=(label,id,value,type='number',extra='')=>`<label class="field">${label}<input id="${id}" type="${type}" step="any" value="${esc(value)}" ${extra}></label>`,sel=(label,id,value,arr)=>`<label class="field">${label}<select id="${id}">${options(arr,value)}</select></label>`;
 function floorField(label,id,value,extra=''){const p=host.get().p;return '<label class="field">'+label+'<select id="'+id+'" '+extra+'>'+Array.from({length:p.total},(_,i)=>'<option value="'+(i+1)+'" '+(+value===i+1?'selected':'')+'>'+esc(FloorLevels.name(p,i+1))+'</option>').join('')+'</select></label>';}
 const assumption='<div class="notice"><b>单向板 · 默认简支梁</b><br>普通板自动找相对两边支承，两组均完整时选短跨；CS 按所选固定边单边传荷；MB / SB / TB 默认简支。CB 单独选择固定端。检查及配筋沿用 Excel v106 Section B。</div>';
 function state(){const raw=host.get(),h=ColumnLoads101.browsing()&&ColumnLoads101.matches(chosen,chosenFloor)?{...raw,viewFloor:raw.floor,floor:chosenFloor}:raw,list=Loading.members(h.p,h.result,h.floor);if(chosenFloor!==h.floor||!list.some(x=>x.token===chosen)){chosen='';chosenFloor=h.floor;}const selected=list.find(x=>x.token===chosen);if(selected?.kind!=='COL')ColumnLoads101.clear();const data=selected?Loading.input(h.p,h.floor,chosen):{};return {...h,list,selected,data};}
 function fresh(p){return output&&stamp===JSON.stringify(p);}
 function selectedResult(h){return fresh(h.p)?output.rows.find(x=>x.floor===h.floor&&x.token===chosen):null;}
 function picker(h){const m=h.selected;if(!m)return '<div class="notice">请在左侧 Plan 点选柱、梁或楼板，再选择 Check、A 抄、B 抄。</div>';const k=h.floor+'|'+m.token,e=h.p.explorer||{};return '<div class="notice"><b>当前选中：'+esc(m.id)+' · '+esc(m.kind==='SLAB'&&h.data.slabType==='CS'?'CS':m.member.displayKind||m.kind)+'</b><div class="row">'+`<label><input type="checkbox" id="ex-include" ${e.selected?.[k]?'checked':''}> Check</label>`+['A','B'].map(x=>`<label><input type="checkbox" data-report="${x}" data-token="${esc(m.token)}" ${e['report'+x]?.[k]?'checked':''}> ${x} 抄</label>`).join('')+'</div></div>';}
 function sectionAColumnCard(h){if(h.selected?.kind!=='COL')return '';const auto=!String(h.data.sectionAAreas||'').trim()||h.data.sectionAAreaMode==='auto';let detail=ColumnLoads101.table(h,auto);return '<details open><summary>Column / Transfer Column · A / B 共用面积法</summary><p>按相邻柱／墙支承线半跨划分几何受荷面积，或在下方手动填写。Section A、Section B 和柱 Check 共用 Loading 的总 DL、SDL、LL；总 DL 已含结构自重。</p>'+btn('自动计算面积','auto-a-column')+'<p class="muted">当前：'+(auto?'自动计算；模型变化后自动更新':'手动面积')+'</p>'+detail+'<details><summary>手动面积（普通柱／Transfer Column）</summary><p>自动传荷出错时，可直接输入承载面积。按楼层和荷载区域分组，使用 Loading 的总 DL＋SDL＋LL。</p><div class="row">'+floorField('起始楼层','ex-a-area-lo',h.floor)+floorField('结束楼层','ex-a-area-hi',h.p.total)+field('承载面积 m²','ex-a-area-value','')+field('荷载区域名称（留空用整层）','ex-a-area-name','','text')+'</div>'+btn('加入面积并保存','add-a-area')+'<p>每行：起始层, 结束层, A=面积m², 可选区域名。原 B、D 格式继续支持。</p><textarea id="ex-a-column-areas" rows="4" placeholder="例如：1, 5, A=16">'+esc(h.data.sectionAAreas||'')+'</textarea>'+btn('保存手动面积','save-a-column')+'</details><p class="muted">A / B 共用原 Excel 面积×楼层数×荷载的累加公式。自动面积先按几何半跨划分，重叠部分按柱参考点等距线分界，Opening 已扣除；传荷未确认仍显示几何范围，构件 Check 单独提示待补。</p></details>';}


 function sectionASupportField(m,o,cs){const current=cs?'Cantilever':(m.kind==='SLAB'&&o.sectionASupport==='Cantilever'?null:o.sectionASupport)||'跟随构件',names={'Simply-supported':'简支','End span':'端跨','Continuous':'连续','Cantilever':'悬臂'},automatic=cs||m.member.displayKind==='CB'?'悬臂':'简支',values=cs?['Cantilever']:m.kind==='SLAB'?['跟随构件','Simply-supported','End span','Continuous']:['跟随构件','Simply-supported','End span','Continuous','Cantilever'];return '<label class="field">Section A 支承类别<select id="ex-a-support">'+values.map(v=>'<option value="'+v+'" '+(current===v?'selected':'')+'>'+(v==='跟随构件'?'自动（当前：'+automatic+'）':names[v]+' · '+v)+'</option>').join('')+'</select></label>';}
 function sectionACard(h){const m=h.selected;if(!m||m.kind==='COL')return '';const c=m.member,o=h.data,cs=m.kind==='SLAB'&&o.slabType==='CS';let L;if(m.kind==='SLAB'){const dir=Loading.slabDirection(h.p,h.floor,m.token,c);L=dir==='X'?c.x1-c.x0:c.y1-c.y0;}else{const a=c.rawA||c.a,z=c.rawZ||c.z;L=Math.hypot(z[0]-a[0],z[1]-a[1]);}const a=Reports.sizing(h.p,{...m,floor:h.floor,loading:{L}});return '<div class="notice"><h3>Section A · 尺寸初筛</h3>'+sectionASupportField(m,o,cs)+'<p>此选择仅用于 A 的跨度／整体深度检查，同 Framing 共用。</p><p>L/h'+(a.support!=='Cantilever'&&a.L>10.001?'（含长跨修正）':'')+' = <b>'+num(a.ratio)+'</b>；限值 <b>'+num(a.limit)+'</b> · '+esc(a.status)+'</p><p class="muted">A：'+esc(a.support)+'。Section B 与传荷按构件的模型计算；普通板两侧传荷；CS 固定边单边传荷。连续内力未在这里计算。</p></div>';}
 document.addEventListener('change',e=>{if(e.target.id!=='ex-a-support')return;const value=e.target.value;if(value!=='跟随构件'&&!Object.hasOwn(Reports.supportLimits,value)){host.toast('请选择原 Excel 的支承类别');return;}memberSave(o=>{o.sectionASupport=value==='跟随构件'?null:value;},['sectionASupport']);});
 function selectPlanMember(hit){const h=host.get();if(h.key!==h.result.floors[h.floor-1].type){chosen='';ColumnLoads101.clear();return null;}chosenFloor=hit?.f||h.floor;const m=hit&&Loading.members(h.p,h.result,chosenFloor).find(x=>x.kind===hit.kind&&(x.member.id===hit.id||hit.kind==='SLAB'&&x.id===hit.slabId));chosen=m?.token||'';if(hit?.f&&hit.f!==h.floor)host.floor(hit.f);ColumnLoads101.select(m?.kind==='COL'?{floor:chosenFloor,token:chosen}:null);if(hit?.kind==='WALL')host.toast('墙目前只参与传荷，没有独立 Member Check');return m;}
 function renderLegacy(tab){const h=state(),cfg=Loading.settings(h.p),fl=Loading.floorload(h.p,h.floor),m=h.selected,o=h.data,rr=selectedResult(h);let html=assumption;
  if(tab==='loading'){
   html='<h2>Loading · '+esc(FloorLevels.name(h.p,h.floor))+'</h2>'+html+'<details><summary>共同材料与 Excel 默认参数</summary><div class="row">'+sel('Beam / Slab fcu','ex-fcu',cfg.fcu,[45,60])+sel('耐火 h','ex-fire',cfg.fire,[1,2,4])+'</div><div class="row">'+sel('TB fcu','ex-tbFcu',cfg.tbFcu,[45,60])+sel('TB 耐火 h','ex-tbFire',cfg.tbFire,[1,2,4])+'</div><div class="row">'+sel('Column fcu','ex-columnFcu',cfg.columnFcu,[25,30,35,40,45,50,55,60])+sel('Column 耐火 h','ex-columnFire',cfg.columnFire,[1,2,4])+'</div><div class="row">'+sel('Wall fcu','ex-wallFcu',cfg.wallFcu,Object.keys(Deflection.grades).map(g=>+g.slice(1)))+field('柱目标主筋率 %','ex-columnRatio',cfg.columnRatio)+field('柱有效长度系数','ex-columnFactor',cfg.columnFactor)+field('柱项目系数（Excel）','ex-columnProject',cfg.columnProject)+'</div>'+btn('保存共同参数','settings')+'<p class="muted">自重 24.5 kN/m³；G 系数 1.4、Q 系数 1.6；fy = 500。柱项目系数独立沿用 Excel，默认 1.25。</p></details><h3>楼层面荷载 · kPa</h3><div class="row">'+field('附加 DL（不含自重）','ex-dl',fl.dl)+field('SDL','ex-sdl',fl.sdl)+field('LL','ex-ll',fl.ll)+'</div><div class="row">'+sel('单向板跨向','ex-direction',fl.direction,['短跨','X','Y'])+floorField('从楼层','ex-lo',h.floor)+floorField('至楼层','ex-hi',h.floor)+'</div>'+btn('应用楼层荷载','floor')+'<p class="muted">空白表示资料未填，0 表示已确认无此荷载。可一次应用多层；每层各自保存。尺寸直接来自图中构件。</p><h3>构件局部输入</h3>'+picker(h);
   if(m){if(m.kind==='SLAB')html+='<p class="notice">普通板：自动选择完整相对支承边，两组均完整时选短跨。悬臂板请在 Member Check 选为 CS，并指定固定边。</p>';
    else if(m.kind==='COL')html+='<div class="row">'+sel('Column system','ex-system',o.system||'Braced',['Braced','Unbraced'])+field('有效长度系数（留空默认）','ex-factor',o.factor)+'</div><p class="muted">柱 Check 与 A / B 抄共用面积法荷载。柱尺寸取当前模型，详细轴压及配筋验算沿用原 Excel。</p>';
    else html+=BeamLoadUI.render(h,selectedResult(h))+(m.member.displayKind==='CB'?'<div class="row">'+cbFixedEndField(h)+field('CB cover mm（留空自动）','ex-cover',o.cover)+'</div><p class="muted">'+esc(cbRootHint(h))+'</p>':'');
    html+='<div class="row">'+btn('保存此构件 Loading','member')+btn('清除局部输入','reset')+'</div>';
   }
   html+='<div class="row">'+btn(busy?'计算中…':'计算 Section B Check','run',busy?'disabled':'')+btn('查看 Check','goto-checks')+'</div>';
  }else if(tab==='checks'){
   html='<h2>Member Check · '+esc(FloorLevels.name(h.p,h.floor))+'</h2>'+html+'<div class="row">'+btn(busy?'计算中…':'计算／更新 Check','run',busy?'disabled':'')+'</div>';
   if(!fresh(h.p))html+='<div class="notice">'+(output?'输入已变化，请重新计算。旧结果不会用于报告。':'填写 Loading 后点击“计算／更新 Check”。')+'</div>';
   html+='<p class="muted">柱、梁、板均由你勾选 Check，可选择多根柱。未勾选的构件仍参与全楼传荷；A 抄、B 抄分别选择。</p>';

   html+=picker(h)+(m&&m.kind!=='COL'&&m.kind!=='SLAB'&&m.member.d*1000>h.result.floors[h.floor-1].sh+1e-6?'<div class="issue">本层结构预留高度 '+num(h.result.floors[h.floor-1].sh)+' mm，小于梁深 '+num(m.member.d*1000)+' mm，请检查净高安排。共用 Framing 截面未自动修改。</div>':'')+(m?'<details open><summary>所选构件支承及特殊荷载</summary>'+memberInputs(h)+'</details>':'')+sectionACard(h)+sectionAColumnCard(h);if(rr){const d=rr.result;html+='<h3>'+esc(rr.id)+' · '+esc(d.status)+'</h3><div class="notice">'+esc(d.description)+'</div>'+(d.fail||[]).map(x=>'<div class="issue">'+esc(x)+'</div>').join('');if(rr.actions)html+='<p>M = '+num(rr.actions.M)+' kNm；V = '+num(rr.actions.V)+' kN</p>';if(rr.rootMoments?.length||rr.supportMoments?.length)html+='<div class="notice"><b>CS 固定边作用（每米边长）</b>'+(rr.rootMoments||rr.supportMoments).map(x=>'<p>'+esc(x.slab)+' → '+esc(x.supportId)+'：G '+num(x.g)+' kN/m；Q '+num(x.q)+' kN/m；M ULS '+num(x.mULS)+' kNm/m；边长 '+num(x.length)+' m</p>').join('')+'<small>根部弯矩已列出；承托构件及节点抗弯／抗扭须另行验算。</small></div>';if(rr.cbSupportMoments?.length)html+='<div class="issue">'+rr.cbSupportMoments.map(x=>'CB '+esc(x.id)+' 根部 M ULS = '+num(x.mULS)+' kNm（梁系弯矩／扭矩分配待分析）').join('<br>')+'</div>';if(rr.loading?.L)html+='<p>参考跨度 L = '+num(rr.loading.L)+' m</p>';if(rr.loadErrors?.length)html+='<div class="issue">Loading 待补：'+rr.loadErrors.map(esc).join('；')+'</div>';if((d.fail||[]).length||(rr.loadErrors||[]).length)html+=inlineColumnArea(h,rr,'B')+inlineRepair(h,rr,'Check');if(d.source)html+='<p class="muted">来源：'+esc(d.source)+'</p>';
    html+='<details><summary>查看计算结果及 Excel 单元格</summary><div class="table-wrap"><table><thead><tr><th>单元格</th><th>结果</th></tr></thead><tbody>'+Object.entries(d.values||{}).map(([k,v])=>'<tr><td>'+esc(k)+'</td><td>'+num(v)+'</td></tr>').join('')+'</tbody></table></div></details>';
   }
   if(m){const steel=o.steel||rr?.result.steel||{},get=(k,def='')=>steel[k]??def;html+='<h3>Section B 配筋</h3>'+sel('配筋模式','ex-steel-mode',o.steel?'MANUAL':'AUTO',['AUTO','MANUAL']);if(m.kind==='SLAB')html+='<div class="row">'+sel(o.slabType==='CS'?'顶部主筋 T':'主筋 T','ex-slab-dia',get('F35',12),[10,12,16,20,25,32])+sel('主筋间距 mm','ex-slab-space',get('H35',200),[100,150,200,250])+'</div><div class="row">'+sel('分布筋 T','ex-trans-dia',get('C57',10),[10,12,16,20,25])+sel('分布筋间距 mm','ex-trans-space',get('D57',250),[100,150,200,250])+'</div>';
    else if(m.kind==='COL')html+='<div class="row">'+sel('柱主筋 T','ex-col-dia',get('C5',32),[32,25,40])+field('根数','ex-col-count',get('C32',8))+'</div>';
    else{const counts=f=>Array.from({length:8},(_,i)=>get('C'+(f+i+(i>3?66:0)),0)).join(', '),dia=f=>get('D'+f,16);html+='<p class="muted">每面最多 8 层，同一面使用一个直径。每层根数以逗号分隔，0 表示该层无筋。CB 的受拉面位于上部。</p><div class="row">'+sel('受压面 T','ex-top-dia',dia(40),[10,12,16,20,25,32,40])+field('各层根数','ex-top-counts',counts(40),'text')+'</div><div class="row">'+sel('受拉面 T','ex-bottom-dia',dia(44),[10,12,16,20,25,32,40])+field('各层根数','ex-bottom-counts',counts(44),'text')+'</div><div class="row">'+field('抗剪肢数','ex-link-legs',get('E58',2))+sel('抗剪箍 T','ex-link-dia',get('G58',10),[8,10,12,16,20,25,32])+field('抗剪间距 mm','ex-link-space',get('H58',200))+'</div><div class="row">'+field('抗扭肢数','ex-tor-legs',get('E76',2))+sel('抗扭箍 T','ex-tor-dia',get('G76',8)||8,[8,10,12,16])+field('抗扭间距 mm','ex-tor-space',get('H76',250)||250)+'</div>';}
    html+='<div class="row">'+btn('保存配筋并检查','steel')+btn('恢复 Excel 自动选筋','auto-steel')+'</div>';
   }
   if(fresh(h.p)){const rows=output.rows.filter(r=>r.floor===h.floor);html+='<h3>本层全部构件</h3><div class="table-wrap"><table><thead><tr><th>选择</th><th>构件</th><th>Check</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+`<input type="checkbox" data-ex="include-row" data-token="${esc(r.token)}" ${h.p.explorer?.selected?.[h.floor+'|'+r.token]?'checked':''}>`+'</td><td>'+btn(esc(r.id),'choose',`data-token="${esc(r.token)}"`)+'</td><td>'+esc(r.result.status)+'</td></tr>').join('')+'</tbody></table></div>';html+=output.issues.filter(i=>i.floor===h.floor).map(i=>'<div class="issue">'+esc(i.msg)+'</div>').join('');}
  }else{
   html='<h2>Section A / Section B 抄</h2>'+html+'<p class="muted">Section A：尺寸初筛及荷载记录。Section B：采用配筋、计算数值及检查结果。两份报告与当前项目共用输入。</p><div class="row">'+floorField('从楼层','ex-report-lo',1)+floorField('至楼层','ex-report-hi',h.p.total)+'</div><div class="row">'+btn('Section A 抄','report-a')+btn('Section B 抄','report-b')+'</div><p class="muted">在 Section A / B 页面直接查看原 Excel 抄并 Print PDF；Excel 工作簿随抄生成，可在对应抄页打开。</p>';
  }
  return html;
 }

 function cbEndNames(c){const a=c.rawA||c.a,z=c.rawZ||c.z,dx=z[0]-a[0],dy=z[1]-a[1],side=(d,low,high)=>Math.abs(d)<1e-6?['','']:d>0?[low,high]:[high,low],x=side(dx,'左','右'),y=side(dy,'上','下');return {a:x[0]+y[0]+'端',z:x[1]+y[1]+'端'};}
 function cbFixedEndField(h){const names=cbEndNames(h.selected.member),v=h.data.fixedEnd;return '<label class="field">CB 固定端<select id="ex-fixedEnd">'+[['auto','自动判断'],['a',names.a],['z',names.z]].map(([value,label])=>'<option value="'+value+'" '+((['a','z'].includes(v)?v:'auto')===value?'selected':'')+'>'+label+'</option>').join('')+'</select></label>';}
 function cbRootHint(h){const root=Loading.cbRoot(h.p,h.result,h.floor,h.selected.member),names=cbEndNames(h.selected.member);return (root.fixedEnd?(root.mode==='auto'?'自动选择：':'手动选择：')+names[root.fixedEnd]+(root.connections[root.fixedEnd].length?'，连接'+root.connections[root.fixedEnd].join('、'):''):root.message)+'。方向以平面图为准。自动判断仅根据柱／墙的几何连接；节点抗弯约束未验算，可手动改选。';}

 function slabInputs(h){const m=h.selected,o=h.data,cs=o.slabType==='CS',dir=Loading.slabDirection(h.p,h.floor,m.token,m.member),labels={left:'左',right:'右',top:'上',bottom:'下'};
  let html='<label class="field">板类型<select id="ex-slab-type"><option value="SLAB" '+(!cs?'selected':'')+'>普通单向板 · 两侧传荷</option><option value="CS" '+(cs?'selected':'')+'>CS · Cantilever Slab 悬臂板</option></select></label>';
  if(cs)html+='<label class="field">CS 固定边（平面图方向）<select id="ex-cs-edge"><option value="">请选择固定边</option>'+Object.entries(labels).map(([k,v])=>'<option value="'+k+'" '+(o.csFixedEdge===k?'selected':'')+'>'+v+'边</option>').join('')+'</select></label><p>CS · '+(dir?'跨向 '+dir+'；悬挑长度 '+num(dir==='X'?m.member.x1-m.member.x0:m.member.y1-m.member.y0)+' m；荷载全部传到'+labels[o.csFixedEdge]+'边。':'请选择固定边后计算。')+'</p><p class="muted">指定边按完全固定、对边自由的单向悬臂模型计算，顶部主筋受拉。B 自重自动＋SDL＋LL；A 使用 Loading 的 DL。根部弯矩另列；承托梁抗扭、墙及节点抗弯须另行验算。</p>';
  else html+='<p class="notice">单向简支板 · 自动支承跨向 '+dir+' · 荷载传到'+(dir==='X'?'左、右':'上、下')+'两侧支承。荷载在 Loading 填写。</p>';
  return (o.supportConflicts?.length?'<p class="issue">同 Framing 各层存在不同的支承设置；请重新选择一次，统一所有同类型楼层。</p>':'')+html+'<small>按 Framing 共用板类型及固定边，选择后自动保存到所有同类型楼层；计算／更新 Check 后更新结果。</small>';
 }
 document.addEventListener('change',e=>{if(!['ex-slab-type','ex-cs-edge'].includes(e.target.id))return;const h=state();if(h.selected?.kind!=='SLAB')return;const v=e.target.value;if(e.target.id==='ex-slab-type'){if(!['SLAB','CS'].includes(v))return;memberSave(o=>{o.slabType=v;delete o.csFixedEdge;delete o.sectionASupport;},['slabType','csFixedEdge','sectionASupport']);}else if(['','left','right','top','bottom'].includes(v))memberSave(o=>{o.csFixedEdge=v;},['csFixedEdge']);});


 function supportValue(control,list){if(!control||control.closest('[hidden]'))return null;const typed=control.closest('.field')?.querySelector('[data-support-id]')?.value.trim();if(!typed)return control.value||'auto';const hits=list.filter(x=>[x.member.id,x.member.displayId,x.value].some(v=>v&&v.toLowerCase()===typed.toLowerCase()));if(hits.length!==1)throw Error(hits.length?'编号重复，请从 Support 列表选择构件':'该编号没有实际相接的构件，请核对位置或截面');return hits[0].value;}
 document.addEventListener('change',e=>{if(e.target.tagName==='SELECT'&&/support[AZ]$/.test(e.target.id)){const input=e.target.closest('.field')?.querySelector('[data-support-id]');if(input)input.value='';}});
 function beamSupportFields(h){const m=h.selected,model=Engine.floorModel(h.result,h.floor),names=cbEndNames(m.member),o=h.data,cb=m.member.displayKind==='CB',root=cb?Loading.cbRoot(h.p,h.result,h.floor,m.member):null,auto=root?(!!root.connections.a.length!==!!root.connections.z.length?(root.connections.a.length?'a':'z'):''):'',fixed=cb?(o.fixedEnd||auto):'';
 return '<details open class="beam-support-fields" data-cb="'+cb+'" data-auto-root="'+auto+'"><summary>'+ (cb?'固定端 Support':'手动补 Support（可选）')+'</summary><p>选择端部实际相接的 Column、Wall 或 Beam；保存后生效。同 Framing 共用，节点抗弯约束未验算。</p><p data-free-end '+(!cb?'hidden':'')+'>'+(!fixed?'请先选择 CB 固定端。':names[fixed==='a'?'z':'a']+'：自由端')+'</p><div class="row">'+[['a','supportA'],['z','supportZ']].map(([end,key])=>{const list=Loading.supportOptions(model,m.member,end),saved=o[key]||'auto',invalid=saved!=='auto'&&!list.some(x=>x.value===saved);return '<label class="field" data-support-end="'+end+'" data-end-name="'+names[end]+'" '+(cb&&fixed!==end?'hidden':'')+'>'+names[end]+' Support<select id="ex-'+key+'"><option value="auto" '+(saved==='auto'?'selected':'')+'>自动判断</option>'+(invalid?'<option value="'+esc(saved)+'" selected>原 Support 已失效，请重新选</option>':'')+[['COL','Column · 柱'],['WALL','Wall · 墙'],['BEAM','Beam · 梁']].map(([type,label])=>'<optgroup label="'+label+'">'+list.filter(x=>x.type===type).map(x=>'<option value="'+esc(x.value)+'" '+(saved===x.value?'selected':'')+'>'+esc(x.label)+'</option>').join('')+'</optgroup>').join('')+'</select><input type="text" data-support-id="'+key+'" maxlength="120" placeholder="也可输入构件编号，如 MB_7" aria-label="'+names[end]+' Support 构件编号"><small>'+(!list.length?'该端没有相接构件。':'按中心线或实际截面连接核对。')+'</small></label>';}).join('')+'</div></details>';
 }
 document.addEventListener('change',e=>{if(!e.target.id?.endsWith('fixedEnd'))return;const container=e.target.closest('.ex-inline-repair')||e.target.closest('#side')||e.target.parentElement.parentElement,block=container?.querySelector('.beam-support-fields[data-cb="true"]');if(!block)return;const fixed=['a','z'].includes(e.target.value)?e.target.value:block.dataset.autoRoot;block.querySelectorAll('[data-support-end]').forEach(n=>n.hidden=n.dataset.supportEnd!==fixed);const free=block.querySelector('[data-support-end="'+(fixed==='a'?'z':'a')+'"]');block.querySelector('[data-free-end]').textContent=fixed?free.dataset.endName+'：自由端':'请先选择 CB 固定端。';});

 function memberInputs(h){const m=h.selected,o=h.data,cfg=Loading.settings(h.p);if(m?.kind==='SLAB')return slabInputs(h);let html='';if(m){if(m.kind==='SLAB')html+='<p class="notice">普通板：自动选择完整相对支承边，两组均完整时选短跨。悬臂板请在 Member Check 选为 CS，并指定固定边。</p>';
    else if(m.kind==='COL')html+='<div class="row">'+sel('Column system','ex-system',o.system||'Braced',['Braced','Unbraced'])+field('有效长度系数（留空默认）','ex-factor',o.factor)+'</div><p class="muted">柱 Check 与 A / B 抄共用面积法荷载。柱尺寸取当前模型，详细轴压及配筋验算沿用原 Excel。</p>';
    else html+=BeamLoadUI.render(h,selectedResult(h))+(m.member.displayKind==='CB'?'<div class="row">'+cbFixedEndField(h)+field('CB cover mm（留空自动）','ex-cover',o.cover)+'</div><p class="muted">'+esc(cbRootHint(h))+'</p>':'');
    if(m.kind!=='SLAB'&&m.kind!=='COL')html+=beamSupportFields(h);html+='<div class="row">'+btn('保存荷载／支承','member')+btn('清除局部输入','reset')+'</div>';
   }
return html;}

 let activeArea='',areaPicking=false,activeFloor=0,currentPage='loading',groupFloors=false,viewFraming='all';
 const LD=LoadData;
 function scopeState(){const h=state();if(viewFraming!=='all'&&h.result.floors[h.floor-1]?.type!==viewFraming)viewFraming=h.result.floors[h.floor-1]?.type||'all';if(activeFloor!==h.floor){activeFloor=h.floor;activeArea='';areaPicking=false;}return h;}

 function shownFloors(h){return h.result.floors.filter(f=>viewFraming==='all'||f.type===viewFraming);}
 function scopedReportMap(h,section){const allowed=new Set(shownFloors(h).map(f=>f.n));return Object.fromEntries(Object.entries(h.p.explorer?.['report'+section]||{}).filter(([k,v])=>v&&allowed.has(+k.split('|')[0])));}
 function floorCheckState(h,f){const wanted=Object.keys(h.p.explorer?.selected||{}).filter(k=>k.startsWith(f+'|')&&h.p.explorer.selected[k]);if(!wanted.length)return {mark:'—',colour:'#7c8b95',label:'未选 Check',bad:[]};if(!fresh(h.p))return {mark:'待算',colour:'#936600',label:'输入已改变或尚未计算',bad:[]};const rows=output.rows.filter(r=>r.floor===f&&r.checked),bad=rows.filter(r=>!/^OK(?:$|[ (])/.test(r.result.status)||r.result.fail?.length||r.loadErrors?.length),missingKeys=wanted.filter(k=>!rows.some(r=>r.floor+'|'+r.token===k)),missing=missingKeys.length;return {mark:bad.length||missing?'✕':'✓',colour:bad.length||missing?'#bd2828':'#167348',label:bad.length||missing?'所选 Check 有 '+(bad.length+Math.max(0,missing))+' 项未通过／待补':'所选 '+rows.length+' 项 Check 已通过（按各构件检查范围）',bad,missing,missingKeys};}
 function floorStrip(h){const floors=shownFloors(h),types=[...new Set(h.result.floors.map(f=>f.type))],state=floorCheckState(h,h.floor);return '<label class="field">查看 Framing<select id="ex-view-framing"><option value="all" '+(viewFraming==='all'?'selected':'')+'>全部 Framing</option>'+types.map(t=>'<option value="'+esc(t)+'" '+(viewFraming===t?'selected':'')+'>'+esc(t)+'</option>').join('')+'</select></label><div class="ex-floors">'+floors.map(f=>{const x=floorCheckState(h,f.n);return btn(esc(FloorLevels.name(h.p,f.n))+' <span style="color:'+x.colour+'">'+x.mark+'</span>','floor-go',`data-floor="${f.n}" data-check-status="${x.mark}" aria-pressed="${f.n===h.floor}" title="${esc(f.type+' · '+x.label)}"`);}).join('')+'</div><small>✓ App 内所选构件检查通过；Excel 核对及抄的生成状态另行显示。✕ 未通过／待补；待算／— 不表示通过。</small>'+(state.bad.length||state.missing?'<details class="ex-floor-issues"><summary>'+esc(FloorLevels.name(h.p,h.floor))+' · '+esc(state.label)+'</summary>'+state.bad.map(r=>'<p>'+btn(esc(r.id),'report-fix',`data-floor="${r.floor}" data-token="${esc(r.token)}"`)+' '+esc(r.result.status)+'：'+esc(Reports.errorSummary([...(r.result.fail||[]),...(r.loadErrors||[])]).slice(0,2).join('；'))+'</p>').join('')+(state.missingKeys||[]).map(k=>'<p>构件已删除或几何／类型已改变：'+esc(k)+' '+btn('移除失效选择','remove-stale-selection',`data-key="${esc(k)}"`)+'</p>').join('')+'</details>':'');}
 document.addEventListener('change',e=>{if(e.target.id!=='ex-view-framing')return;const h=host.get(),v=e.target.value;if(v!=='all'&&!h.result.floors.some(f=>f.type===v))return;viewFraming=v;if(v!=='all'&&h.result.floors[h.floor-1]?.type!==v)host.floor(h.result.floors.find(f=>f.type===v).n);host.refresh();});

 function common(h){const cfg=Loading.settings(h.p),pair=(title,grade,fire,values)=>'<section class="ex-material-group"><h4>'+title+'</h4><div class="ex-material-pair">'+sel('Concrete Grade · fcu (MPa)','ex-'+grade,cfg[grade],values)+sel('FRR · 耐火时间 (h)','ex-'+fire,cfg[fire],[1,2,4])+'</div></section>';return '<details><summary>共同材料与 Excel 参数</summary>'+pair('普通梁 / Slab / CB / CS','fcu','fire',[45,60])+pair('TB · 转换梁','tbFcu','tbFire',[45,60])+pair('Column · 柱','columnFcu','columnFire',[25,30,35,40,45,50,55,60])+'<section class="ex-material-group"><h4>Wall · 墙</h4><div class="ex-material-pair">'+sel('Concrete Grade · fcu (MPa)','ex-wallFcu',cfg.wallFcu,Object.keys(Deflection.grades).map(g=>+g.slice(1)))+'</div></section>'+'<section class="ex-material-group"><h4>柱计算参数</h4><div class="ex-grid">'+field('柱目标主筋率 %','ex-columnRatio',cfg.columnRatio)+field('柱有效长度系数','ex-columnFactor',cfg.columnFactor)+field('柱项目系数','ex-columnProject',cfg.columnProject)+'</div></section>'+btn('保存共同参数','settings')+'</details>';}

 function loadCells(v,f,area='',to=f){const attrs=`data-floor="${f}" data-to="${to}" data-area="${esc(area)}"`;return '<td><select data-load="usage" '+attrs+'>'+options(['','手动',...UsageOptions.map(x=>x.name)],v.usage||'')+'</select></td>'+['dl','sdl','ll'].map(k=>'<td><input type="number" min="0" step="any" data-load="'+k+'" '+attrs+' value="'+esc(k==='ll'?LD.live(v):v[k])+'" '+(k==='ll'?'placeholder="'+esc(LD.live({...v,ll:null})??'需填写')+'"':'')+'></td>').join('');}
 function floorRows(h){const groups=[];for(const f of h.result.floors){const stamp=JSON.stringify([f.type,LD.floor(h.p,f.n),LD.areas(h.p,f.n)]),last=groups.at(-1);if(groupFloors&&last&&last.to===f.n-1&&last.stamp===stamp)last.to=f.n;else groups.push({n:f.n,to:f.n,stamp});}return groups.map(f=>{const v=LD.floor(h.p,f.n),label=esc(FloorLevels.range(h.p,f.n,f.to));return '<tr class="'+(h.floor>=f.n&&h.floor<=f.to?'ex-current':'')+'"><td>'+btn('×','clear-floor',`data-floor="${f.n}" data-to="${f.to}" title="清空所列楼层的默认荷载"`)+'</td><td>'+btn(label,'floor-go',`data-floor="${f.n}"`)+'</td>'+loadCells(v,f.n,'',f.to)+'</tr>';}).join('');}
 let rangeDraft={range:'',usage:'',dl:null,sdl:0,ll:null};
 document.addEventListener('change',e=>{if(!e.target.id?.startsWith('lp84-'))return;try{const h=host.get(),value=LoadPath84.readControls(h.p,h.result);store(ex=>{ex.loadPath84=value;});host.refresh();}catch(err){host.toast(err.message);}});
 document.addEventListener('input',e=>{const id=e.target.id||'';if(!id.startsWith('ex-range-'))return;const k=id.slice(9);if(['range','usage'].includes(k))rangeDraft[k]=e.target.value;else if(['lo','hi','dl','sdl','ll'].includes(k))rangeDraft[k]=e.target.value===''?null:Number(e.target.value);});
 document.addEventListener('change',e=>{if(e.target.id!=='ex-range-usage')return;rangeDraft.usage=e.target.value;rangeDraft.ll=LD.live({usage:rangeDraft.usage,ll:null});$('ex-range-ll').value=rangeDraft.ll??'';$('ex-range-default').textContent=LD.live({...rangeDraft,ll:null})??'需填写';});

 let rangeContext=null,rangeFloor=0;
 function syncRange(h){if(rangeContext!==h.p||rangeFloor!==h.floor){rangeContext=h.p;rangeFloor=h.floor;const v=LD.floor(h.p,h.floor);rangeDraft={range:esc(FloorLevels.name(h.p,h.floor))+'',lo:h.floor,hi:h.floor,usage:v.usage,dl:v.dl,sdl:v.sdl,ll:v.ll};}}
 function loadGroups(h){const groups=[];for(const f of h.result.floors){const value=LD.floor(h.p,f.n),stamp=JSON.stringify(value),last=groups.at(-1);if(last&&last.hi===f.n-1&&last.stamp===stamp)last.hi=f.n;else groups.push({lo:f.n,hi:f.n,stamp,value});}return groups;}
 function rangeForm(h){syncRange(h);const v=rangeDraft;return '<div class="ex-range-box"><h3>楼层输入 · 整层默认</h3><div class="ex-grid">'+field('起始层','ex-range-lo',v.lo,'number',`min="1" max="${h.p.total}" step="1"`)+field('结束层','ex-range-hi',v.hi,'number',`min="1" max="${h.p.total}" step="1"`)+sel('Usage','ex-range-usage',v.usage,['','手动',...UsageOptions.map(x=>x.name)])+field('Section A D.L. 含自重 · kPa','ex-range-dl',v.dl)+field('S.D.L. · kPa','ex-range-sdl',v.sdl)+field('L.L. · kPa','ex-range-ll',LD.live(v))+'</div><div class="row">'+btn('保存楼层荷载','apply-range')+btn('＋楼层组','new-load-group')+'</div><p class="muted">选择 Usage 自动填入 LL；选“手动”须自行填写。默认值：<b id="ex-range-default">'+esc(LD.live({...v,ll:null})??'需填写')+'</b>。只更新整层默认，已有区域荷载保留。</p></div>';}
 function loadGroupList(h){const groups=loadGroups(h).filter(g=>Object.hasOwn(h.p.explorer?.floors||{},g.lo)||g.value.dl!==null||g.value.usage);if(!groups.length)return '<p class="muted">尚未填写楼层荷载；例如起始 1、结束 10，一次填写 1–10/F。</p>';return '<div class="ex-load-groups">'+groups.map(g=>'<div class="ex-load-group">'+btn(esc(FloorLevels.range(h.p,g.lo,g.hi)),'edit-load-group',`data-lo="${g.lo}" data-hi="${g.hi}" title="查看 Framing 并编辑本组荷载"`)+'<span>'+esc(g.value.usage||'未选用途')+' · A DL '+num(g.value.dl)+' / B 自重自动 / SDL '+num(g.value.sdl)+' / LL '+num(LD.live(g.value))+'</span>'+btn('×','clear-floor',`data-floor="${g.lo}" data-to="${g.hi}" title="清空本组默认荷载，保留区域"`)+'</div>').join('')+'</div>';}
 function areaLoadFields(a,f){const attrs=`data-floor="${f}" data-to="${f}" data-area="${esc(a.id)}"`;return '<div class="ex-grid"><label class="field">Usage<select data-load="usage" '+attrs+'>'+options(['','手动',...UsageOptions.map(x=>x.name)],a.usage||'')+'</select></label>'+['dl','sdl','ll'].map((k,i)=>'<label class="field">'+['Section A D.L. 含自重 · kPa','S.D.L. · kPa','L.L. · kPa'][i]+'<input type="number" min="0" step="any" data-load="'+k+'" '+attrs+' value="'+esc(k==='ll'?LD.live(a):a[k])+'" placeholder="'+(k==='ll'?esc(LD.live({...a,ll:null})??'需填写'):'')+'"></label>').join('')+'</div>';}
 let groupContext=null,groupKey='',groupDraft=null,groupSource=null,groupRows=[],legendRows=[],legendFloor=null,legendSnapshot=null,groupPicking=false,groupDrag=null;
 function initGroup(h,force=false){if(force||groupContext!==h.p||groupKey!==h.key){groupContext=h.p;groupKey=h.key;const f=h.result.floors[h.floor-1]?.type===h.key?h.floor:h.result.floors.find(f=>f.type===h.key)?.n;const v=f?LD.floor(h.p,f):{};groupDraft={lo:f??'',hi:f??'',scope:'whole',name:'Area 1',usage:v.usage||'',dl:v.dl??null,sdl:v.sdl??0,ll:v.ll??null,panels:[]};groupSource=null;groupPicking=false;groupDrag=null;groupEditing=false;groupRemove84=false;}return groupDraft;}
 function readGroupForm(){if(!groupDraft)return;for(const k of ['lo','hi','name','scope','usage','dl','sdl','ll']){const el=$('lg-'+k);if(!el)continue;const v=el.value;groupDraft[k]=['lo','hi','dl','sdl','ll'].includes(k)?(v===''?null:Number(v)):v;}}
 let groupEditing=false,groupRemove84=false;
 function shownLoadingFloor(h){return h.result.floors[h.floor-1]?.type===h.key?h.floor:null;}
 function groupEditor(v){if(!groupEditing)return '';return '<div id="lg-editor" class="ex-range-box"><h3>'+(groupSource?'编辑荷载组':'新增荷载组')+'</h3><div class="ex-grid">'+floorField('起始层','lg-lo',v.lo)+floorField('结束层','lg-hi',v.hi)+'<label class="field">应用范围<select id="lg-scope"><option value="whole" '+(v.scope==='whole'?'selected':'')+'>整层</option><option value="area" '+(v.scope==='area'?'selected':'')+'>指定区域</option></select></label><div class="lg-wide">'+sel('Usage','lg-usage',v.usage,['','手动',...UsageOptions.map(x=>x.name)])+'</div>'+field('Section A D.L. 含自重 · kPa','lg-dl',v.dl)+field('S.D.L. · kPa','lg-sdl',v.sdl)+field('L.L. · kPa','lg-ll',LD.live(v))+'</div><p class="muted">Section A：使用你填写的 D.L.（含自重），再加 SDL、LL。Section B：自重自动计算，再加同一组 SDL、LL；不使用这里的 D.L.。做 Section A 时须填 D.L.，可填 0。</p><p class="muted">选择 Usage 自动填入 LL；选“手动”须自行填写。默认值：<b id="lg-default">'+esc(LD.live({...v,ll:null})??'需填写')+'</b></p>'+(v.scope==='area'?field('区域名称','lg-name',v.name,'text')+'<div class="row">'+btn(groupPicking?'结束框选':'在 Plan 拖框选范围','lg-pick')+btn(groupRemove84?'移除中（点击追加）':'框选移除','lg-remove-mode')+btn('清空选择','lg-clear')+btn('删除本层所选荷载','lg-delete-selected')+'</div><p class="muted">拖框追加整块 Slab；Alt＋拖框移除。粗边框表示选择，底色表示已保存荷载。</p>':'<p class="muted">更新所填楼层的默认荷载，已有区域荷载保留。</p>')+'<div class="row">'+btn('保存荷载组','lg-save')+btn('取消修改','lg-cancel')+'</div></div>';}
 function renderLoading(){const h=host.get(),v=initGroup(h),f=shownLoadingFloor(h);groupRows=LoadGroups.list(h.p,h.result,h.key);const allFloors=h.result.floors.filter(x=>x.type===h.key),legend=f?LoadGroups.overview(h.p,h.result,f):[],issues=f?LD.validate(h.p,f,Engine.floorModel(h.result,h.floor,h.key).slabs.map(s=>Loading.token('SLAB',s))):[];
  const floorButtons=allFloors.map(x=>{const c=LoadGroups.completion(h.p,h.result,x.n),description=esc(FloorLevels.name(h.p,x.n))+' · '+c.label+' · '+c.complete.toFixed(1)+'/'+c.total.toFixed(1)+' m²';return btn(esc(FloorLevels.name(h.p,x.n))+''+(c.status==='complete'?' ✓':''),'lg-floor',`data-floor="${x.n}" data-load-status="${c.status}" aria-pressed="${x.n===f}" aria-label="${description}" title="${description}"`);}).join('');
  legendRows=legend;legendFloor=f;legendSnapshot=f?LoadGroups.legendState(h.p,f):null;
  const legendHTML=legend.map((g,i)=>g.unassigned?'<div class="lg-legend-row"><span class="lg-swatch lg-unassigned">—</span><div><b>未分配荷载</b><span class="muted"> · '+g.panels.length+' 块板</span></div></div>':'<div class="lg-legend-row"><span class="lg-swatch" style="background:'+g.colour+'">'+g.number+'</span><div><b>'+esc(g.name)+'</b><span class="muted"> · '+g.panels.length+' 块板</span><div>A DL '+num(g.dl)+' · SDL '+num(g.sdl)+' · L.L. '+num(g.ll)+' <small>kPa</small></div>'+([g.sdl,g.ll].some(x=>x===null)?'<small class="lg-warning">荷载未填完整</small>':'')+'</div>'+btn('删除','lg-delete-legend',`data-legend="${i}" data-floor="${f}" class="lg-legend-delete" title="删除 ${f}/F 此项对应的 ${g.panels.length} 块板荷载设置；可撤销" aria-label="删除 ${f}/F ${esc(g.name)} 荷载"`)+'</div>').join('');
  const groups=groupRows.filter(g=>f&&g.refs.some(r=>r.f===f));
  return '<h2>Loading · '+esc(h.key)+'</h2>'+sel('查看 Framing','lg-framing',h.key,Object.keys(h.p.types))+'<p class="notice">单向板自动短跨 · 默认简支梁<br>Section A：手填 D.L.（含自重）＋SDL＋LL。<br>Section B：板、梁自重自动计算＋SDL＋LL。SDL、LL 共用（kPa）。</p><h3>楼层荷载</h3><div class="lg-floors" aria-label="查看整层荷载">'+(floorButtons||'<p class="muted">此 Framing 尚未分配楼层。</p>')+'</div><p class="lg-status-key"><span>□ 未填写</span><span class="lg-key-partial">■ 未填齐／待核对</span><span class="lg-key-complete">■ 已填齐 ✓</span></p><p class="muted">颜色按已保存荷载更新；深色边框表示正在查看。绿色仅表示输入完整（Section B：SDL、LL）；Section A 还须填写 D.L.。</p><section id="lg-overview"><h3>'+(f?esc(FloorLevels.name(h.p,f))+' · 全层荷载图':'全层荷载图')+'</h3><p class="muted">已分配荷载显示颜色；未分配保持无色。相同用途和荷载值共用一种颜色。</p><div class="lg-legend" aria-label="荷载颜色图例"><b>Legend · 荷载图例</b>'+(legendHTML||'<p class="muted">暂无可显示的楼板。</p>')+'<p class="muted lg-delete-note">删除仅影响当前楼层，可撤销；区域删除后采用整层默认荷载。</p></div>'+(issues.length?'<p class="lg-warning">'+issues.map(esc).join('<br>')+'</p>':'')+'</section><div class="lg-add"><div class="row">'+btn('＋荷载组','lg-new')+'</div>'+groupEditor(v)+'</div><details class="lg-manage"><summary>已保存荷载组 · '+(f?esc(FloorLevels.name(h.p,f))+'':'当前 Framing')+'（编辑／删除）</summary>'+(groups.length?groups.map(g=>'<div class="ex-load-group">'+btn(esc(FloorLevels.range(h.p,g.lo,g.hi))+' · '+(g.scope==='whole'?'整层':esc(g.value.name)),'lg-edit',`data-group="${g.id}"`)+'<span>'+esc(g.value.usage||'未选用途')+' · A DL '+num(g.value.dl)+' / B 自重自动 / SDL '+num(g.value.sdl)+' / LL '+num(LD.live(g.value))+'</span>'+btn('×','lg-delete',`data-group="${g.id}" title="删除本荷载组；覆盖 '+esc(FloorLevels.range(h.p,g.lo,g.hi))+'，可撤销"`)+'</div>').join(''):'<p class="muted">本层尚无已保存荷载组。</p>')+'</details><p class="muted">区域覆盖整层默认荷载，不叠加。区域组楼层须使用同一 Framing。</p>';
 }
 function highlights(){const h=host.get();if(currentPage!=='loading')return [];initGroup(h);const f=shownLoadingFloor(h),saved=f?LoadGroups.overview(h.p,h.result,f).map(g=>({...g,name:g.unassigned?'':g.number+' · '+g.name,active:false,overview:true})):[];
  if(groupEditing&&groupDraft.scope==='area'){const selected=new Set(previewPanels(h));saved.push({colour:'#0086d1',name:'',active:true,draft:true,rects:previewRects(h)});}return saved;
 }

 function previewRects(h){const chosen=new Set(previewPanels(h));return Engine.floorModel(h.result,h.floor,h.key).slabs.filter(s=>chosen.has(Loading.token('SLAB',s))).flatMap(s=>s.rects);}
 function previewPanels(h){const panels=groupDraft?.panels||[];if(!groupDrag)return panels;const box=groupBox(),picked=LoadGroups.pick(Engine.floorModel(h.result,h.floor,h.key).slabs,box);return groupDrag.remove?panels.filter(t=>!picked.includes(t)):[...new Set([...panels,...picked])];}
 function groupBox(){if(!groupDrag)return null;const {a,z}=groupDrag;return {x0:Math.min(a[0],z[0]),x1:Math.max(a[0],z[0]),y0:Math.min(a[1],z[1]),y1:Math.max(a[1],z[1])};}
 function beginArea(q,remove=false,tolerance=.02){const h=host.get();initGroup(h);if(!groupEditing||groupDraft.scope!=='area'||!groupPicking)return false;readGroupForm();groupDrag={a:q,z:q,remove:remove||groupRemove84,tolerance};host.repaint();return true;}
 function moveArea(q){if(!groupDrag)return false;groupDrag.z=q;host.repaint();return true;}
 function finishArea(cancel=false){if(!groupDrag)return false;const h=host.get(),d=groupDrag;let next=previewPanels(h);if(Math.hypot(d.a[0]-d.z[0],d.a[1]-d.z[1])<d.tolerance){const s=Engine.floorModel(h.result,h.floor,h.key).slabs.find(s=>s.rects.some(r=>d.z[0]>r.x0&&d.z[0]<r.x1&&d.z[1]>r.y0&&d.z[1]<r.y1));if(s){const t=Loading.token('SLAB',s);next=d.remove||groupDraft.panels.includes(t)?groupDraft.panels.filter(x=>x!==t):[...groupDraft.panels,t];}else next=groupDraft.panels;}
  if(!cancel){groupDraft.panels=next;delete groupDraft.rects;}groupDrag=null;host.refresh();return true;}
 async function groupAction(action,b){if(!action.startsWith('lg-'))return false;const h=host.get();initGroup(h);
  if(action==='lg-floor'){const f=Number(b.dataset.floor);if(!Number.isInteger(f)||h.result.floors[f-1]?.type!==h.key)throw Error('请选择当前 Framing 的楼层');host.floor(f);initGroup(host.get(),true);host.refresh();return true;}
  if(action==='lg-new'||action==='lg-cancel'){initGroup(h,true);if(action==='lg-new'){groupEditing=true;Object.assign(groupDraft,{usage:'',dl:10,sdl:0,ll:null});}host.refresh();return true;}
  if(action==='lg-edit'){const g=groupRows.find(g=>g.id===b.dataset.group);if(!g)throw Error('荷载组已变化，请重新选择');groupSource=JSON.parse(JSON.stringify(g));groupDraft={...g.value,scope:g.scope,lo:g.lo,hi:g.hi,name:g.value.name||'Area 1',panels:[...(g.value.panels||[])]};if(groupDraft.rects){groupDraft.panels=[...new Set(groupDraft.rects.flatMap(r=>LoadGroups.pick(Engine.floorModel(h.result,h.floor,h.key).slabs,r)))];delete groupDraft.rects;}groupPicking=g.scope==='area';groupEditing=true;host.refresh();return true;}
  if(action==='lg-delete-legend'){
   const f=Number(b.dataset.floor),i=Number(b.dataset.legend),g=legendRows[i],snapshot=legendSnapshot;
   if(f!==legendFloor||f!==shownLoadingFloor(h)||!Number.isInteger(i)||!g)throw Error('荷载图例已变化，请重新选择');
   let outcome;
   if(store((e,h)=>{outcome=LoadGroups.removeLegend(h.p,h.result,f,g,snapshot);})){initGroup(host.get(),true);host.refresh();host.toast(FloorLevels.name(h.p,f)+' 此项荷载已删除'+(outcome.restoredDefault?'，已恢复整层默认荷载':'')+'；可撤销，请保存项目文件');}
   return true;
  }
  if(action==='lg-delete'){const g=groupRows.find(g=>g.id===b.dataset.group);if(!g)throw Error('荷载组已变化');if(store((e,h)=>LoadGroups.remove(h.p,g))){initGroup(host.get(),true);host.refresh();}return true;}
  readGroupForm();if(action==='lg-remove-mode'){groupRemove84=!groupRemove84;groupPicking=true;b.textContent=groupRemove84?'移除中（点击追加）':'框选移除';return true;}if(action==='lg-delete-selected'){const chosen=[...groupDraft.panels];if(!chosen.length)throw Error('请先拖框选择 Slab');if(store((e,h)=>LoadGroups.removePanels(h.p,h.result,Number(groupDraft.lo),chosen))){initGroup(host.get(),true);host.refresh();host.toast('所选楼板的区域荷载已删除，恢复整层默认；可撤销');}return true;}if(action==='lg-pick'){groupPicking=!groupPicking;host.refresh();return true;}if(action==='lg-clear'){groupDraft.panels=[];delete groupDraft.rects;host.refresh();return true;}
  if(action==='lg-save'){const draft=JSON.parse(JSON.stringify(groupDraft)),source=groupSource;const done=store((e,h)=>LoadGroups.save(h.p,h.result,h.key,draft,source));if(done){if(host.get().result.floors[draft.lo-1]?.type===h.key)host.floor(draft.lo);initGroup(host.get(),true);host.refresh();host.toast('荷载组已保存，可撤销；请保存项目文件');}else{groupContext=host.get().p;groupDraft=draft;groupSource=source;groupEditing=true;host.refresh();}return true;}
  return false;
 }
 document.addEventListener('input',e=>{if(e.target.id?.startsWith('lg-')&&groupDraft)readGroupForm();});
 document.addEventListener('change',e=>{const id=e.target.id;if(id==='lg-framing'){host.framing(e.target.value);return;}if(!id?.startsWith('lg-')||!groupDraft)return;readGroupForm();if(id==='lg-usage'){groupDraft.ll=LD.live({usage:groupDraft.usage,ll:null});$('lg-ll').value=groupDraft.ll??'';$('lg-default').textContent=LD.live({...groupDraft,ll:null})??'需填写';}if(id==='lg-scope'){groupPicking=groupDraft.scope==='area';groupDrag=null;host.refresh();}});

 function columnSummary(h){return '<p class="muted">柱可在 Member Check 中点选并勾选 Check；全楼传荷仍逐层累积。</p>';}
 let memberTableOpen=false;
 function memberTable(h){
  const e=h.p.explorer||{},keys=new Set(['selected','reportA','reportB'].flatMap(name=>Object.entries(e[name]||{}).filter(([,v])=>v===true).map(([k])=>k))),floorKeys=new Set([...keys].map(k=>Number(k.split('|')[0])));
  const items=shownFloors(h).filter(f=>floorKeys.has(f.n)).flatMap(f=>Loading.members(h.p,h.result,f.n).filter(m=>keys.has(f.n+'|'+m.token)).map(m=>({...m,floor:f.n,framing:f.type})));
  if(!items.length)return '';
  return '<p class="muted">图中玫红边框：已勾选 Check；蓝色：当前点选。A／B 抄页面按各自勾选范围高亮。列表按查看 Framing 汇总各层；点构件编号可定位该层。</p><details id="ex-selected-members"'+(memberTableOpen?' open':'')+'><summary>'+(viewFraming==='all'?'全部 Framing':esc(viewFraming))+' · 已选构件 · '+items.length+'</summary><div class="table-wrap ex-members"><table><thead><tr><th>楼层</th><th>Framing</th><th>构件</th><th>Check</th><th>A 抄</th><th>B 抄</th></tr></thead><tbody>'+items.map(m=>{const k=m.floor+'|'+m.token,attrs=`data-floor="${m.floor}" data-token="${esc(m.token)}"`;return '<tr data-member-floor="'+m.floor+'" data-member-framing="'+esc(m.framing)+'"><td>'+esc(FloorLevels.name(h.p,m.floor))+'</td><td>'+esc(m.framing)+'</td><td>'+btn(esc(m.id),'choose',attrs)+'</td><td>'+`<input type="checkbox" data-ex="include-row" ${attrs} ${e.selected?.[k]?'checked':''}>`+'</td>'+['A','B'].map(x=>`<td><input type="checkbox" data-report="${x}" ${attrs} ${e['report'+x]?.[k]?'checked':''}></td>`).join('')+'</tr>';}).join('')+'</tbody></table></div></details>';
 }
 function selectionFloor(h,data){const f=data.floor===undefined?h.floor:Number(data.floor);if(!Number.isInteger(f)||!h.result.floors.some(x=>x.n===f))throw Error('楼层已改变，请重新选择构件');return f;}

 function reportAInputs(h){const notes=h.p.explorer?.reportANotes||{},src=SectionATemplate,get=r=>src.find(x=>x.row===r).cells[0][1],text=(label,id,v,required=false)=>'<label class="field">'+label+'<textarea id="'+id+'" rows="2"'+(required?' data-input-state="'+(/XXXX|____/.test(v)?'required':'default')+'"':'')+'>'+esc(v)+'</textarea></label>';
  return LoadPath84.controls(h.p,h.result)+'<details class="ex-report-notes"><summary>Section A · 报告文字与表格输入</summary><p>段落按 qqq1.pdf 顺序，表格及计算沿用原 Excel。场地条件和钢结构文字来自原模板，须按本项目核对后保存；楼层、DL、LL 自动读取现有输入。</p>'+text('Introduction','ex-a-introduction',notes.introduction??get(5),!notes.introduction)+text('Location','ex-a-location',notes.location??get(6),!notes.location)+'<details><summary>Site Constraints / Design Implications</summary>'+src.filter(x=>x.row>=10&&x.row<=17).map((x,i)=>'<div class="ex-material-pair">'+text('Site Constraint '+(i+1),'ex-a-constraint-'+i,(notes.constraints?.[i]||x.cells.map(c=>c[1]))[0],!notes.constraints)+text('Design Implications','ex-a-implication-'+i,(notes.constraints?.[i]||x.cells.map(c=>c[1]))[1],!notes.constraints)+'</div>').join('')+'</details>'+text('Steel grade assumption','ex-a-steel-grade',notes.steelGrade??get(34),!notes.steelGrade)+text('Steel D.L. assumption','ex-a-steel-dl',notes.steelDL??get(36),!notes.steelDL)+'<details><summary>Floor Summary · 净高 / E&amp;M Zone / 自动结构高度</summary><p>层高读取楼层设置。Structural Height = (层高 − Headroom − E&M Zone) × 1000 mm；保存后同步楼层与自动梁深。两项均留空保留手动结构高度。同一 Framing 的计算高度须一致，不同高度请在楼层页另设类型。</p>'+h.result.floors.map(f=>{const a=f.headroom!==undefined||f.em!==undefined?f:(h.p.explorer?.reportAFloors?.[f.n]||{});return '<div class="ex-material-pair">'+field(esc(FloorLevels.name(h.p,f.n))+' · Headroom (m)','ex-a-headroom-'+f.n,a.headroom,'number',a.headroom==null?'data-input-state="required"':'')+field(esc(FloorLevels.name(h.p,f.n))+' · E&amp;M Zone (m)','ex-a-em-'+f.n,a.em,'number',a.em==null?'data-input-state="required"':'')+'<div>'+esc(FloorLevels.name(h.p,f.n))+' · 层高 '+num(f.h)+' m · Structural Height <output id="ex-a-sh-'+f.n+'">'+num(f.sh)+' mm</output></div></div>';}).join('')+'</details>'+reportANarratives(h)+btn('保存报告文字与表格输入','save-a-report-notes')+'</details>';
 }
 function reportANarratives(h){const n=h.p.explorer?.reportANotes||{};return '<details><summary>3–6 整合版本 · 按 PDF 顺序编排</summary><p>文字、原图与比较表来自“3–6 整合版本”最终 Word；PDF 仅确定章节顺序。文字、尺寸和推荐结论均可编辑；不适用的章节取消勾选。保存后随项目文件保留。</p>'+SectionANotes.blocks.map(b=>'<details><summary>'+esc(b.title)+'</summary><label><input id="ex-a-enable-'+b.id+'" type="checkbox" '+((n.enabled?.[b.id]??b.enabled)!==false?'checked':'')+'> 输出本节</label><p class="muted">'+esc(b.source)+'</p><textarea id="ex-a-note-'+b.id+'" rows="7"'+(!Object.hasOwn(n.blocks||{},b.id)?' data-input-state="'+(b.required?'required':'default')+'"':'')+'>'+esc(n.blocks?.[b.id]??b.text)+'</textarea>'+(b.jointChoices?'<label class="field">Movement joints · 原文二选一<select id="ex-a-joint" '+(![0,1].includes(n.jointChoice)?'data-input-state="required"':'')+'><option value="">待选择</option>'+b.jointChoices.map((v,i)=>'<option value="'+i+'" '+(n.jointChoice===i?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label>':'')+(b.tables?'<details><summary>编辑原稿表格</summary>'+b.tables.map((t,ti)=>'<div class="copy-table-wrap"><table class="copy-table">'+t.map((row,ri)=>'<tr>'+row.map((v,ci)=>'<td><textarea rows="3" id="ex-a-table-'+b.id+'-'+ti+'-'+ri+'-'+ci+'"'+(!n.tables?.[b.id]?' data-input-state="default"':'')+'>'+esc(n.tables?.[b.id]?.[ti]?.[ri]?.[ci]??v)+'</textarea></td>').join('')+'</tr>').join('')+'</table></div>').join('')+'</details>':'')+'</details>').join('')+'</details>';}
 function saveAReportNotes(){const h=host.get(),before=h.p.explorer?.reportANotes||{},n={...before,blocks:{...before.blocks},tables:{...before.tables},enabled:{}},source=r=>SectionATemplate.find(x=>x.row===r).cells[0][1],put=(key,id,defaultValue)=>{const v=$(id).value;if(v!==defaultValue||Object.hasOwn(before,key))n[key]=v;};
  put('introduction','ex-a-introduction',source(5));put('location','ex-a-location',source(6));put('steelGrade','ex-a-steel-grade',source(34));put('steelDL','ex-a-steel-dl',source(36));
  const constraints=SectionATemplate.filter(x=>x.row>=10&&x.row<=17).map((x,i)=>[$('ex-a-constraint-'+i).value,$('ex-a-implication-'+i).value]);
  if(before.constraints||JSON.stringify(constraints)!==JSON.stringify(SectionATemplate.filter(x=>x.row>=10&&x.row<=17).map(x=>x.cells.map(c=>c[1]))))n.constraints=constraints;
  n.jointChoice=$('ex-a-joint').value===''?null:Number($('ex-a-joint').value);
  for(const b of SectionANotes.blocks){n.enabled[b.id]=$('ex-a-enable-'+b.id).checked;const v=$('ex-a-note-'+b.id).value;if(v!==b.text||Object.hasOwn(before.blocks||{},b.id))n.blocks[b.id]=v;if(b.tables){const tables=b.tables.map((t,ti)=>t.map((row,ri)=>row.map((v,ci)=>$('ex-a-table-'+b.id+'-'+ti+'-'+ri+'-'+ci).value)));if(before.tables?.[b.id]||JSON.stringify(tables)!==JSON.stringify(b.tables))n.tables[b.id]=tables;}}
  const floors={...h.p.explorer?.reportAFloors};for(const f of h.result.floors){const headroom=read('ex-a-headroom-'+f.n),em=read('ex-a-em-'+f.n);if([headroom,em].some(x=>x!==null&&(!Number.isFinite(x)||x<0)))throw Error('净高和 E&M Zone 须为非负数，或留空');floors[f.n]={headroom,em};}
  const ok=store(ex=>{Engine.applyClearances(h.p,floors);ex.reportANotes=n;ex.reportAFloors=floors;});if(ok)host.toast('Section A 文字和表格已保存；结构高度已更新');
 }

 function reportErrors(errors){if(!errors.length)return '';const summaries=Reports.errorSummary(errors);return '<div class="ex-report-errors"><ul>'+summaries.slice(0,4).map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>'+ (summaries.length>4?'<p>另有 '+(summaries.length-4)+' 项原因。</p>':'')+'<details><summary>展开原始传荷记录（'+errors.length+' 项）</summary><div class="ex-error-log">'+errors.map(s=>'<p>'+esc(s)+'</p>').join('')+'</div></details></div>';}

 function areaFormPrefix(r,section){return 'ex-inline-'+section+'-'+r.floor+'-'+encodeURIComponent(r.token);}
 function inlineColumnArea(h,r,section){if(r.kind!=='COL')return '';const id=areaFormPrefix(r,section),o=Loading.input(h.p,r.floor,r.token);return '<details open class="ex-inline-area"><summary>'+section+' · 柱／Transfer Column 面积备用</summary><div class="row">'+field('起始层',id+'-lo',r.floor)+field('结束层',id+'-hi',h.p.total)+field('面积 m²',id+'-area','')+field('区域名称（留空整层）',id+'-name','','text')+'</div><label class="field">已有分组（可直接修改；新增面积追加到下方）<textarea id="'+id+'-rows" rows="3" placeholder="1, 5, A=16">'+esc(o.sectionAAreas||'')+'</textarea></label>'+'<small>A / B 共用 Loading 已保存的总 DL、SDL、LL。</small>'+btn('采用面积并重算','inline-area-save',`data-floor="${r.floor}" data-token="${esc(r.token)}" data-section="${section}"`)+'</details>';}


 function inlineRepair(h,r,section){
  const id=areaFormPrefix(r,section)+'-repair',o=Loading.input(h.p,r.floor,r.token),selected=Loading.members(h.p,h.result,r.floor).find(x=>x.token===r.token);if(!selected)return '';
  const local={...h,floor:r.floor,selected,data:o},attrs=`data-floor="${r.floor}" data-token="${esc(r.token)}" data-section="${section}"`;let body='';
  if(r.kind!=='COL'&&r.kind!=='SLAB')body=beamSupportFields(local)+(r.member.displayKind==='CB'?cbFixedEndField(local):'');
  if(r.kind==='SLAB')body=sel('板类型','ex-slab-type',o.slabType||'SLAB',['SLAB','CS'])+'<label class="field">CS 固定边（普通板不使用）<select id="ex-cs-edge"><option value="">自动／未指定</option>'+Object.entries({left:'左',right:'右',top:'上',bottom:'下'}).map(([key,label])=>'<option value="'+key+'" '+(o.csFixedEdge===key?'selected':'')+'>'+label+'</option>').join('')+'</select></label>';
  body=body.replace(/id="ex-([^"]+)"/g,(_,key)=>'id="'+id+'-'+key+'"');
  if(body)body+=btn('保存 Support 并重算','inline-support-save',attrs);
  const loads=[{key:'floor',label:esc(FloorLevels.name(h.p,r.floor))+' 整层默认',value:LD.floor(h.p,r.floor)},...LD.areas(h.p,r.floor).map(a=>({key:a.id,label:esc(FloorLevels.name(h.p,r.floor))+' '+a.name,value:a}))];
  body+='<details><summary>补充 Loading 输入（保存到原 Loading）</summary><p>只修改实际缺项；区域荷载优先于整层默认。上层来源缺项请按错误标明的楼层修改。</p>'+loads.map(x=>{const pre=id+'-load-'+encodeURIComponent(x.key);return '<details><summary>'+esc(x.label)+'</summary><div class="row">'+field('总 DL kPa（A）',pre+'-dl',x.value.dl)+field('SDL kPa',pre+'-sdl',x.value.sdl)+field('LL kPa',pre+'-ll',LD.live(x.value))+'</div>'+btn('保存荷载并重算','inline-load-save',attrs+' data-area="'+esc(x.key)+'"')+'</details>';}).join('')+'</details>';
  body+='<p class="muted">未修改时保持原自动计算。手动 Support 只从实际相接构件中选；超出 Excel 模板的荷载形式，补输入也不会强行改为通过。</p>';
  return '<details open class="ex-inline-repair"><summary>在此补充／修改</summary>'+body+'</details>';
 }
 async function inlineRepairAction(action,b,h){
  if(!['inline-support-save','inline-load-save'].includes(action))return false;
  const f=Number(b.dataset.floor),t=b.dataset.token,section=b.dataset.section,id=areaFormPrefix({floor:f,token:t},section)+'-repair',m=Loading.members(h.p,h.result,f).find(x=>x.token===t);if(!m)throw Error('构件已改变，请重新选择');
  if(action==='inline-load-save'){const key=b.dataset.area,pre=id+'-load-'+encodeURIComponent(key),source=key==='floor'?LD.floor(h.p,f):LD.areas(h.p,f).find(a=>a.id===key);if(!source)throw Error('荷载区域已改变');const next={...source,...Object.fromEntries(['dl','sdl','ll'].map(k=>[k,read(pre+'-'+k)]))};LD.clean(next);store(()=>{if(key==='floor')LD.setFloor(h.p,f,next);else Object.assign(source,LD.clean(next));});}
  else{const v={},model=Engine.floorModel(h.result,f);let keys=[];
   if(m.kind==='SLAB'){v.slabType=$(id+'-slab-type').value;if(!['SLAB','CS'].includes(v.slabType))throw Error('请选择板类型');v.csFixedEdge=v.slabType==='CS'?($(id+'-cs-edge')?.value||''):null;if(v.slabType==='CS'&&!['left','right','top','bottom'].includes(v.csFixedEdge))throw Error('请选择 CS 固定边');v.sectionASupport=null;keys=['slabType','csFixedEdge','sectionASupport'];}
   else{for(const [end,key]of [['a','supportA'],['z','supportZ']]){const control=$(id+'-'+key);if(!control||control.closest('[hidden]')){v[key]=null;continue;}const value=supportValue(control,Loading.supportOptions(model,m.member,end));if(value!=='auto'&&!Loading.supportOptions(model,m.member,end).some(x=>x.value===value))throw Error('Support 必须是该端实际相接的构件');v[key]=value;}keys=['supportA','supportZ'];if(m.member.displayKind==='CB'){v.fixedEnd=['a','z'].includes($(id+'-fixedEnd').value)?$(id+'-fixedEnd').value:null;keys.push('fixedEnd');}}
   store(ex=>{const o={...Loading.input(h.p,f,t),...v};delete o.supportConflicts;ex.members[f+'|'+t]=o;Loading.saveFramingSupports(h.p,f,t,o,keys);});
  }
  await calculate();host.refresh();return true;
 }

 function reportSelection(h,section){const all=Object.keys(h.p.explorer?.['report'+section]||{}).filter(k=>h.p.explorer['report'+section][k]),scope=new Set(shownFloors(h).map(f=>f.n)),live=new Set(h.result.floors.flatMap(f=>Loading.members(h.p,h.result,f.n).map(m=>f.n+'|'+m.token))),current=all.filter(k=>scope.has(+k.split('|')[0])),stale=all.filter(k=>!live.has(k)&&(scope.has(+k.split('|')[0])||!h.result.floors[+k.split('|')[0]-1])),unchecked=section==='B'?current.filter(k=>live.has(k)&&!h.p.explorer?.selected?.[k]):[];return {all,current,stale,unchecked,hidden:all.filter(k=>h.result.floors[+k.split('|')[0]-1]&&!scope.has(+k.split('|')[0])).length};}
 function reportReadiness(h,section){const q=reportSelection(h,section);let html='';if(!q.all.length)html+='<p class="notice">本份尚未勾选 '+section+' 抄构件；Check 和 A／B 抄分别选择。</p>';if(q.hidden)html+='<p class="notice">'+q.hidden+' 个已选 '+section+' 抄构件被当前 Framing 筛选隐藏。'+btn('查看全部 Framing','report-show-all')+'</p>';if(q.unchecked.length)html+='<p class="notice">'+q.unchecked.length+' 个构件已选 B 抄但未勾选 Check，目前只会输出待补提示。'+btn('勾选本份构件 Check 并更新','report-enable-check',`data-section="${section}"`)+'</p>';if(q.stale.length)html+='<details open><summary>失效的报告选择 · '+q.stale.length+'</summary>'+q.stale.map(k=>'<p>'+esc(k)+' '+btn('清除本份失效选择','report-forget-stale',`data-key="${esc(k)}" data-section="${section}"`)+'</p>').join('')+'</details>';return html;}

 function renderReports(section){const h=scopeState(),reportOutput=fresh(h.p)?(section==='A'?Loading.run(h.p,h.result,'A'):output):null,chosenRows=reportOutput?reportOutput.rows.filter(r=>scopedReportMap(h,section)[r.floor+'|'+r.token]):[];return '<h2>Section '+section+' 抄</h2>'+assumption+(section==='A'?reportAInputs(h)+(typeof OverallReport!=='undefined'?OverallReport.sectionA(h.p):''):'')+reportReadiness(h,section)+'<p>在 Member Check 单独勾选本份抄的构件；两份抄可以不同。</p><div class="row">'+btn('选择要抄的构件','goto-checks')+btn('更新 Check','run')+'</div><div class="row">'+floorField('从楼层','ex-report-lo',1)+floorField('至楼层','ex-report-hi',h.p.total)+btn('生成原 Excel Section '+section+' 抄','preview-report',`data-section="${section}"`)+'</div>'+(!fresh(h.p)?'<div class="notice">输入或选择已改变，预览前会先更新检查。</div>':'<p>本份已选 '+chosenRows.length+' 个构件。</p>')+chosenRows.map(r=>'<div class="ex-report-row">'+esc(FloorLevels.name(h.p,r.floor))+' · '+esc(r.id)+' · '+esc(Reports.review(h.p,r,section).label)+' '+(Reports.review(h.p,r,section).errors.length?reportErrors(Reports.review(h.p,r,section).errors)+inlineColumnArea(h,r,section)+inlineRepair(h,r,section):'')+btn('查看／补齐','report-fix',`data-floor="${r.floor}" data-token="${esc(r.token)}"`)+' '+btn('到 Excel 核对','excel-row',`data-floor="${r.floor}" data-token="${esc(r.token)}"`)+'</div>').join('')+'<p class="muted">抄由原 Excel 宏生成并保存在工作簿内，直接在 Excel 查看输入、Check 和抄。不能对应原表的构件列为未核对。</p>';}

 function orphanCS(h){const live=new Set(h.list.filter(x=>x.kind==='SLAB').map(x=>h.floor+'|'+x.token));return Object.entries(h.p.explorer?.members||{}).filter(([k,v])=>k.startsWith(h.floor+'|SLAB|')&&v.slabType==='CS'&&!live.has(k)).map(([k])=>'<div class="issue">CS 板块几何已改变。清除同 Framing 的旧记录后，请在新板块重新指定 CS 及固定边。'+btn('清除这条失效 CS 记录','clear-orphan-cs','data-key="'+esc(k)+'"')+'</div>').join('');}

 function render(tab){const previousMembers=$('ex-selected-members');if(previousMembers)memberTableOpen=previousMembers.open;currentPage=tab;const h=scopeState();if(tab==='loading')return renderLoading();if(tab==='reportA'||tab==='reportB')return floorStrip(h)+renderReports(tab==='reportA'?'A':'B');let html=renderLegacy('checks');const cut=html.indexOf('<h3>本层全部构件');if(cut>=0)html=html.slice(0,cut);return common(h)+floorStrip(h)+orphanCS(h)+html+memberTable(h)+(h.selected?'<div class="row">'+btn('到 Excel 核对所选构件','excel-selected')+'</div><p class="muted">自动填写你的 RC Excel，执行原 Check 和抄；在窗口查看差异并打开原表。</p>':'');}
 function canvasClick(q){if(currentPage!=='loading')return false;const h=scopeState();if(!areaPicking)return true;const c=Engine.floorModel(h.result,h.floor).slabs.find(c=>c.rects.some(r=>q[0]>r.x0&&q[0]<r.x1&&q[1]>r.y0&&q[1]<r.y1));if(!c){host.toast('请选择楼板内部；Opening 和无楼板区域不能分配荷载');return true;}store((ex,h)=>LD.toggle(h.p,h.floor,activeArea,Loading.token('SLAB',c)));return true;}
 async function exportExcel(f,t){window.ExcelSync.open('RC','Check',{member:f+'|'+t});}
 async function newAction(action,b){if(await groupAction(action,b))return true;const h=scopeState(),a=LD.areas(h.p,h.floor).find(a=>a.id===(b.dataset.area||activeArea));
  if(await inlineRepairAction(action,b,h))return true;
  if(action==='inline-area-save'){const f=Number(b.dataset.floor),t=b.dataset.token,section=b.dataset.section,id=areaFormPrefix({floor:f,token:t},section),lo=read(id+'-lo',true),hi=read(id+'-hi',true),area=read(id+'-area'),name=$(id+'-name').value.trim();if(/[,，\n]/.test(name))throw Error('区域名不能有逗号或换行');let rows=$(id+'-rows').value.trim();if(area!==null){positive(area,'面积');rows=[rows,[lo,hi,'A='+area,...(name?[name]:[])].join(', ')].filter(Boolean).join('\n');}if(!rows)throw Error('请填写面积');Reports.parseColumnAreas(rows,h.p,f);store(ex=>{const o=ex.members[f+'|'+t]??={};o.sectionAAreas=rows;o.sectionAAreaMode='manual';ex.selected[f+'|'+t]=true;});await calculate();host.refresh();return true;}
  if(action==='new-load-group'){rangeContext=h.p;rangeFloor=h.floor;rangeDraft={lo:h.floor,hi:h.floor,usage:'',dl:null,sdl:0,ll:null};host.refresh();return true;}
  if(action==='edit-load-group'){const lo=+b.dataset.lo,hi=+b.dataset.hi;host.floor(lo);rangeContext=h.p;rangeFloor=lo;rangeDraft={lo,hi,...LD.floor(h.p,lo)};host.refresh();return true;}
  if(action==='apply-range'){const lo=$('ex-range-lo')?.value,hi=$('ex-range-hi')?.value,text=lo||hi?String(lo)+'-'+String(hi)+'/F':$('ex-range-range')?.value||'',values={usage:$('ex-range-usage').value,dl:read('ex-range-dl'),sdl:read('ex-range-sdl'),ll:read('ex-range-ll')};const range=LD.parseRange(text,h.p.total);rangeDraft={range:text,lo:range.lo,hi:range.hi,...values};rangeContext=h.p;rangeFloor=range.lo;const done=store((e,h)=>LD.applyRange(h.p,text,values));if(done){groupFloors=true;host.floor(range.lo);host.refresh();host.toast('已应用 '+FloorLevels.range(h.p,range.lo,range.hi)+' 默认荷载；Area 保留，可撤销');}return true;}
  if(action==='floor-go'){host.floor(+b.dataset.floor);host.refresh();return true;}
  if(action==='group-floors'){groupFloors=!groupFloors;host.refresh();return true;}
  if(action==='clear-floor'){store((e,h)=>{for(let f=+b.dataset.floor;f<=+(b.dataset.to||b.dataset.floor);f++)delete e.floors[f];});return true;}
  if(action==='confirm-floor'){store((e,h)=>LD.setFloor(h.p,h.floor,LD.floor(h.p,h.floor)));return true;}
  if(action==='copy-loads'){const lo=read('ex-copy-lo',true),hi=read('ex-copy-hi',true);store((e,h)=>LD.copy(h.p,h.result,h.floor,lo,hi,Loading.token));return true;}
  if(action==='add-area'){store((e,h)=>{activeArea=LD.addArea(h.p,h.floor).id;areaPicking=true;});return true;}
  if(action==='delete-area'){store((e,h)=>{e.areas[h.floor]=LD.areas(h.p,h.floor).filter(a=>a.id!==b.dataset.area);});if(activeArea===b.dataset.area){activeArea='';areaPicking=false;}host.refresh();return true;}
  if(action==='area-go'||action==='pick-area'){activeArea=b.dataset.area;areaPicking=action==='pick-area';host.refresh();return true;}
  if(action==='stop-area'){areaPicking=false;host.refresh();return true;}
  if(action==='area-details'){const name=$('ex-area-name').value.trim(),direction=$('ex-area-dir').value;if(!name)throw Error('请填写区域名称');store((e,h)=>{const target=LD.areas(h.p,h.floor).find(x=>x.id===activeArea);Object.assign(target,{name,direction});});return true;}
  if(action==='copy-all'||action==='copy-none'){store((e,h)=>{if(action==='copy-none'){for(const k of Object.keys(e['report'+b.dataset.section]||{}))if(k.startsWith(h.floor+'|'))delete e['report'+b.dataset.section][k];return;}for(const m of Loading.members(h.p,h.result,h.floor)){const k=h.floor+'|'+m.token;e['report'+b.dataset.section][k]=action==='copy-all'&&!!e.selected[k];}});return true;}
  if(action==='report-show-all'){viewFraming='all';host.refresh();return true;}
  if(action==='report-enable-check'){const section=b.dataset.section;if(section!=='B')return true;const q=reportSelection(h,section);store(ex=>{for(const k of q.unchecked)ex.selected[k]=true;});await calculate();return true;}
  if(action==='report-forget-stale'){const section=b.dataset.section;if(!['A','B'].includes(section))return true;const q=reportSelection(h,section);if(!q.stale.includes(b.dataset.key))throw Error('构件仍存在，请在 Member Check 调整勾选');store(ex=>{delete ex['report'+section][b.dataset.key];});return true;}
  if(action==='preview-report'){const section=b.dataset.section,lo=read('ex-report-lo',true),hi=read('ex-report-hi',true);if(!Number.isInteger(lo)||!Number.isInteger(hi)||lo<1||hi>h.p.total||lo>hi)throw Error('楼层范围无效');if(!fresh(h.p))await calculate();if(!fresh(h.p))throw Error('计算未完成');const map=scopedReportMap(h,section),rows=output.rows.filter(r=>r.floor>=lo&&r.floor<=hi&&map[r.floor+'|'+r.token]);if(!Object.keys(map).some(k=>map[k]&&+k.split('|')[0]>=lo&&+k.split('|')[0]<=hi)){if(section==='A'&&typeof OverallReport!=='undefined'&&OverallReport.sectionA(h.p).includes('data-copy-face=')){report(section,lo,hi);return true;}const q=reportSelection(h,section);if(q.hidden&&!q.current.length)throw Error('已选构件被当前 Framing 筛选隐藏，请选择正确 Framing 或查看全部');if(q.current.length)throw Error('当前楼层范围 '+FloorLevels.range(h.p,lo,hi)+' 不包含已选构件，请调整从／至楼层');throw Error('请先在 Member Check 勾选本份抄的构件');}report(section,lo,hi);return true;}
  if(action==='report-fix'){chosen=b.dataset.token;chosenFloor=+b.dataset.floor;host.focusMember(chosen,chosenFloor);host.tab('checks');return true;}
  if(action==='excel-selected'){await exportExcel(h.floor,chosen);return true;}if(action==='excel-row'){await exportExcel(+b.dataset.floor,b.dataset.token);return true;}return false;
 }
 document.addEventListener('change',e=>{const a=e.target,d=a.dataset||{};try{
  if(a.id==='ex-view-floor'){const f=Number(a.value);if(!Number.isInteger(f)||f<1||f>host.get().p.total)throw Error('楼层无效');host.floor(f);host.refresh();return;}
  if(a.id==='ex-area-select'){activeArea=a.value;areaPicking=false;host.refresh();return;}
  if(d.load){const area=d.area,v=a.value===''?null:Number(a.value);store((ex,h)=>{for(let f=+d.floor;f<=+(d.to||d.floor);f++){const old=area?LD.areas(h.p,f).find(x=>x.id===area):LD.floor(h.p,f),next={...old};if(d.load==='usage'){next.usage=a.value;next.ll=LD.live({usage:a.value,ll:null});}else next[d.load]=v;if(area)Object.assign(old,LD.clean(next));else LD.setFloor(h.p,f,next,false);}});}
  if(d.report)store((ex,h)=>ex['report'+d.report][selectionFloor(h,d)+'|'+d.token]=a.checked);
  if(a.id==='ex-floor-dir')store((ex,h)=>LD.setFloor(h.p,h.floor,{...LD.floor(h.p,h.floor),direction:a.value},false));
 }catch(err){host.toast(err.message);}});

 function calculate(){if(calculation)return calculation;calculation=calculateNow().finally(()=>{calculation=null;});return calculation;}
 async function calculateNow(){if(busy)return;busy=true;host.refresh();host.toast('正在按 Excel Section B 计算…');await new Promise(r=>setTimeout(r,40));try{const sizing=await BeamSizing83.apply(host);const h=host.get();output=Loading.run(h.p,h.result);stamp=JSON.stringify(h.p);host.toast('Check 已更新；梁宽调整 '+sizing.changes.length+' 次'+(sizing.stopped.length?'；'+sizing.stopped.map(x=>x.id+'：'+x.reason).join('；'):''));}catch(e){output=null;host.toast('计算未完成：'+e.message);}finally{busy=false;host.refresh();}}
 function read(id,required=false){const e=$(id);if(!e)return null;const str=e.value.trim();if(!str){if(required)throw Error('请填写 '+e.parentElement.textContent.trim());return null;}const v=Number(str);if(!Number.isFinite(v))throw Error('请输入有效数字');return v;}
 function positive(v,label){if(!(v>0))throw Error(label+' 须大于 0');return v;}
 function store(fn){const h=host.get();return host.transact(()=>{const ex=LoadData.init(h.p);fn(ex,h);});}
 function memberSave(fn,shareSupport=false){return store((ex,h)=>{const k=h.floor+'|'+chosen,o={...Loading.input(h.p,h.floor,chosen)};delete o.supportConflicts;fn(o);ex.members[k]=o;if(shareSupport)Loading.saveFramingSupports(h.p,h.floor,chosen,o,Array.isArray(shareSupport)?shareSupport:Loading.sharedSupportKeys);});}
 function report(section,lo,hi){const h=host.get();if(!fresh(h.p))throw Error('请先计算／更新 Check，再生成报告');reportSection=section;const reportOutput=section==='A'?Loading.run(h.p,h.result,'A'):output;const scoped={...reportOutput,floorScope:shownFloors(h).map(f=>f.n),reportA:scopedReportMap(h,'A'),reportB:scopedReportMap(h,'B')};const html=Reports.content(h.p,scoped,section,lo,hi);reportDocument=Reports.document(h.p,scoped,section,lo,hi);$('ex-report-content').innerHTML=html;$('ex-report-title').textContent='Section '+section+' 抄';$('ex-report-dialog').dataset.lo=lo;$('ex-report-dialog').dataset.hi=hi;if(!$('ex-report-dialog').open)$('ex-report-dialog').showModal();ReportPaper.prepare($('ex-report-content'));for(const img of $('ex-report-content').querySelectorAll('img'))img.addEventListener('load',()=>ReportPaper.prepare($('ex-report-content')),{once:true});}
 document.addEventListener('change',e=>{if(e.target.id==='ex-member'){chosen=e.target.value;chosenFloor=host.get().floor;const h=host.get(),m=Loading.members(h.p,h.result,chosenFloor).find(x=>x.token===chosen);ColumnLoads101.select(m?.kind==='COL'?{floor:chosenFloor,token:chosen}:null);host.refresh();}if(e.target.id==='ex-include'||e.target.dataset?.ex==='include-row'){const t=e.target.dataset.token||chosen,checked=e.target.checked;try{store((ex,h)=>ex.selected[selectionFloor(h,e.target.dataset)+'|'+t]=checked);}catch(err){host.toast(err.message);}}});
 document.addEventListener('input',e=>{const m=e.target.id?.match(/^ex-a-(?:headroom|em)-(\d+)$/);if(!m)return;const f=host.get().result.floors.find(x=>x.n===+m[1]);if(!f)return;try{$('ex-a-sh-'+f.n).textContent=Engine.structuralHeight({...f,headroom:read('ex-a-headroom-'+f.n),em:read('ex-a-em-'+f.n)})+' mm';}catch(err){$('ex-a-sh-'+f.n).textContent=err.message;}});
 document.addEventListener('click',async e=>{const b=e.target.closest('button[data-ex]');if(!b)return;const action=b.dataset.ex;try{if(await newAction(action,b))return;
  if(action==='remove-stale-selection'){const h=host.get(),k=b.dataset.key,f=Number(k?.split('|')[0]),t=k?.slice(String(f).length+1);if(!Number.isInteger(f)||!h.result.floors[f-1])throw Error('楼层不存在');if(Loading.members(h.p,h.result,f).some(m=>m.token===t))throw Error('构件仍存在，请在构件列表调整勾选');store(ex=>{for(const map of ['selected','reportA','reportB'])delete ex[map][k];});await calculate();return;}if(action==='run'){await calculate();return;}if(action.startsWith('goto-')){host.tab(action.slice(5));return;}if(action==='choose'){chosen=b.dataset.token;chosenFloor=selectionFloor(host.get(),b.dataset);host.focusMember(chosen,chosenFloor);return;}
  if(action==='save-a-report-notes'){saveAReportNotes();return;}
  if(action==='settings'){const v={};for(const k of Object.keys(Loading.defaults))v[k]=positive(read('ex-'+k,true),k);v.wallFcu=read('ex-wallFcu')??Loading.defaults.wallFcu;if(v.wallFcu!==null&&!Object.hasOwn(Deflection.grades,'C'+v.wallFcu))throw Error('请选择有效 Wall 混凝土等级');if(v.columnRatio>6)throw Error('柱目标配筋率须不大于 6%');store(ex=>ex.settings=v);}
  if(action==='floor'){const h=host.get(),lo=read('ex-lo',true),hi=read('ex-hi',true);if(!Number.isInteger(lo)||!Number.isInteger(hi)||lo<1||hi>h.p.total||lo>hi)throw Error('楼层范围无效');const load={dl:read('ex-dl'),sdl:read('ex-sdl'),ll:read('ex-ll'),direction:$('ex-direction').value};if(['dl','sdl','ll'].some(k=>load[k]!==null&&load[k]<0))throw Error('荷载不能为负数');store(ex=>{for(let f=lo;f<=hi;f++)ex.floors[f]={...load};});}
  if(action==='member'){const h=state(),v={};if(h.selected.kind==='SLAB'){host.toast('板类型和固定边选择后自动保存');return;}
   else if(h.selected.kind==='COL'){v.system=$('ex-system').value;v.factor=read('ex-factor');if(v.factor!==null)positive(v.factor,'有效长度系数');}
   else{Object.assign(v,BeamLoadUI.read(h));const supportModel=Engine.floorModel(h.result,h.floor);v.supportA=supportValue($('ex-supportA'),Loading.supportOptions(supportModel,h.selected.member,'a'));v.supportZ=supportValue($('ex-supportZ'),Loading.supportOptions(supportModel,h.selected.member,'z'));v.torsion=$('ex-torsion')?read('ex-torsion'):(h.data.torsion??0);if($('ex-fixedEnd')){v.fixedEnd=['a','z'].includes($('ex-fixedEnd').value)?$('ex-fixedEnd').value:null;v.cover=read('ex-cover');if(v.cover!==null&&(!Number.isFinite(v.cover)||v.cover<=0))throw Error('保护层须大于 0；留空按 FRR 自动取值');}}
   for(const [k,x]of Object.entries(v))if(typeof x==='number'&&x<0)throw Error('输入不能为负数');memberSave(o=>Object.assign(o,v),h.selected.kind!=='COL'?['supportA','supportZ','fixedEnd']:false);}
  if(action==='auto-a-column'){memberSave(o=>{o.sectionAAreaMode='auto';});host.toast('A / B 柱面积已切换为自动计算');}
  if(action==='b-area-mode'){const h=state();if(!String(h.data.sectionAAreas||'').trim())throw Error('请先保存手动面积及楼层范围');Reports.parseColumnAreas(h.data.sectionAAreas,h.p,h.floor);memberSave(o=>{o.mode='area';});return;}
  if(action==='b-auto-mode'){memberSave(o=>{o.mode='auto';});return;}
  if(action==='save-b-area'){const sw=read('ex-area-slab-sw'),extra=read('ex-area-extra-dead',true);if(sw!==null&&(!Number.isFinite(sw)||sw<0)||!Number.isFinite(extra)||extra<0)throw Error('结构自重不能为负');memberSave(o=>{o.areaSlabSW=sw;o.areaExtraDead=extra;});return;}
  if(action==='add-a-area'){const h=state(),lo=read('ex-a-area-lo',true),hi=read('ex-a-area-hi',true),area=positive(read('ex-a-area-value',true),'承载面积'),name=$('ex-a-area-name').value.trim();if(/[,，\n]/.test(name))throw Error('区域名称不能包含逗号或换行');const line=[lo,hi,'A='+area,...(name?[name]:[])].join(', '),value=[$('ex-a-column-areas').value.trim(),line].filter(Boolean).join('\n');Reports.parseColumnAreas(value,h.p,h.floor);memberSave(o=>{o.sectionAAreas=value;o.sectionAAreaMode='manual';});host.toast('已保存手动面积，A / B 按 Loading 的 DL＋SDL＋LL 计算');return;}
  if(action==='save-a-column'){const h=state();Reports.parseColumnAreas($('ex-a-column-areas').value,h.p,h.floor);memberSave(o=>{o.sectionAAreas=$('ex-a-column-areas').value;o.sectionAAreaMode='manual';});host.toast('A / B 柱承载面积已保存');}
  if(action==='clear-orphan-cs'){const key=b.dataset.key,h=state(),live=new Set(h.list.filter(x=>x.kind==='SLAB').map(x=>h.floor+'|'+x.token));if(key?.startsWith(h.floor+'|SLAB|')&&!live.has(key)&&h.p.explorer?.members?.[key]?.slabType==='CS')store((ex,h)=>Loading.clearFramingRecord(h.p,h.floor,key.slice(String(h.floor).length+1)));return;}
  if(action==='reset'){BeamLoadUI.clear();store((ex,h)=>{Loading.saveFramingSupports(h.p,h.floor,chosen,{});delete ex.members[h.floor+'|'+chosen];});}
  if(action==='steel'||action==='auto-steel'){const h=state();let steel=null;if(action==='steel'&&$('ex-steel-mode').value==='MANUAL'){steel={};if(h.selected.kind==='SLAB'){for(const [k,id]of Object.entries({F35:'slab-dia',H35:'slab-space',C57:'trans-dia',D57:'trans-space'}))steel[k]=positive(read('ex-'+id,true),id);}
    else if(h.selected.kind==='COL'){steel.C5=read('ex-col-dia',true);steel.C32=positive(read('ex-col-count',true),'根数');if(!Number.isInteger(steel.C32))throw Error('钢筋根数须为整数');}
    else{for(const [f,prefix]of [[40,'top'],[44,'bottom']]){const counts=$('ex-'+prefix+'-counts').value.split(/[,，]/).map(x=>Number(x.trim()));if(counts.length>8||counts.some(x=>!Number.isInteger(x)||x<0))throw Error('每面最多 8 层，各层根数为非负整数');const d=read('ex-'+prefix+'-dia',true);for(let i=0;i<8;i++){const r=f+i+(i>3?66:0),n=counts[i]||0;steel['C'+r]=n||'';steel['D'+r]=n?d:'';}}for(const [k,id]of Object.entries({E58:'link-legs',G58:'link-dia',H58:'link-space',E76:'tor-legs',G76:'tor-dia',H76:'tor-space'}))steel[k]=positive(read('ex-'+id,true),id);if(!Number.isInteger(steel.E58)||!Number.isInteger(steel.E76))throw Error('箍筋肢数须为整数');}
   }memberSave(o=>o.steel=steel);await calculate();return;}
  if(action==='report-a'||action==='report-b'){host.tab(action==='report-a'?'reportA':'reportB');return;}
  if(action==='report-close')$('ex-report-dialog').close();
  if(action==='report-copy'){const txt=Reports.text($('ex-report-content').innerHTML);let copied=false;try{await navigator.clipboard.writeText(txt);copied=true;}catch{let ta;try{ta=document.createElement('textarea');ta.value=txt;document.body.append(ta);ta.select();copied=!!document.execCommand('copy');}catch{}finally{ta?.remove();}}if(copied)host.toast('已复制 Section '+reportSection+' 抄');else{host.download('Section_'+reportSection+'_抄.txt',txt,'text/plain');host.toast('浏览器未允许剪贴板，已下载文字版');}}
  if(action==='report-download'){const h=host.get(),d=$('ex-report-dialog').dataset;host.download('Section_'+reportSection+'_抄_'+d.lo+'-'+d.hi+'F.html',reportDocument,'text/html');}
  if(action==='report-print'){const d=$('ex-report-dialog');d.close();const st=document.createElement('style');st.id='ex-print-style';st.textContent='@page{size:A4 portrait;margin:14mm}@media print{body>.print-page{width:auto!important;height:auto!important;overflow:visible!important} .print-page .check-report{font:10pt Arial;color:#233e3c}.print-page table{width:100%;table-layout:auto;font-size:9pt}.print-page th,.print-page td{white-space:normal;overflow-wrap:anywhere;padding:5px;border:1px solid #bbb}.print-page th{position:static}.print-page h2,.print-page h3{break-after:avoid}.member-report{break-inside:avoid}.report-heading{display:block!important;height:auto!important;background:white!important;color:#233e3c!important;padding:0!important}.print-page p{line-height:1.5}.print-page .assumption{padding:8px;background:#eef5f1}}';st.textContent+=ReportPaper.css;document.head.append(st);$('printpage').innerHTML=$('ex-report-content').innerHTML;const clean=()=>{st.remove();window.removeEventListener('afterprint',clean);};window.addEventListener('afterprint',clean);window.print();}
 }catch(err){host.toast(err.message);}});
 return {clearSelection(){chosen='';chosenFloor=0;ColumnLoads101.clear();BeamLoadUI.clear();},resetProject(){ColumnLoads101.clear();BeamLoadUI.clear();groupEditing=false;groupContext=null;groupDraft=null;groupSource=null;groupDrag=null;groupPicking=false;output=null;stamp='';chosen='';chosenFloor=0;activeArea='';areaPicking=false;activeFloor=0;groupFloors=false;rangeDraft={range:'',usage:'',dl:null,sdl:0,ll:null};$('ex-report-content').innerHTML='';if($('ex-report-dialog').open)$('ex-report-dialog').close();},beamInputs(hit){selectPlanMember(hit);const h=state();return h.selected&&["MB","SB","TB","CB"].includes(h.selected.kind)?"<h3>"+esc(h.selected.id)+"</h3>"+memberInputs(h):"<p class=muted>在左侧选择一根梁后输入。</p>";},render,calculate,highlights,canvasClick,beginArea,moveArea,finishArea,groupBox,selectPlanMember,openMember(hit){const h=host.get();if(h.key!==h.result.floors[h.floor-1].type){host.toast(h.key+' 尚未分配到楼层；请先在楼层表绑定后再做 Member Check');return;}if(hit.kind==='WALL'){host.toast('墙目前只传递荷载，不增加 Excel 以外的墙 Check');return;}const f=hit.f||h.floor,m=Loading.members(h.p,h.result,f).find(x=>x.member.id===hit.id&&x.kind===hit.kind||hit.kind==='SLAB'&&x.kind==='SLAB'&&x.id===hit.slabId);if(m){chosen=m.token;chosenFloor=f;host.focusMember(chosen,f);}},getOutput:()=>output};
}