const Overall=(()=>{
 const D=OverallSource,roles=D.roles,inputs=D.inputs,num=x=>typeof x==='number'&&Number.isFinite(x),blank=x=>x===null||x===undefined,flat=x=>x.flat(Infinity),own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
 const defaults=face=>Object.fromEntries(inputs.map(m=>[m.key,(face==='D'?m.defaultD:m.default)??null]));
 function normalize(x,face){const d=defaults(face);for(const m of inputs)if(x&&own(x,m.key)){const v=x[m.key];if(v===null||v===''||num(v)||m.rules.includes('t')&&typeof v==='string')d[m.key]=v===''?null:v;else throw Error('无效的 Excel 输入：'+m.key);}return d;}
 function validate(x,face){const n=normalize(x,face),b=n.basement==='Yes',has=v=>num(v);if(!['Yes','No'].includes(n.basement))return 'Select Basement Yes / No';if(!['UNIFORM','LAYERED'].includes(n.mode))return 'Select wind mode';for(const m of inputs){const v=n[m.key],a=face==='D'?m.sourceD:m.input;if(m.rules.includes('b')&&!b)continue;if(m.key==='height'){if(!has(v))return 'Enter building top mPD';continue;}if(m.rules.includes('t'))continue;if(blank(v)){if(!m.rules.includes('o'))return 'Enter '+m.key+' ('+a+')';}else{if(!has(v))return 'Number required: '+a;if(m.rules.includes('p')&&v<=0)return 'Positive value required: '+a;if(m.rules.includes('n')&&v<0)return 'Non-negative value required: '+a;}}
  if(![n.height,n.leftEL,n.baseRL].every(has))return 'Enter roof, left ground and O levels (mPD)';if(!has(n.rightEL))return 'Enter right ground level for wind pressure height (mPD)';if(n.height<=n.rightEL)return 'Roof must be above right ground';if(n.height<=n.leftEL)return 'Roof must be above left ground';if(n.leftEL<n.baseRL)return 'Left ground is below O: review model';if(n.mode==='LAYERED'){const hs=inputs.filter(m=>m.key.startsWith('layerH')).map(m=>n[m.key]).filter(num);if(!hs.length||Math.abs(hs.reduce((a,b)=>a+b,0)-(n.height-n.leftEL))>.001)return 'Layered wind heights must sum to roof minus left ground';}return '';
 }
 const number=x=>{if(blank(x)||x==='')return 0;if(num(x))return x;if(typeof x==='boolean')return +x;if(typeof x==='string'&&x.trim()!==''&&Number.isFinite(+x))return +x;throw Error('#VALUE!');};
 function compare(a,b){if(blank(a))a=typeof b==='string'?'':typeof b==='boolean'?false:0;if(blank(b))b=typeof a==='string'?'':typeof a==='boolean'?false:0;if(typeof a===typeof b){if(typeof a==='string'){a=a.toUpperCase();b=b.toUpperCase();}return a<b?-1:a>b?1:0;}const rank=v=>typeof v==='boolean'?2:typeof v==='string'?1:0;return rank(a)-rank(b);}
 function format(v,fmt='0.000'){if(blank(v))v=0;if(!num(v))return String(v);const section=fmt.split(';')[0],percent=section.includes('%'),dec=(section.match(/\.([0#]+)/)||[])[1]||'',min=(dec.match(/0/g)||[]).length,max=dec.length;if(!/[0#]/.test(section))return String(v);const result=new Intl.NumberFormat('en-US',{useGrouping:section.includes(','),minimumFractionDigits:min,maximumFractionDigits:max}).format(percent?v*100:v);return result+(section.includes('.')&&!result.includes('.')?'.':'')+(percent?'%':'');}
 const letters=n=>{let s='';for(;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;},coord=a=>{const m=a.match(/^([A-Z]+)(\d+)$/);if(!m)throw Error('Unsupported reference '+a);return [Number(m[2]),[...m[1]].reduce((v,c)=>v*26+c.charCodeAt(0)-64,0)];};
 function machine(x,face='B'){
  const state=normalize(x,face),over={},cache={},busy=new Set(),errors={};const set=(s,a,v)=>over[s+'!'+a]=v;
  for(const m of inputs)set(roles[m.role],m.cell,state[m.key]);set(roles[3],'B9',state.gammaWater);set(roles[3],'B10',state.submergedLeft);set(roles[1],'B9',num(state.height)&&num(state.leftEL)?state.height-state.leftEL:null);set(roles[1],'AZ130',over[roles[1]+'!B9']);
  for(const s of Object.values(roles))set(s,'A1',face+' - '+(s==='抄'?'Copy':s));set(roles[5],'D3',face);
  function range(s,r){let sheet=s,a=r;if(r.includes('!')){const i=r.lastIndexOf('!');sheet=r.slice(0,i).replace(/^'|'$/g,'').replace(/''/g,"'");a=r.slice(i+1);}if(!a.includes(':'))return get(sheet,a);const [first,last]=a.split(':'),[r0,c0]=coord(first),[r1,c1]=coord(last),out=[];for(let rr=r0;rr<=r1;rr++)for(let c=c0;c<=c1;c++)out.push(get(sheet,letters(c)+rr));return out;}
  function ev(a,s){const [kind,k]=a;if(kind==='v')return k;if(kind==='r')return range(s,k);if(kind==='err')throw Error(k);if(kind==='u')return k==='-'?-number(ev(a[2],s)):number(ev(a[2],s));if(kind==='b'){const av=ev(a[2],s),bv=ev(a[3],s);if(k==='&')return String(av??'')+String(bv??'');const cmp=compare(av,bv);if(k==='=')return cmp===0;if(k==='<>')return cmp!==0;if(k==='<')return cmp<0;if(k==='>')return cmp>0;if(k==='<=')return cmp<=0;if(k==='>=')return cmp>=0;const x=number(av),y=number(bv);if(k==='+')return x+y;if(k==='-')return x-y;if(k==='*')return x*y;if(k==='/'){if(y===0)throw Error('#DIV/0!');return x/y;}if(k==='^'){const v=x**y;if(!Number.isFinite(v))throw Error('#NUM!');return v;}}
   if(kind!=='f')throw Error('Unknown AST');const args=a[2];if(k==='IF')return ev(args[ev(args[0],s)?1:2]||['v',false],s);if(k==='IFERROR'){try{return ev(args[0],s);}catch{return ev(args[1],s);}}const v=args.map(a=>ev(a,s)),all=flat(v),ns=all.filter(num);switch(k){case 'AND':return all.every(Boolean);case 'OR':return all.some(Boolean);case 'NOT':return !v[0];case 'ISNUMBER':return num(v[0]);case 'COUNT':return ns.length;case 'COUNTA':return all.filter(x=>!blank(x)).length;case 'SUM':return ns.reduce((a,b)=>a+b,0);case 'PRODUCT':return ns.length?ns.reduce((a,b)=>a*b,1):0;case 'AVERAGE':if(!ns.length)throw Error('#DIV/0!');return ns.reduce((a,b)=>a+b,0)/ns.length;case 'MIN':return ns.length?Math.min(...ns):0;case 'MAX':return ns.length?Math.max(...ns):0;case 'ABS':return Math.abs(number(v[0]));case 'SQRT':if(number(v[0])<0)throw Error('#NUM!');return Math.sqrt(number(v[0]));case 'EXP':return Math.exp(number(v[0]));case 'LN':if(number(v[0])<=0)throw Error('#NUM!');return Math.log(number(v[0]));case 'TAN':return Math.tan(number(v[0]));case 'PI':return Math.PI;case 'MOD':if(!number(v[1]))throw Error('#DIV/0!');return number(v[0])-number(v[1])*Math.floor(number(v[0])/number(v[1]));case 'ROUNDUP':{const n=number(v[0]),p=10**number(v[1]);return Math.sign(n)*Math.ceil(Math.abs(n)*p)/p;}case 'ROUND':{const n=number(v[0]),p=10**number(v[1]);return Math.sign(n)*Math.round(Math.abs(n)*p+Number.EPSILON*Math.abs(n)*p)/p;}case 'TEXT':return format(number(v[0]),v[1]);case 'CHAR':return String.fromCharCode(number(v[0]));case 'HYPERLINK':return v[1]??v[0];case 'INDEX':{const ar=Array.isArray(v[0])?v[0]:[v[0]],ref=args[0][0]==='r'?args[0][1].split('!').pop():'',ends=ref.split(':'),cols=ends.length===2?coord(ends[1])[1]-coord(ends[0])[1]+1:1;return ar[(number(v[1])-1)*cols+(v.length>2?number(v[2])-1:0)]??null;}case 'SUMPRODUCT':{const arrays=v.map(x=>Array.isArray(x)?x:[x]);return arrays[0].reduce((sum,_,i)=>sum+arrays.reduce((p,a)=>p*(num(a[i])?a[i]:0),1),0);}case 'COUNTIFS':{const arrays=v.filter((_,i)=>i%2===0).map(a=>Array.isArray(a)?a:[a]);return arrays[0].filter((_,j)=>arrays.every((a,i)=>{const criterion=v[i*2+1];if(typeof criterion!=='string')return compare(a[j],criterion)===0;const m=criterion.match(/^(<=|>=|<>|=|<|>)(.*)$/);if(!m)return compare(a[j],criterion)===0;const rhs=m[2]!==''&&Number.isFinite(+m[2])?+m[2]:m[2],c=compare(a[j],rhs);return ({'<':c<0,'>':c>0,'<=':c<=0,'>=':c>=0,'=':c===0,'<>':c!==0})[m[1]];})).length;}default:throw Error('Unsupported formula '+k);}
  }
  function get(s,a){const key=s+'!'+a;if(own(over,key))return over[key];if(own(cache,key))return cache[key];if(busy.has(key))throw Error('Circular '+key);const c=D.sheets[s]?.cells[a];if(!c)return null;if(!c.ast)return c.value??null;busy.add(key);try{let v=ev(c.ast,s);if(blank(v))v=0;if(typeof v==='number'&&!Number.isFinite(v))throw Error('#NUM!');return cache[key]=v;}catch(e){errors[key]=e.message;throw e;}finally{busy.delete(key);}}
  function safe(s,a){try{return get(s,a);}catch(e){return e.message;}}
  return {get,safe,state,errors,format,source:D};
 }
 function calculate(x,face='B'){const error=validate(x,face);if(error)return {state:'INPUT REQUIRED: '+error,face};const m=machine(x,face),w=roles[1],u=roles[2],sl=roles[3],ot=roles[4],put=v=>num(v)?v:'NOT ASSESSED',r={8:m.get(u,'B6'),9:m.get(w,'K3'),10:m.get(w,'AZ132'),12:put(m.get(w,'K5')),13:num(m.get(w,'K5'))&&num(m.get(ot,'C22'))?m.get(w,'K5')*m.get(ot,'C22'):null,14:put(m.get(sl,'B59')),15:put(m.get(ot,'B43'))},criteria={14:put(m.get(sl,'B60')),15:put(m.get(ot,'B44'))};if(r[8]==='Yes'){if(num(m.get(u,'B17'))&&m.get(u,'B17')===0){r[16]='NO UPLIFT';r[22]=0;}else{r[16]=put(m.get(u,'B19'));criteria[16]=put(m.get(ot,'B17'));}}else{r[16]='N/A: no basement';r[22]='N/A';}for(const i of [14,15,16])if(num(r[i])&&num(criteria[i]))r[i+6]=r[i]>0?criteria[i]/r[i]:'NO RESISTANCE';let best=-1,missing=false,noResistance='';for(const [j,label]of ['Sliding','Overturning','Uplift'].entries()){const v=r[j+20];if(num(v)){if(v>best){best=v;r[24]=label;}}else if(v==='NO RESISTANCE')noResistance=label;else if(v!=='N/A')missing=true;}if(best>=0)r[23]=best;if(noResistance){r[23]='NO RESISTANCE';r[24]=noResistance;}r[25]=missing?'PARTIAL - see unassessed checks':'All listed applicable checks assessed';return {state:'CALCULATED',face,results:r,criteria,input:m.state};}
 function compareFaces(b,d){if(b?.state!=='CALCULATED'||d?.state!=='CALCULATED')return {25:'Calculate both faces with valid inputs first.'};const out={};for(const r of [12,13,20,21,22,23]){const x=b.results[r],y=d.results[r];if(x==='NO RESISTANCE'||y==='NO RESISTANCE')out[r]=x===y?'Both: no resistance':x==='NO RESISTANCE'&&num(y)?'B':y==='NO RESISTANCE'&&num(x)?'D':'Not comparable / not assessed';else if(num(x)&&num(y))out[r]=Math.abs(x-y)<1e-7?'Equal':x>y?'B':'D';else out[r]='Not comparable / not assessed';}for(const r of [14,15,16])out[r]=out[r+6];if(b.results[25].startsWith('PARTIAL')||d.results[25].startsWith('PARTIAL')){out[23]='No overall ranking: incomplete scope';out[25]='Compare completed checks individually.';}else out[25]='Governing face by maximum utilisation; wind review still applies.';return out;}
 return {defaults,normalize,validate,machine,calculate,compareFaces,format,num,inputs,roles,source:D,coord,letters};
})();
if(typeof module!=='undefined')module.exports=Overall;
