window.TrussUI109=(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:2}):'—';
 const groups={top:'上弦',bottom:'下弦',diagonal:'斜腹杆',vertical:'竖腹杆'};
 let stamp='',cached;
 function results(p,r){const key=JSON.stringify(p);if(stamp!==key){cached=Loading.run(p,r,'B');stamp=key;}return cached;}
 const field=(label,k,v,options)=>`<label>${label}${options?`<select data-tt-field="${k}">${options.map(([x,l])=>`<option value="${esc(x)}" ${String(x)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`:`<input data-tt-field="${k}" type="${k==='name'?'text':'number'}" step="any" value="${esc(v)}">`}</label>`;
 const check=(label,k,v)=>`<label class="wp-sub"><input type="checkbox" data-tt-field="${k}" ${v?'checked':''}> ${label}</label>`;
 function sketch(g,c){if(!g)return '';const span=g.span,depth=g.depth,scale=Math.min(670/span,240/depth),x=v=>65+v*scale,y=v=>310-v*scale,nodes=c?.nodes,members=c?.members;let out=`<svg viewBox="0 0 820 390" style="width:100%;max-height:420px" role="img" aria-label="桁架立面及上层柱荷载">`;
  if(nodes)for(const m of members){const a=nodes[m.i],b=nodes[m.j];out+=`<line x1="${x(a.x)}" y1="${y(a.y)}" x2="${x(b.x)}" y2="${y(b.y)}" stroke="${m.ok?'#137c87':'#bc442d'}" stroke-width="${['top','bottom'].includes(m.group)?4:2}"/><text x="${x((a.x+b.x)/2)+4}" y="${y((a.y+b.y)/2)-5}" font-size="11" fill="#345b65">${m.id}</text>`;}
  else out+=`<path d="M${x(0)} ${y(0)}H${x(span)}M${x(0)} ${y(depth)}H${x(span)}" stroke="#137c87" stroke-width="4"/>`;
  for(const s of g.sources){const l=c?.input.loads.find(l=>l.id===s.id);out+=`<path d="M${x(s.x)} ${y(depth)-42}v30l-5 -7m5 7l5 -7" fill="none" stroke="#c27837" stroke-width="2"/><text x="${x(s.x)+7}" y="${y(depth)-30}" font-size="11">${esc(s.id)}${l?' · G '+num(l.g)+' / Q '+num(l.q)+' kN':''}</text>`;}
  for(const [i,s]of [g.A,g.B].entries()){const xx=x(i?span:0);out+=`<path d="M${xx} 313l-10 16h20z" fill="none" stroke="#345b65" stroke-width="2"/>${i?`<circle cx="${xx-5}" cy="333" r="3" fill="none" stroke="#345b65"/><circle cx="${xx+5}" cy="333" r="3" fill="none" stroke="#345b65"/>`:``}<text x="${xx-12}" y="354" font-size="12">${esc(s.id)}</text>`;}
  out+=`<text x="65" y="377" font-size="13">L = ${num(span)} m · h = ${num(depth)} m · z 上 / 下 = ${num(g.zTop)} / ${num(g.zBottom)} m</text></svg>`;return out;
 }
 function render(p,r){const out=results(p,r),floors=r.floors.map(f=>[f.n,FloorLevels.name(p,f.n)]),items=TrussModel109.list(p);let html=`<div class="wp-head"><div><span class="wp-scheme">Scheme 1 · RC 柱转换 · S460 钢桁架</span><h1>水平转换桁架</h1><p>用于 RC 方案的柱转换，可替代 RC 转换梁 TB；无需建立 Scheme 2。单一 TT 构件，上下弦可相隔一层或两层。</p></div><div class="wp-row"><button data-tt="add" class="primary">＋ 新增桁架</button><button data-tt="excel">生成桁架 Excel</button></div></div>`;
  html+=`<div class="wp-card"><b>计算范围</b><p class="wp-sub">HK Steel Code 2011（2023 版及 2026-04 修订）· BS 热轧 UB / UC · S460 按厚度取 p<sub>y</sub>。平面铰接节点、杆件轴线交汇；新增节点混凝土只计自重。检查拉压轴力、两轴屈曲、长细比、平面内稳定筛查和 G+Q／Q 位移。连接、钢筋焊接及锚固、局部荷载弯矩、耐火与桁架整体抗扭不在本计算范围。钢材自重折算为节点荷载。</p><p class="wp-sub">承托柱选在下弦楼层的柱段；受托柱选在上弦楼层之上的柱段。特征 G/Q 自动读取柱的实际传荷，跨层反力直接送到下弦承托柱。位移限值是项目输入，没有预设为规范通用限值。</p></div>`;
  if(!items.length)html+='<div class="wp-empty">新增一个桁架，选定上下弦楼层、两根承托柱及受托柱。<br>已存在的 TB 可在桁架中选择替代。</div>';
  for(const t of items){const v=out.trusses.find(x=>x.id===t.id),g=v?.geometry,c=v?.calculation,lower=Engine.floorModel(r,t.bottomFloor),upper=Engine.floorModel(r,t.topFloor+1),here=Engine.floorModel(r,t.topFloor),columns=m=>[['','选择柱'],...(m?.columns||[]).map(c=>[c.id,c.id+' · ('+TrussModel109.pt(c).map(num).join(', ')+') m'])];
   html+=`<section class="wp-card" data-tt-id="${esc(t.id)}"><div class="wp-row wp-spread"><h2>${esc(t.name)} · ${t.enabled===false?'已停用':esc(v?.status||'INPUT REQUIRED')}</h2><button data-tt="remove">删除桁架</button></div><div class="wp-grid">${field('名称','name',t.name)}${field('下弦／承托柱楼层','bottomFloor',t.bottomFloor,floors.filter(x=>x[0]<p.total-1))}${field('上弦楼层','topFloor',t.topFloor,floors.filter(x=>x[0]>1&&x[0]<p.total))}${field('左端承托柱（平面起点）','supportA',t.supportA,columns(lower))}${field('右端承托柱（平面终点）','supportB',t.supportB,columns(lower))}${field('基础分格数（另加受托柱节点）','panels',t.panels)}${field('替代原 TB（可选）','replacement',t.replaces?.token||'',[['','独立桁架'],...(here?.beams||[]).filter(b=>b.kind==='TB').map(b=>[Loading.token('TB',b),b.displayId||b.id])])}</div><div class="wp-row">${check('启用传荷','enabled',t.enabled!==false)}${check('转换区无净高要求（跨两层时必选）','noHeadroom',t.noHeadroom)}</div>`;
   html+=`<h3>受托柱 · ${esc(FloorLevels.name(p,t.topFloor+1))} 柱段 → 上弦节点</h3><div class="wp-row">${(upper?.columns||[]).map(s=>`<label><input type="checkbox" data-tt-source="${esc(s.id)}" ${t.sourceIds.includes(s.id)?'checked':''}> ${esc(s.id)} (${TrussModel109.pt(s).map(num).join(', ')})</label>`).join('')||'该层没有柱'}</div>`;
   html+=`<details class="wp-detail" open><summary>截面、侧向支承及项目位移限值</summary><div class="wp-grid">${Object.entries(groups).map(([key,name])=>field(name+' · S460 热轧形钢','sections.'+key,t.sections?.[key]||'auto',[['auto','自动选型'],...TransferTruss109.catalog.sections.map(s=>[s.id,s.id])])).join('')}${['top','bottom'].map(key=>field(groups[key]+' 平面外无支承长度 m（空白=全跨）','restraints.'+key,t.restraints?.[key])).join('')}${field('G+Q 位移限值 mm','limits.total',t.limits?.total)}${field('Q 增量位移限值 mm','limits.live',t.limits?.live)}${field('受托柱差异位移限值 mm','limits.differential',t.limits?.differential)}</div>${check('已设置上下弦及腹杆节点的平面外侧向支承；上面填写的无支承长度与实际布置一致','bracingConfirmed',t.bracingConfirmed)}<p class="wp-sub">截面强轴置于桁架平面；平面内有效长度取杆件节点距。侧向支承的刚度、强度及节点构造另行落实。自动选型统一每组截面；Class 4 压杆不支持。</p></details>`;
   html+=`<details class="wp-detail"><summary>柱接驳区新增混凝土自重</summary><p class="wp-sub">仅填未包含在原柱／楼层恒载内的新增体积，避免重复计重；0 表示无新增自重。密度 24.5 kN/m³。</p><div class="wp-grid">${[['left','左承托柱'],['right','右承托柱'],...t.sourceIds.map(id=>[id,id+' 受托柱'])].map(([id,label])=>field(label+' · m³','jointVolumes.'+id,t.jointVolumes?.[id]??0)).join('')}</div></details>`;
   if(v?.fail.length)html+=`<div class="wp-alert">${v.fail.map(esc).join('<br>')}</div>`;html+=sketch(g,c);
   if(c){html+=`<p class="wp-sub">钢材 ${num(c.mass)} kg / ${num(c.steelWeight)} kN；节点混凝土 ${num(c.concreteWeight)} kN；选型 ${c.iterations} 轮。强度与位移均考虑独立 Q 的不利布置。</p><table class="wp-table"><tr><th>端部反力</th><th>G · kN</th><th>Q · kN</th><th>ULS 最大 · kN</th></tr>${[g.A,g.B].map((s,i)=>`<tr><td>${esc(s.id)}</td><td>${num(c.reactions.dead[i])}</td><td>${num(c.reactions.live[i])}</td><td>${num(c.reactions.uls[i].max)}</td></tr>`).join('')}</table><div class="wp-grid">${[['total','G+Q'],['live','Q 增量'],['differential','柱间差异']].map(([key,label])=>`<div>${label}位移：<b>${num(c.deflection[key])}</b> / ${num(t.limits?.[key])} mm</div>`).join('')}</div><div style="overflow:auto"><table class="wp-table"><tr><th>杆件</th><th>截面</th><th>压／拉 kN</th><th>p<sub>y</sub> MPa</th><th>λx / λy</th><th>Pc / Pt kN</th><th>利用率</th></tr>${c.members.map(m=>`<tr><td>${m.id}</td><td>${esc(m.section.id)}</td><td>${num(m.Nc)} / ${num(m.Nt)}</td><td>${m.capacity.py}</td><td>${num(m.capacity.lambdaX)} / ${num(m.capacity.lambdaY)}</td><td>${num(m.capacity.Pc)} / ${num(m.capacity.Pt)}</td><td class="${m.ok?'wp-ok':''}">${num(m.util*100)}% ${m.ok?'✓':'✕'}</td></tr>`).join('')}</table></div>`;}
   html+=`<div class="wp-row">${check('加入 A 抄','reportA',t.reportA!==false)}${check('加入 B 抄','reportB',t.reportB!==false)}</div></section>`;
  }
  return html;
 }
 function restore(p,t){if(!t.replaces)return;Loading.init(p);for(const [key,value]of Object.entries(t.previousSelections||{})){const [map,...rest]=key.split(':');(p.explorer[map]??={})[rest.join(':')]=value;}t.previousSelections={};}
 function capture(p,t){if(!t.replaces)return;Loading.init(p);t.previousSelections??={};for(const map of ['selected','reportA','reportB']){const key=t.replaces.floor+'|'+t.replaces.token;t.previousSelections[map+':'+key]=p.explorer[map]?.[key]??false;if(p.explorer[map])delete p.explorer[map][key];}}
 function references(p,r,t){t.references={};try{const g=TrussModel109.geometry(p,r,t);t.references={supportA:TrussModel109.pt(g.A),supportB:TrussModel109.pt(g.B),...Object.fromEntries(g.sources.map(s=>[s.id,TrussModel109.pt(s.c)]))};}catch{}}
 function click(e,host){const b=e.target.closest('[data-tt]');if(!b)return false;const {p}=host.get(),action=b.dataset.tt;if(action==='excel'){host.navigate('reportA');ExcelSync.generate('Truss');}else host.transact(()=>{p.transferTrusses??=[];if(action==='add'){if(p.total<3)throw Error('至少需要三个楼层编号，才能指定下弦、上弦及受托柱段');let n=1;while(p.transferTrusses.some(t=>t.id==='TT'+n))n++;const top=Math.max(2,Math.min(p.total-1,host.get().floor||2));p.transferTrusses.push({id:'TT'+n,name:'TT'+n,enabled:true,bottomFloor:top-1,topFloor:top,supportA:'',supportB:'',sourceIds:[],panels:4,sections:{},restraints:{},limits:{total:null,live:null,differential:null},jointVolumes:{left:0,right:0},reportA:true,reportB:true});}else if(action==='remove'){const id=b.closest('[data-tt-id]').dataset.ttId,t=p.transferTrusses.find(x=>x.id===id);restore(p,t);p.transferTrusses=p.transferTrusses.filter(x=>x.id!==id);}});return true;}
 function change(e,host){const node=e.target.closest('[data-tt-field],[data-tt-source]');if(!node)return false;const {p,result:r}=host.get(),id=node.closest('[data-tt-id]').dataset.ttId;host.transact(()=>{const t=p.transferTrusses.find(t=>t.id===id),key=node.dataset.ttField;let v=node.type==='checkbox'?node.checked:node.type==='number'||['bottomFloor','topFloor'].includes(key)?node.value===''?null:Number(node.value):node.value;
   if(node.dataset.ttSource){const id=node.dataset.ttSource;t.sourceIds=node.checked?[...new Set([...t.sourceIds,id])]:t.sourceIds.filter(x=>x!==id);t.jointVolumes[id]??=0;references(p,r,t);return;}
   if(key==='replacement'){restore(p,t);t.replaces=v?{floor:t.topFloor,token:v}:null;if(v)capture(p,t);return;}
   if(key==='enabled'){if(!v)restore(p,t);else capture(p,t);}
   const path=key.split('.');if(path.length===2)(t[path[0]]??={})[path[1]]=v;else t[key]=v;
   if(['bottomFloor','topFloor'].includes(key)){restore(p,t);t.replaces=null;t.sourceIds=[];t.supportA=t.supportB='';t.references={};if(key==='bottomFloor'&&(t.topFloor<=v||t.topFloor-v>2))t.topFloor=v+1;if(key==='topFloor'&&(t.bottomFloor>=v||v-t.bottomFloor>2))t.bottomFloor=v-1;}
   if(['supportA','supportB'].includes(key))references(p,r,t);
  });return true;}
 return {render,click,change,results,sketch};
})();
