const TrussModel109=(()=>{
 const list=p=>p.transferTrusses||[],active=p=>list(p).filter(t=>t.enabled!==false),token=t=>'TT|'+t.id;
 const pt=c=>[c.cx??c.x,c.cy??c.y],finite=x=>typeof x==='number'&&Number.isFinite(x),uniq=a=>[...new Set(a)];
 function validate(p){if(p.transferTrusses===undefined)return;if(!Array.isArray(p.transferTrusses)||p.transferTrusses.length>40)throw Error('Transfer Truss 最多 40 项');const ids=new Set();for(const t of p.transferTrusses){if(!t||typeof t.id!=='string'||!/^[A-Za-z0-9_-]{1,40}$/.test(t.id)||ids.has(t.id))throw Error('Transfer Truss 编号无效或重复');ids.add(t.id);if(typeof t.name!=='string'||t.name.length>80)throw Error('Transfer Truss 名称无效');if(!Number.isInteger(t.bottomFloor)||!Number.isInteger(t.topFloor)||t.bottomFloor<1||t.topFloor>=p.total||t.topFloor<=t.bottomFloor||t.topFloor-t.bottomFloor>2)throw Error('Transfer Truss 楼层无效：须在项目内相隔 1–2 层，且上方保留受托柱段；请先调整或删除桁架');if(!Array.isArray(t.sourceIds)||t.sourceIds.length>12||t.sourceIds.some(x=>typeof x!=='string'))throw Error('Transfer Truss 受托柱清单无效');}}
 function geometry(p,r,t){const errors=[],b=t.bottomFloor,f=t.topFloor;if(!Number.isInteger(b)||!Number.isInteger(f)||b<1||f>=p.total||f<=b||f-b>2)throw Error('上弦／下弦须相隔 1–2 层，且上弦上方须有受托柱楼层');if(f-b===2&&!t.noHeadroom)errors.push('跨两层布置须确认转换区无净高要求');
  const lower=Engine.floorModel(r,b),upper=Engine.floorModel(r,f+1),find=(m,id)=>{const all=m.columns.filter(c=>c.id===id);if(all.length!==1)throw Error('所选柱不存在或编号不唯一：'+(id||'未选择'));return all[0];},A=find(lower,t.supportA),B=find(lower,t.supportB);if(A.id===B.id)throw Error('须选择两根不同的承托柱');
  const a=pt(A),z=pt(B),span=Math.hypot(z[0]-a[0],z[1]-a[1]);if(span<.3)throw Error('承托柱中心距小于 0.3 m');const ux=(z[0]-a[0])/span,uy=(z[1]-a[1])/span;
  if(!t.sourceIds.length)throw Error('请选择上弦上方的受托柱');if(uniq(t.sourceIds).length!==t.sourceIds.length)throw Error('受托柱重复');const sources=t.sourceIds.map(id=>{const c=find(upper,id),q=pt(c),x=(q[0]-a[0])*ux+(q[1]-a[1])*uy,offset=Math.abs((q[0]-a[0])*uy-(q[1]-a[1])*ux);if(offset>.001||x<-.001||x>span+.001)errors.push(id+' 柱中心不在桁架平面或跨度内（容差 1 mm）');return {id,c,x:Math.max(0,Math.min(span,x))};});
  const levels=LocalHeights96.levels(p),elevation=(f,q)=>LocalHeights96.levelAt(p,f,...q,levels),zb=elevation(b,a),zt=elevation(f,a);if(Math.abs(elevation(b,z)-zb)>.001||[z,...sources.map(s=>pt(s.c))].some(q=>Math.abs(elevation(f,q)-zt)>.001))errors.push('各上弦或下弦节点标高不一致；本版只支持水平平行弦');if(!(zt>zb))errors.push('上弦标高须高于下弦');
  if(t.replaces){if(t.replaces.floor!==f)errors.push('被替代 TB 须在上弦楼层');const beams=Engine.floorModel(r,f).beams.filter(c=>c.kind==='TB'&&Loading.token('TB',c)===t.replaces.token);if(beams.length!==1)errors.push('被替代 TB 已删除或几何已改变');else{const ba=beams[0].rawA||beams[0].a,bz=beams[0].rawZ||beams[0].z,close=(q,v)=>Math.hypot(q[0]-v[0],q[1]-v[1])<=.001;if(!(close(ba,a)&&close(bz,z)||close(ba,z)&&close(bz,a)))errors.push('被替代 TB 两端须与所选承托柱中心对齐');}}
  const saved=t.references;if(saved){for(const [key,c]of [['supportA',A],['supportB',B],...sources.map(s=>[s.id,s.c])])if(saved[key]&&Math.hypot(...pt(c).map((v,i)=>v-saved[key][i]))>.001)errors.push(key+' 柱坐标已变化，请重新选择该柱以确认');}
  return {t,A,B,a,z,span,depth:zt-zb,zBottom:zb,zTop:zt,sources,errors};
 }
 function replacement(p,f,c){return active(p).find(t=>t.replaces?.floor===f&&t.replaces.token===Loading.token(c.kind,c));}
 function manager(p,r){const states=active(p).map(t=>{try{const g=geometry(p,r,t);return {t,g,errors:[...g.errors],loads:[],extra:[]};}catch(e){return {t,errors:[e.message],loads:[],extra:[]};}}),pending=new Map(),results=[];
  const claims=new Map();for(const s of states)for(const id of s.t.sourceIds){const key=s.t.topFloor+'|'+id;if(!claims.has(key))claims.set(key,[]);claims.get(key).push(s);}for(const [key,a]of claims)if(a.length>1)for(const s of a)s.errors.push('同一受托柱被多个桁架指定：'+key);
  const reps=new Map();for(const s of states)if(s.t.replaces){const key=s.t.replaces.floor+'|'+s.t.replaces.token;if(reps.has(key)){s.errors.push('同一 TB 被多次替代');reps.get(key).errors.push('同一 TB 被多次替代');}else reps.set(key,s);}
  function consume(f,above){const kept=[];for(const up of above){const owners=claims.get(f+'|'+up.member.id);if(!owners){kept.push(up);continue;}for(const s of owners){const source=s.g?.sources.find(c=>c.id===up.member.id);s.loads.push({id:up.member.id,x:source?.x??0,g:up.g,q:up.q});s.errors.push(...up.errors);if(up.truss109?.length)s.extra.push(...up.truss109);}}return kept;}
  function replaced(f,beam){return reps.get(f+'|'+beam.token);}
  function rejectDirect(state,beam,input){if(beam.lines.length||beam.points.length||beam.csMoments.length||beam.cbMoments.length||input.mode==='manual'||input.extraDead||input.points?.length||input.beamLoads?.length)state.errors.push('原 TB 仍有板、梁、墙或手动荷载；柱到柱桁架不能接收，请先另设支承路径并清除原 TB 荷载');state.errors.push(...beam.errors.filter(e=>!beam.supportErrors.includes(e)));}
  function solveFloor(f){for(const s of states.filter(x=>x.t.topFloor===f)){const {t,g}=s;for(const id of t.sourceIds)if(!s.loads.some(l=>l.id===id))s.errors.push('未取得受托柱 '+id+' 的 G/Q');let calc=null;try{if(g&&!s.errors.length)calc=TransferTruss109.design({span:g.span,depth:g.depth,loads:s.loads,panels:t.panels,sections:t.sections,restraints:t.restraints,limits:t.limits,jointVolumes:t.jointVolumes,bracingConfirmed:t.bracingConfirmed});}catch(e){s.errors.push(e.message);}
    const entry={id:t.id,name:t.name,t,geometry:g,calculation:calc,status:s.errors.length?'INPUT REQUIRED':calc?.status||'INPUT REQUIRED',fail:uniq([...s.errors,...calc?.fail||[]])};results.push(entry);
    const error=entry.status==='OK'?null:t.name+'：'+entry.fail.join('；');if(!pending.has(t.bottomFloor))pending.set(t.bottomFloor,[]);for(let i=0;i<2;i++)pending.get(t.bottomFloor).push({id:i?t.supportB:t.supportA,g:calc?.reactions.dead[i]??0,q:calc?.reactions.live[i]??0,errors:error?[error]:[],truss109:uniq([t.name,...s.extra])});
   }}
  function receive(f,columns){for(const a of pending.get(f)||[]){const dest=columns.filter(c=>c.member.id===a.id);if(dest.length===1){const c=dest[0];c.g+=a.g;c.q+=a.q;c.errors.push(...a.errors);c.truss109=uniq([...(c.truss109||[]),...a.truss109]);}else{const item=results.find(x=>x.name===a.truss109[0]);if(item){item.status='INPUT REQUIRED';item.fail.push('下层承托柱已不存在：'+a.id);}}}}
  return {consume,replaced,rejectDirect,solveFloor,receive,results,states};
 }
 // Use the physical G/Q on every downstream column touched by a TT. The
 // original spreadsheet's area multiplier is 1 only as a load-table adapter.
 function columnSchedule(p,r){const cfg=Loading.settings(p),dead=r.loading.dead,live=r.loading.live,errors=[...r.result?.fail||[]].filter(x=>r.result.status==='INPUT REQUIRED'),sum=1.4*dead+1.6*live,N=sum*cfg.columnProject,rho=cfg.columnRatio/100,b=Math.ceil(Math.sqrt(N*1000/(.35*cfg.columnFcu*(1-rho)+.67*500*rho))/100)*100,Ag=b*b,As=Ag*rho,Ac=Ag-As,capacity=(.35*cfg.columnFcu*Ac+.67*500*As)/1000;
  if(![dead,live,N,capacity].every(finite)||dead<0||live<0||N<=0)errors.push('桁架反力及柱累计荷载无效');
  return {physicalTruss:true,rows:[{lo:r.floor,hi:r.floor,usage:'TT physical G/Q (kN); multiplier 1',dl:dead,sdl:0,ll:live,area:1,count:1,areaName:'Reaction input, not tributary area',automatic:false}],errors,cells:{B4:r.id,B5:b,B6:b,B7:cfg.columnFcu,B8:500,B9:cfg.columnRatio,B10:cfg.columnProject,B11:1.4,B12:1.6,J36:sum,E38:N,E4:Ag,E5:As,E6:Ac,E39:capacity,E41:N<=capacity?'OKAY':'NOT OKAY'}};
 }
 function visuals(p,r,lo=1,hi=p.total){const out=[];for(const t of active(p).filter(t=>t.topFloor>=lo&&t.bottomFloor<=hi))try{const g=geometry(p,r,t);if(g.errors.length)continue;const mesh=TransferTruss109.mesh({span:g.span,depth:g.depth,panels:t.panels,loads:g.sources.map(s=>({id:s.id,x:s.x,g:0,q:0}))}),nodes=mesh.nodes.map(n=>[g.a[0]+n.x/g.span*(g.z[0]-g.a[0]),g.a[1]+n.x/g.span*(g.z[1]-g.a[1]),g.zBottom+n.y]);out.push({t,g,mesh,nodes});}catch{}return out;}
 function plan(ctx,p,r,f,xy){for(const {t,g} of visuals(p,r,f,f)){const a=xy(...g.a),b=xy(...g.z);ctx.save();ctx.strokeStyle='#127c8a';ctx.fillStyle='#127c8a';ctx.lineWidth=4;ctx.setLineDash([10,4]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();ctx.setLineDash([]);ctx.font='bold 12px Segoe UI';ctx.fillText(t.name+' · TT · '+FloorLevels.name(p,t.bottomFloor)+'–'+FloorLevels.name(p,t.topFloor),(a[0]+b[0])/2+7,(a[1]+b[1])/2-10);ctx.restore();}}
 function space(ctx,p,r,project,lo,hi,bottom,top){for(const v of visuals(p,r,lo,hi)){ctx.save();ctx.strokeStyle='#127c8a';ctx.lineWidth=2.3;for(const m of v.mesh.members){let a=[...v.nodes[m.i]],b=[...v.nodes[m.j]];if(Math.max(a[2],b[2])<bottom||Math.min(a[2],b[2])>top)continue;const dz=b[2]-a[2],mix=t=>a.map((x,i)=>x+t*(b[i]-x));if(Math.abs(dz)>1e-8){let l=Math.max(0,Math.min((bottom-a[2])/dz,(top-a[2])/dz)),h=Math.min(1,Math.max((bottom-a[2])/dz,(top-a[2])/dz));if(l>h)continue;const aa=mix(l),bb=mix(h);a=aa;b=bb;}ctx.beginPath();ctx.moveTo(...project(...a).slice(0,2));ctx.lineTo(...project(...b).slice(0,2));ctx.stroke();}const mid=project((v.g.a[0]+v.g.z[0])/2,(v.g.a[1]+v.g.z[1])/2,Math.min(top,v.g.zTop));ctx.font='bold 12px Segoe UI';ctx.fillStyle='#127c8a';ctx.fillText(v.t.name,mid[0]+5,mid[1]-8);ctx.restore();}}
 return {list,active,token,validate,geometry,replacement,manager,columnSchedule,plan,space,visuals,pt};
})();
if(typeof module!=='undefined')module.exports=TrussModel109;
