const TrussReports109=(()=>{
 const n=v=>Number.isFinite(v)?v.toFixed(2):'—',text=s=>({text:s}),groups={top:'Top chord',bottom:'Bottom chord',diagonal:'Diagonal',vertical:'Vertical'};
 function pages(p,entry,section){const {geometry:g,calculation:c,t}=entry,name=t.name+' · Section '+section+' · S460 transfer truss',shape=[],scale=Math.min(420/g.span,155/g.depth),x=v=>40+v*scale,y=v=>205-v*scale;
  for(const m of c.members){const a=c.nodes[m.i],b=c.nodes[m.j];shape.push({type:'line',x:x(a.x),y:y(a.y),x2:x(b.x),y2:y(b.y),width:['top','bottom'].includes(m.group)?2.5:1.2,color:'#0057b8'},{type:'text',x:x((a.x+b.x)/2)+3,y:y((a.y+b.y)/2)-12,text:m.id,size:8});}
  for(const s of g.sources)shape.push({type:'line',x:x(s.x),y:y(g.depth)-32,x2:x(s.x),y2:y(g.depth),arrow:true,color:'#0057b8'},{type:'text',x:x(s.x)+3,y:y(g.depth)-32,text:s.id,size:9});
  shape.push({type:'text',x:35,y:225,text:g.A.id+' (pin) → '+g.B.id+' (vertical roller); L = '+n(g.span)+' m; h = '+n(g.depth)+' m',size:10});
  const scope='Planar concentric pin-jointed axial model; BS hot-rolled UB/UC; steel alone. Joint concrete adds weight only. No weld / rebar anchorage / connection / fire / whole-truss torsion design. Member SW lumped at nodes; local bending requires separate review.';
  const first={title:name,section,order:45,lines:[text('HK Steel Code 2011 (2023 edition), April 2026 amendments. '+c.status+' within stated scope.'),text('Bottom '+FloorLevels.name(p,t.bottomFloor)+' z='+n(g.zBottom)+' m; top '+FloorLevels.name(p,t.topFloor)+' z='+n(g.zTop)+' m. Upper column segment: '+FloorLevels.name(p,t.topFloor+1)+'.'),text('E = 205,000 N/mm²; S460 py = 460 / 440 / 430 / 410 / 400 MPa for t ≤ 16 / 40 / 63 / 80 / 100 mm (Table 3.2).'),text(scope)],shapes:shape,shapeHeight:250,after:[text('Characteristic reactions: '+g.A.id+' G='+n(c.reactions.dead[0])+', Q='+n(c.reactions.live[0])+' kN; '+g.B.id+' G='+n(c.reactions.dead[1])+', Q='+n(c.reactions.live[1])+' kN.'),text('Steel SW = '+n(c.steelWeight)+' kN; additional joint concrete = '+n(c.concreteWeight)+' kN. Reactions bypass intermediate floors; lower columns use accumulated physical G/Q.'),text('Deflection envelopes G+Q / Q / differential = '+n(c.deflection.total)+' / '+n(c.deflection.live)+' / '+n(c.deflection.differential)+' mm; project limits = '+t.limits.total+' / '+t.limits.live+' / '+t.limits.differential+' mm.'),text('In-plane stiffness remains positive with 10× compression envelope: '+(c.stable?'YES':'NO')+'. Out-of-plane lateral restraint assumption: '+(t.bracingConfirmed?'confirmed in model':'UNCONFIRMED')+'.')]};
  const loads={title:name+' · Loads & method',section,order:45,lines:[text('Separate characteristic G and Q; no reuse of already-factored column design load.'),text('ULS envelope: each G uses adverse 1.4 / beneficial 1.0; each independent Q uses adverse 1.6 / beneficial 0 (Table 4.2). Each member has its own governing arrangement.'),text('Solve K u = P with EA/L bar stiffness. N = EA/L × axial displacement. Both chord levels and web axial deformation are included.'),text('Pt = Ag py (8.6.1, no holes assumed). Pc = Ag min(pcx,pcy) (8.7, Appendix 8.4). ε=√(275/py); conservative flange B/(2tf)≤13ε; web d/tw≤40ε. Class 4 compression excluded.'),text('pc = py pE / [φ + √(φ² − py pE)]; pE=π²E/λ²; φ=[py+(1+η)pE]/2; η=max[0,α(λ−λ0)/1000]; λ0=0.2π√(E/py).'),text('Rolled UB curves x/y: a/b (tf≤40), b/c (>40). UC: b/c, c/d. αa=2, αb=3.5, αc=5.5, αd=8. λc≤200; λt≤300. No built-up welded-section py reduction applied.')],table:[['Source / position','G / Q (kN)','Additional joint volume (m³)'],...c.input.loads.map(l=>[l.id+' @ '+n(l.x)+' m',n(l.g)+' / '+n(l.q),n(t.jointVolumes?.[l.id]??0)]),['Support joints','24.5 kN/m³ × volume',n(t.jointVolumes?.left??0)+' / '+n(t.jointVolumes?.right??0)]],after:[text('Equilibrium residuals: ΣV = '+c.forceResidual.toExponential(2)+' kN; ΣM = '+c.momentResidual.toExponential(2)+' kNm.'),...c.fail.map(s=>text('NOT OK: '+s))]};
  const selected=section==='A'?Object.keys(groups).map(g=>c.members.filter(m=>m.group===g).reduce((a,b)=>a.util>=b.util?a:b)):c.members,detail=[];
  for(let i=0;i<selected.length;i+=8)detail.push({title:name+' · '+(section==='A'?'Governing members':'Member checks')+' '+(i/8+1),section,order:45,lines:[text('Axial member utilisation = max(Nc/Pc, Nt/Pt). Effective lengths: in-plane = node spacing; out-of-plane = chord restraint spacing or full web length.'),text('Top / bottom out-of-plane length = '+n(t.restraints?.top||g.span)+' / '+n(t.restraints?.bottom||g.span)+' m. Strong axis is in the truss plane.')],table:[['Member / section','Actions / resistance (kN)','Slenderness / check'],...selected.slice(i,i+8).map(m=>[m.id+' · '+groups[m.group]+'\n'+m.section.id+'\nL='+n(m.L)+' m; py='+m.capacity.py,n(m.Nc)+' / '+n(m.capacity.Pc)+' compression\n'+n(m.Nt)+' / '+n(m.capacity.Pt)+' tension','λx/y '+n(m.capacity.lambdaX)+' / '+n(m.capacity.lambdaY)+'\ncurves '+m.capacity.curves.join('/')+'; '+n(100*m.util)+'%\n'+(m.ok?'OK':m.fail.join('; '))])],after:[text('Geometry: British Steel UB datasheet 19-07-2024 / UC datasheet 10-07-2023, BS EN 10365. S460 grade is a design assumption; supplier availability is not inferred.')]});
  return [first,loads,...detail];
 }
 const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
 function workbook(p,entry,sec){const c=entry.calculation,t=entry.t,sheets={},expected={};function sheet(name){const s={cells:{},formulas:{}};sheets[name]=s;expected[name]={};return s;}function row(s,r,values){values.forEach((v,i)=>s.cells[col(i)+r]=v);}function f(s,cell,formula,value){s.formulas[cell]=formula;if(value!==undefined){const name=Object.keys(sheets).find(k=>sheets[k]===s);expected[name][cell]=value;}}
  const cover=sheet('Read me');row(cover,1,[t.name+' · Transfer truss · E2.109']);const notes=['S460 BS hot-rolled UB/UC; HK Steel 2011 (2023) + April 2026 amendments.','This workbook is a calculation snapshot. Return to the app to change loads, geometry or sections.','Excel recalculates bar forces from exported nodal displacements and EA/L, nodal equilibrium, load envelopes and member capacities.','The stiffness solution, section search and 10x compression stability screening are performed in the app. Excel does not repeat the stiffness solve.','Each characteristic load case has its own sheet. H/I equilibrium residuals must be zero. J/K are support reactions.','Columns/beam/slab characteristic loads are from the selected project load path. All dimensions m except section properties in mm.','Local bending due to member weight is excluded by nodal lumping. Connection, anchorage, fire and whole-truss torsion checks are outside scope.','Joint concrete is weight only. Volumes are additional to the existing model loads.','G+Q / live / differential project limits (mm): '+[t.limits.total,t.limits.live,t.limits.differential].join(' / '),'App result: '+c.status,...c.fail];notes.forEach((v,i)=>row(cover,i+3,[v]));
  const members=sheet('Members'),headers=['Member','Group','Section','A mm2','Mass kg/m','tf mm','tw mm','B mm','d mm','L m','cx','cy','rx mm','ry mm','py MPa','Lx m','Ly m','lambda x','lambda y','alpha x','alpha y','pE x','eta x','phi x','pc x','pE y','eta y','phi y','pc y','Pt kN','Pc kN','Non-slender','Nc kN','Nt kN','Utilisation','Steel SW kN'];row(members,1,[t.name+' | Member checks']);row(members,5,headers);
  c.members.forEach((m,i)=>{const r=i+6,s=m.section,q=m.capacity;row(members,r,[m.id,m.group,s.id,s.A,s.mass,s.tf,s.tw,s.B,s.d,m.L,m.c,m.s,s.rx,s.ry,null,q.lx,q.ly,null,null,{a:2,b:3.5,c:5.5,d:8}[q.curves[0]],{a:2,b:3.5,c:5.5,d:8}[q.curves[1]]]);
   f(members,'O'+r,`=IF(MAX(F${r},G${r})<=16,460,IF(MAX(F${r},G${r})<=40,440,IF(MAX(F${r},G${r})<=63,430,IF(MAX(F${r},G${r})<=80,410,400))))`,q.py);
   f(members,'R'+r,`=P${r}*1000/M${r}`,q.lambdaX);f(members,'S'+r,`=Q${r}*1000/N${r}`,q.lambdaY);
   for(const [l,a,pe,eta,phi,pc,answer]of [['R','T','V','W','X','Y',q.pcX],['S','U','Z','AA','AB','AC',q.pcY]]){f(members,pe+r,`=PI()^2*205000/${l}${r}^2`);f(members,eta+r,`=MAX(0,${a}${r}*(${l}${r}-0.2*PI()*SQRT(205000/O${r}))/1000)`);f(members,phi+r,`=(O${r}+(1+${eta}${r})*${pe}${r})/2`);f(members,pc+r,`=MIN(O${r},O${r}*${pe}${r}/(${phi}${r}+SQRT(MAX(0,${phi}${r}^2-O${r}*${pe}${r}))))`,answer);}
   f(members,'AD'+r,`=D${r}*O${r}/1000`,q.Pt);f(members,'AE'+r,`=D${r}*MIN(Y${r},AC${r})/1000`,q.Pc);f(members,'AF'+r,`=IF(AND(H${r}/(2*F${r})<=13*SQRT(275/O${r}),I${r}/G${r}<=40*SQRT(275/O${r})),1,0)`,q.nonSlender?1:0);f(members,'AJ'+r,`=E${r}*J${r}*9.80665/1000`,m.weight);
  });
  c.cases.forEach((a,k)=>{const name='Case'+String(k+1).padStart(2,'0'),s=sheet(name);row(s,1,[a.id,a.kind]);row(s,4,['Node','x m','y m','Px kN','Py kN','ux m','uy m','Fx residual','Fy residual','Rx kN','Ry kN','Member','N kN (+tension)']);c.nodes.forEach((node,i)=>{const r=i+5,rx=c.fixed.indexOf(2*i),ry=c.fixed.indexOf(2*i+1);row(s,r,[node.id,node.x,node.y,a.P[2*i],a.P[2*i+1],a.U[2*i],a.U[2*i+1],null,null,rx<0?0:a.R[rx],ry<0?0:a.R[ry]]);for(const [axis,cell,P,R]of [[0,'H','D','J'],[1,'I','E','K']]){const terms=c.members.flatMap((m,j)=>m.i===i||m.j===i?[`${m.i===i?-1:1}*Members!${axis?'L':'K'}${j+6}*$M$${j+5}`]:[]);f(s,cell+r,`=${terms.join('+')||0}-${P}${r}-${R}${r}`,0);}});c.members.forEach((m,i)=>{const r=i+5,mr=i+6;s.cells['L'+r]=m.id;f(s,'M'+r,`=205000*Members!D${mr}/1000/Members!J${mr}*(Members!K${mr}*(F${m.j+5}-F${m.i+5})+Members!L${mr}*(G${m.j+5}-G${m.i+5}))`,a.N[i]);});});
  c.members.forEach((m,i)=>{const r=i+6,terms=maximum=>c.cases.map((a,k)=>{const ref=`Case${String(k+1).padStart(2,'0')}!M${i+5}`,lo=a.kind==='G'?1:0,hi=a.kind==='G'?1.4:1.6;return `IF(${ref}${maximum?'>':'<'}0,${hi},${lo})*${ref}`;}).join('+');f(members,'AG'+r,`=MAX(0,-(${terms(false)}))`,m.Nc);f(members,'AH'+r,`=MAX(0,${terms(true)})`,m.Nt);f(members,'AI'+r,`=MAX(AG${r}/AE${r},AH${r}/AD${r})`,m.util);});
  const def=sheet('Deflection');row(def,1,['SLS displacement envelopes · mm']);row(def,4,['Node / pair','G','Q min','Q max','G+Q envelope','Q envelope']);let dr=5;function displacement(label,node1,node2,expectedTotal,expectedLive){const r=dr++;def.cells['A'+r]=label;const term=(a,k)=>`(Case${String(k+1).padStart(2,'0')}!G${node1+5}${node2===undefined?'':'-Case'+String(k+1).padStart(2,'0')+'!G'+(node2+5)})*1000`,cases=c.cases.map((a,k)=>({kind:a.kind,v:term(a,k)}));f(def,'B'+r,'='+cases.filter(x=>x.kind==='G').map(x=>x.v).join('+'));f(def,'C'+r,'='+cases.filter(x=>x.kind==='Q').map(x=>'MIN(0,'+x.v+')').join('+'));f(def,'D'+r,'='+cases.filter(x=>x.kind==='Q').map(x=>'MAX(0,'+x.v+')').join('+'));f(def,'E'+r,`=MAX(ABS(B${r}+C${r}),ABS(B${r}+D${r}))`,expectedTotal);f(def,'F'+r,`=MAX(ABS(C${r}),ABS(D${r}))`,expectedLive);}
  c.nodes.forEach((node,i)=>displacement(node.id,i,undefined,c.slsEnvelopes[i].total,c.slsEnvelopes[i].live));
  for(let i=0;i<c.loadNodes.length;i++)for(let j=0;j<i;j++)displacement(c.input.loads[i].id+' - '+c.input.loads[j].id,c.loadNodes[i],c.loadNodes[j]);
  const summary=sheet('Summary');row(summary,1,[t.name+' · '+c.status]);row(summary,4,['Quantity','Excel','App']);const quantities=[['Steel self-weight kN',`=SUM(Members!AJ6:AJ${c.members.length+5})`,c.steelWeight],['Max member utilisation',`=MAX(Members!AI6:AI${c.members.length+5})`,Math.max(...c.members.map(m=>m.util))],['Total displacement envelope mm',`=MAX(Deflection!E5:E${c.nodes.length+4})`,c.deflection.total],['Live displacement envelope mm',`=MAX(Deflection!F5:F${c.nodes.length+4})`,c.deflection.live],['Differential displacement mm',dr>c.nodes.length+5?`=MAX(Deflection!E${c.nodes.length+5}:E${dr-1})`:'=0',c.deflection.differential]];quantities.forEach(([label,formula,value],i)=>{row(summary,i+5,[label,null,value]);f(summary,'B'+(i+5),formula,value);});
  return {type:'Truss',method:'PLANAR_AXIAL_109',section:sec,label:t.name+' · S460 Transfer Truss',sheets,expected,reportPages:pages(p,entry,sec),calculationStatus:c.status};
 }
 function jobs(p,r,section,report){const out=Loading.run(p,r,section==='A'?'A':'B'),batches=[],issues=[];for(const entry of out.trusses){if(report&&entry.t['report'+section]===false)continue;try{if(!entry.calculation||!['total','live','differential'].every(k=>Number.isFinite(entry.t.limits?.[k])&&entry.t.limits[k]>0))throw Error(entry.fail.join('；')||'输入未完整');batches.push(workbook(p,entry,section||'B'));}catch(e){issues.push({id:entry.name,reason:e.message});}}return {batches,issues};}
 return {pages,workbook,jobs};
})();
