window.WorkspacePages=(()=>{
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=x=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString('en-US',{maximumFractionDigits:2}):'—';
 let host,root,current='',lastHTML='',reportUrls={},refreshTimer,pdfModule,pdfObserver,pdfDocument,pdfCleanup,paintGeneration=0;
 const button=(action,text,extra='')=>`<button data-wp="${action}" ${extra}>${text}</button>`;
 function init(h){host=h;root=document.createElement('div');root.id='workspace-pages';document.querySelector('.stage').append(root);
  const style=document.createElement('style');style.textContent=`
  .layout[data-full="true"]{grid-template-columns:var(--nav-width,200px) 6px minmax(0,1fr)!important}
  .layout[data-full="true"]>.side,.layout[data-full="true"]>#side-divider{display:none!important}
  .layout[data-full="true"] .stage{grid-column:3;min-width:0;overflow:hidden;display:block}
  .layout[data-full="true"] .stage>:not(#workspace-pages){display:none!important}
  #workspace-pages{display:none;height:100%;overflow:auto;background:#f3f7f8;padding:24px 30px;color:#284653}
  .layout[data-full="true"] #workspace-pages{display:block}
  .wp-head{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center;gap:18px;margin-bottom:22px}.wp-head h1{font-size:24px;margin:0 0 6px}.wp-head p{margin:0;color:#71858d}
  .wp-card{padding:22px;background:white;border:1px solid #dce6e9;border-radius:12px;margin:16px 0;min-width:0}.wp-card h2{margin:0;font-size:19px}
  .wp-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(185px,1fr));gap:14px;margin:16px 0}.wp-grid label{display:flex;flex-direction:column;gap:7px;font-size:13px;color:#526d79}.wp-grid input,.wp-grid select{width:100%;min-width:0;padding:9px;border:1px solid #cbdbe2;border-radius:6px;color:#284653;background:#fffdf3}
  #workspace-pages button{padding:9px 14px;border-radius:7px;cursor:pointer;border:1px solid #cbdbe2;background:white;color:#236679}#workspace-pages button.primary{background:#196a7d;color:white;border-color:#196a7d}#workspace-pages button:disabled{opacity:.5;cursor:default}
  .wp-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.wp-spread{justify-content:space-between}.wp-sub{color:#738894;font-size:13px;line-height:1.7}.wp-alert{padding:12px 16px;background:#fff7e9;color:#916124;border-radius:8px;margin:12px 0}.wp-ok{color:#26785c}.wp-status{font-size:13px}.wp-table{width:100%;border-collapse:collapse;margin:14px 0;font-size:14px}.wp-table th,.wp-table td{text-align:left;padding:11px;border-bottom:1px solid #e3ebee}.wp-table th{background:#f2f7f9}.wp-empty{padding:60px 20px;text-align:center;color:#718590}
  .wp-report{min-height:550px;padding:20px;background:#e3e9ec;border-radius:8px}.wp-report canvas{display:block;width:100%;max-width:850px;aspect-ratio:210/297;margin:0 auto 24px;background:white;box-shadow:0 2px 8px #20394625}.wp-scheme{display:inline-flex;font-size:12px;border-radius:20px;background:#e6f2f4;color:#236779;padding:4px 10px;margin-bottom:8px}.wp-bay{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:20px}.wp-sketch{background:#f5f9fa;border-radius:10px;min-height:200px;padding:12px}.wp-detail summary{cursor:pointer;color:#6e8490;margin:10px 0}.wp-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}.wp-cards .wp-card{margin:0}#nav .scheme-label{font-size:11px;padding:14px 12px 4px;color:#7e929a;letter-spacing:.05em}#nav button{white-space:normal}
  @media(max-width:1100px){.wp-bay{grid-template-columns:1fr}.wp-sketch{display:none}#workspace-pages{padding:18px}.layout[data-full="true"]{grid-template-columns:var(--nav-width,180px) 6px minmax(0,1fr)!important}}
  `;document.head.append(style);root.addEventListener('click',click);root.addEventListener('change',change);
 }
 function field(label,key,value,type='number',opts=null){const attr=`data-field="${key}"`;return `<label>${label}${opts?`<select ${attr}>${opts.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select>`:`<input ${attr} type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}">`}</label>`;}
 function floors(p){return Array.from({length:p.total},(_,i)=>[i+1,FloorLevels.name(p,i+1)]);}
 function rectangle(r){return ['x0','x1','y0','y1'].map(k=>field(k.toUpperCase()+' · m','rect.'+k,r[k])).join('');}
 function rectFields(p,result,item){if(!item.axisRefs)return rectangle(item.rect);const key=result.floors[(item.floor??item.from)-1]?.type;if(!key)return '楼层不存在';return ['x0','x1','y0','y1'].map(k=>field(k.toUpperCase()+' 轴线','axis.'+k,item.axisRefs[k],'text',[['','选择轴线'],...Engine.axes(p,k[0],key).map(a=>[a.id,a.id+' · '+num(a.v)+' m'])])).join('');}
 function sketch(b){const vertical=b.angle===90,count=Math.min(b.n||0,24),lines=Array.from({length:count},(_,i)=>{const pos=40+180*(i+1)/(count+1);return vertical?`<path d="M${pos} 45v150"/>`:`<path d="M40 ${45+150*(i+1)/(count+1)}h180"/>`;}).join('');return `<svg viewBox="0 0 260 250" aria-label="Scheme 2 钢梁布置示意"><rect x="40" y="45" width="180" height="150" fill="#e9f3f5" stroke="#2d6880" stroke-width="4"/><g stroke="#479883" stroke-width="2">${lines}</g><g fill="#476d7b" font-size="12" text-anchor="middle"><text x="130" y="27">X1 ${num(b.rect.x1-b.rect.x0)} m</text><text x="130" y="222">Y ${num(b.rect.y1-b.rect.y0)} m · n = ${esc(b.n)}</text><text x="130" y="242">${b.n>24?'示意图疏绘；计算包含全部次梁':'横向／纵向等间距布置'}</text></g></svg>`;}
 function steel(p,result){const s=p.scheme2||{},list=s.bays||[],cols=s.columns||[],set=Steel.settings(p);
  let html=`<div class="wp-head"><div><span class="wp-scheme">Scheme 2 · Steel</span><h1>组合梁与组合柱</h1><p>共用轴线、楼层、区域和 Loading；构件独立于 Scheme 1。</p></div><div class="wp-row">${button('add-bay','＋ 钢梁区域','class="primary"')}${button('add-column','＋ 组合柱')}</div></div>`;
  html+=`<details class="wp-card wp-detail"><summary>计算参数 · 沿用 Steel Excel 方法</summary><div class="wp-grid" data-group="settings">${field('E · N/mm²','E',set.E)}${field('SB1 挠度 L /','limit1',set.limit1)}${field('SB2 挠度 L /','limit2',set.limit2)}${field('CSB3 挠度 L /','limit3',set.limit3)}${field('钢材等级','grade',set.grade,'text',Object.keys(SteelCatalog.grades).map(g=>[g,g]))}${field('组合柱 fcu · N/mm²','fcu',set.fcu)}${field('组合柱 py · N/mm²','py',set.py)}${field('组合柱原表系数','wind',set.wind)}</div><p class="wp-sub">组合梁采用 M ÷ 1.6、I ÷ 2.8；组合柱采用原表混凝土包钢方法。梁表 DL = 公用 DL + SDL。</p></details>`;
  if(!list.length&&!cols.length)html+='<div class="wp-empty">先加入本次要计算的钢梁区域或组合柱。<br>只为加入的构件生成 Check 和 Section A 抄。</div>';
  list.forEach((b,i)=>{const r=Steel.bay(p,result,b),l=r.input?.loading;html+=`<section class="wp-card" data-group="bays" data-index="${i}"><div class="wp-row wp-spread"><h2>${esc(b.name)} · ${esc(FloorLevels.name(p,b.floor))}</h2>${button('remove','删除区域')}</div><div class="wp-bay"><div><div class="wp-grid">${field('编号','name',b.name,'text')}${field('楼层','floor',b.floor,'number',floors(p))}${field('类型','type',b.type,'text',[['ss','Simply supported'],['cantilever','带悬挑区']])}${field('次梁方向','angle',b.angle,'number',[[0,'横向 · 0°'],[90,'纵向 · 90°']])}${field('内部次梁数量 n','n',b.n)}${b.type==='cantilever'?field('悬挑长度 X2 · m','x2',b.x2)+field('悬挑区次梁数量','nc',b.nc):''}</div><details class="wp-detail"><summary>区域范围 · 模型坐标</summary><div class="wp-grid">${rectFields(p,result,b)}</div></details></div><div class="wp-sketch">${sketch({...b,rect:Steel.rectangle(p,result,b)||b.rect})}</div></div>${r.ok?`<p class="wp-sub">Loading 自动读取：DL ${num(l.dl)} + SDL ${num(l.sdl)} = ${num(r.input.dl)} kPa · LL ${num(l.ll)} kPa</p><table class="wp-table"><thead><tr><th>构件</th><th>Mmax · kN·m</th><th>V · kN</th><th>Ireq · cm⁴</th><th>原表选型</th><th>Check</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${x.id}</td><td>${num(x.Mmax)}</td><td>${num(x.V)}</td><td>${num(x.Ireq)}</td><td>${esc(x.selected?x.selected.family+' '+x.selected.section:'无合适截面')}</td><td class="${x.selected?'wp-ok':''}">${x.status}</td></tr>`).join('')}</tbody></table>`:`<div class="wp-alert">待补齐：${esc(r.errors.join('；'))}</div>`}<label class="wp-sub"><input type="checkbox" data-field="report" ${b.report!==false?'checked':''}> 加入 Section A · Scheme 2 抄</label></section>`;});
  cols.forEach((c,i)=>{const r=Steel.column(p,result,c);html+=`<section class="wp-card" data-group="columns" data-index="${i}"><div class="wp-row wp-spread"><h2>${esc(c.name)}</h2>${button('remove','删除柱')}</div><div class="wp-grid">${field('编号','name',c.name,'text')}${field('从楼层','from',c.from,'number',floors(p))}${field('至楼层','to',c.to,'number',floors(p))}${field('混凝土 B · mm','b',c.b)}${field('混凝土 D · mm','d',c.d)}${field('包钢截面','section',c.section,'text',[['','选择 UC 截面'],...SteelCatalog.sections.filter(s=>s.family==='UC').map(s=>[s.B,'UC '+s.B])])}</div><details class="wp-detail"><summary>各层受荷范围 · 模型坐标</summary><div class="wp-grid">${rectFields(p,result,c)}</div></details>${r.ok?`<table class="wp-table"><tr><th>累计荷载 · kN</th><th>Pcp · kN</th><th>钢材承载占比</th><th>Check</th></tr><tr><td>${num(r.N)}</td><td>${num(r.Pcp)}</td><td>${num(r.ratio*100)}%</td><td>${esc(r.status)}</td></tr></table><p class="wp-sub">已累计 ${r.rows.length} 层。每层的 DL、SDL、LL 分别读取公用 Loading。</p>`:`<div class="wp-alert">待补齐：${esc(r.errors.join('；'))}</div>`}<label class="wp-sub"><input type="checkbox" data-field="report" ${c.report!==false?'checked':''}> 加入 Section A · Scheme 2 抄</label></section>`;});return html;
 }
 function recordHTML(r){return `<section class="wp-card"><div class="wp-row wp-spread"><h2>${esc(r.label)}</h2>${r.workbook?button('open-workbook','打开 Excel',`data-id="${esc(r.runId)}" data-file="${esc(r.workbook)}"`):''}</div><p class="wp-status">${r.ok?(r.differences?.length?'发现 '+r.differences.length+' 项差异':r.compared>0?'已与 Excel 核对 '+r.compared+' 项':'已生成；未完成结果核对'):'未完成：'+esc(r.error)}</p>${r.differences?.length?`<details><summary>查看差异</summary><table class="wp-table"><tr><th>位置</th><th>App</th><th>Excel</th></tr>${r.differences.map(d=>`<tr><td>${esc(d.sheet+'!'+d.cell)}</td><td>${esc(d.app)}</td><td>${esc(d.excel)}</td></tr>`).join('')}</table></details>`:''}</section>`;}
 function excel(){const s=ExcelSync.state(),native=!!window.chrome?.webview?.postMessage;return `<div class="wp-head"><div><h1>生成 Excel</h1><p>把当前输入填入原表副本，保留公式、宏和抄。</p></div></div><div class="wp-cards">${[['Overall','Overall Check','B／D 比较与控制面的抄'],['Deflection','Deflection Check','Scheme 1 · 墙柱指定轴估算、等效均布风、B／D 比较与抄'],['RC','Scheme 1 · RC','按 Member Check 中各自勾选的 A／B 构件生成'],['Steel','Scheme 2 · Steel','已加入 Section A 的钢梁与组合柱'],['Foundation','Foundation','所选柱、桩型及 pile-cap · 原 Excel 的 A／B 抄']].map(([id,title,note])=>`<section class="wp-card"><h2>${title}</h2><p class="wp-sub">${note}</p>${button('generate','生成 '+(id==='Overall'?'Overall':id)+' Excel',`data-type="${id}" class="primary" ${s.busy||!native?'disabled':''}`)}</section>`).join('')}</div><p class="wp-sub">${esc(s.progress||(native?'需要本机 Microsoft Excel。生成后可直接打开填写好的 Excel；原始文件保持不变。':'此版本可输入、验算和保存项目；原 Excel 宏及 A／B 抄请将项目文件在 Windows 版打开后生成。'))}</p>${s.stale?'<div class="wp-alert">输入已改变，下列为上一次生成的结果。</div>':''}${s.issues.length?`<div class="wp-alert">${s.issues.map(x=>esc((x.id||'')+'：'+x.reason)).join('<br>')}</div>`:''}${s.records.map(recordHTML).join('')}`;}
 function reportTime(s){if(s.busy)return '正在生成…';if(!s.generatedAt)return '尚未生成';const d=new Date(s.generatedAt),pad=n=>String(n).padStart(2,'0');return '生成时间：'+d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+' '+pad(d.getHours())+':'+pad(d.getMinutes())+':'+pad(d.getSeconds());}
 function report(tab){const section=tab==='reportA'?'A':'B',s=ExcelSync.reportState(section),global=ExcelSync.state(),url=reportUrls[section],native=!!window.chrome?.webview?.postMessage;return `<div class="wp-head"><div><h1>Section ${section} 抄</h1><p>${section==='A'?'Scheme 1 · RC ／ Scheme 2 · Steel ／ Overall ／ Deflection Check ／ Foundation':'Scheme 1 · RC'} · 原 Excel 排版</p></div><div class="wp-row">${button('generate-report',s.busy?'生成中…':url?'重新生成抄':'生成抄',`data-section="${section}" class="primary" ${global.busy||!native?'disabled':''}`)}${button('generate-both','生成 A＋B 抄',`${global.busy||!native?'disabled':''}`)}${button('print','Print PDF',`data-section="${section}" ${!url||s.stale||global.busy?'disabled':''}`)}</div></div><p class="wp-sub"><span data-report-time>${reportTime(s)}</span>${s.busy?' · '+esc(s.progress):''}</p>${s.issues.length?`<details class="wp-alert"><summary>${s.issues.length} 项尚未生成</summary>${s.issues.map(x=>esc((x.id||'')+'：'+x.reason)).join('<br>')}</details>`:''}${s.stale?'<div class="wp-alert">输入已改变，请点击“生成抄”更新；旧版暂不可打印。</div>':''}${url?`<div class="wp-report" data-pdf="${url}" aria-label="Section ${section} 原 Excel 抄"></div>`:`<div class="wp-empty">${esc(s.message||(native?'点击“生成抄”开始，进入本页不会自动生成。':'请在 Windows 版点击“生成抄”；需要本机 Microsoft Excel。'))}</div>`}`;}

 async function paintPDF(){
  const box=root.querySelector('[data-pdf]');if(!box||box.dataset.loaded)return;box.dataset.loaded='true';
  const generation=++paintGeneration;pdfCleanup?.();pdfCleanup=null;pdfObserver?.disconnect();
  if(pdfDocument){pdfDocument.destroy();pdfDocument=null;}
  const alive=()=>generation===paintGeneration&&box.isConnected;
  box.textContent='正在显示原 Excel 抄…';
  try{
   pdfModule??=import('./pdfjs/pdf.min.mjs');const lib=await pdfModule;lib.GlobalWorkerOptions.workerSrc='./pdfjs/pdf.worker.min.mjs';
   const doc=await lib.getDocument({url:box.dataset.pdf,isEvalSupported:false,standardFontDataUrl:'./pdfjs/standard_fonts/'}).promise;
   if(!alive()){doc.destroy();return;}pdfDocument=doc;box.innerHTML='';
   const pages=new Map();let timer;
   const desired=canvas=>{const width=canvas.getBoundingClientRect().width;return width>0?DisplayQuality.size(width,width/(pages.get(canvas).aspect||210/297)):null;};
   const renderPage=async canvas=>{
    const state=pages.get(canvas);if(!alive()||!state.visible||state.running)return;
    const target=desired(canvas);if(!target||state.width===target.width)return;
    state.running=true;delete canvas.dataset.rendered;
    try{
     const page=state.page??=await doc.getPage(+canvas.dataset.page);if(!alive())return;
     const base=page.getViewport({scale:1});state.aspect=base.width/base.height;canvas.style.aspectRatio=base.width+'/'+base.height;
     const next=desired(canvas),vp=page.getViewport({scale:next.width/base.width});
     canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);
     state.task=page.render({canvasContext:canvas.getContext('2d'),viewport:vp});await state.task.promise;
     if(alive()){state.width=next.width;canvas.dataset.rendered='true';}
    }catch(e){if(alive()&&e.name!=='RenderingCancelledException'){state.failed=true;canvas.replaceWith(Object.assign(document.createElement('p'),{textContent:'页面显示失败：'+e.message}));}}
    finally{state.running=false;state.task=null;}
    if(!alive()||state.failed)return;
    if(!state.visible){canvas.width=1;canvas.height=1;state.width=0;delete canvas.dataset.rendered;return;}
    const latest=desired(canvas);if(latest&&state.width!==latest.width)requestAnimationFrame(()=>renderPage(canvas));
   };
   const repaint=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(alive())for(const [canvas,state]of pages)if(state.visible)renderPage(canvas);},100);};
   pdfObserver=new IntersectionObserver(entries=>{for(const e of entries){const state=pages.get(e.target);state.visible=e.isIntersecting;if(state.visible)renderPage(e.target);else if(!state.running){e.target.width=1;e.target.height=1;state.width=0;delete e.target.dataset.rendered;}}},{root,rootMargin:'500px'});
   const resize=new ResizeObserver(repaint);resize.observe(box);const unwatch=DisplayQuality.watch(repaint);
   pdfCleanup=()=>{clearTimeout(timer);resize.disconnect();unwatch();for(const state of pages.values())state.task?.cancel();};
   for(let i=1;i<=doc.numPages;i++){const canvas=document.createElement('canvas');canvas.dataset.page=i;canvas.setAttribute('aria-label','第 '+i+' 页，共 '+doc.numPages+' 页');pages.set(canvas,{visible:i===1,width:0,running:false,aspect:210/297});box.append(canvas);pdfObserver.observe(canvas);}
   await renderPage(box.firstElementChild);
  }catch(e){if(alive())box.textContent='预览未完成：'+e.message;}
 }

 function render(tab){if(current.startsWith('report')&&!tab.startsWith('report')){pdfCleanup?.();pdfCleanup=null;pdfObserver?.disconnect();if(pdfDocument){++paintGeneration;pdfDocument.destroy();pdfDocument=null;}lastHTML='';}current=tab;if(tab!=='deflection')DeflectionFraming91.park();const full=['foundation','sections','steel','excel','deflection','reportA','reportB'].includes(tab);document.querySelector('.layout').dataset.full=String(full);if(!full)return;const {p,result}=host.get();let html=tab==='sections'?LoadPath84.preview(p,result):tab==='foundation'?FoundationUI.render(p,result):tab==='deflection'?DeflectionUI.render(p,result):tab==='steel'?steel(p,result):tab==='excel'?excel():report(tab);if(html!==lastHTML){DeflectionFraming91.park();root.innerHTML=html;lastHTML=html;}if(tab==='deflection')DeflectionFraming91.mount();if(tab.startsWith('report')){paintPDF();}}
 function clearPDF(section){if(reportUrls[section])URL.revokeObjectURL(reportUrls[section]);delete reportUrls[section];}
 async function setPDF(section,bytes){if(reportUrls[section])URL.revokeObjectURL(reportUrls[section]);reportUrls[section]=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));render(current);}
 function axisRect(p,key){const xs=Engine.axes(p,'x',key),ys=Engine.axes(p,'y',key);const pos=x=>x.pos??x.v??x.x;return {x0:pos(xs[0]),x1:pos(xs[1]),y0:pos(ys[0]),y1:pos(ys[1])};}
 async function click(e){if(DeflectionUI.click(e,host))return;const b=e.target.closest('[data-wp]');if(!b)return;const a=b.dataset.wp,{p,floor,key}=host.get();
  if(a==='add-bay'||a==='add-column'){host.transact(()=>{const s=Steel.init(p),list=s[a==='add-bay'?'bays':'columns'];let n=1;while(list.some(x=>x.name===(a==='add-bay'?'Steel bay ':'SC')+n))n++;const rect=axisRect(p,key),xs=Engine.axes(p,'x',key),ys=Engine.axes(p,'y',key),axisRefs={x0:xs[0].id,x1:xs[1].id,y0:ys[0].id,y1:ys[1].id};if(!Object.values(rect).every(Number.isFinite))throw Error('请先设置至少两条 X、Y 轴线');list.push(a==='add-bay'?{name:'Steel bay '+n,rect,axisRefs,floor,type:'ss',angle:0,n:1,nc:0,x2:null,report:true}:{name:'SC'+n,rect,axisRefs,from:1,to:p.total,b:null,d:null,section:'',report:true});});}
  if(a==='remove'){const node=b.closest('[data-group]');host.transact(()=>Steel.init(p)[node.dataset.group].splice(+node.dataset.index,1));}
  if(a==='generate')ExcelSync.generate(b.dataset.type);
  if(a==='generate-report')ExcelSync.generateReport(b.dataset.section);
  if(a==='generate-both')ExcelSync.generateReport('AB');
  if(a==='open-workbook')ExcelSync.openWorkbook(b.dataset.id,b.dataset.file);
  if(a==='print'){const s=b.dataset.section,url=reportUrls[s];if(url&&!ExcelSync.reportState(s).stale){const name=('Section '+s+' - '+p.name).replace(/[\\/:*?"<>|]/g,'_')+'.pdf';if(window.chrome?.webview?.postMessage){const data=new Uint8Array(await (await fetch(url)).arrayBuffer());let binary='';for(let i=0;i<data.length;i+=32768)binary+=String.fromCharCode(...data.subarray(i,i+32768));window.chrome.webview.postMessage({kind:'export-file',name,encoding:'base64',value:btoa(binary)});}else{const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();}}}
 }
 function change(e){if(FoundationUI.change(e,host))return;if(DeflectionUI.change(e,host))return;const input=e.target.closest('[data-field]');if(!input)return;const node=input.closest('[data-group]'),{p}=host.get(),k=input.dataset.field;let value=input.type==='checkbox'?input.checked:input.type==='number'||['floor','from','to','angle'].includes(k)?input.value===''?null:Number(input.value):input.value;
  host.transact(()=>{const s=Steel.init(p),target=node.dataset.group==='settings'?s.settings:s[node.dataset.group][+node.dataset.index];if(k.startsWith('axis.'))target.axisRefs[k.split('.')[1]]=value;else if(k.startsWith('rect.'))target.rect[k.split('.')[1]]=value;else target[k]=value;if(target.rect&&!(target.rect.x1>target.rect.x0&&target.rect.y1>target.rect.y0))throw Error('区域上限须大于下限');if(['n','nc'].includes(k)&&!(Number.isSafeInteger(value)&&value>=0))throw Error('次梁数量须为非负整数');});
 }
 return {init,render,setPDF,clearPDF,refresh:()=>host&&render(current)};
})();
