const path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve('FramingStudio/assets/index.html')).href);
const passed=await page.evaluate(()=>{
 const ok=(v,m)=>{if(!v)throw Error(m)},near=(a,b,m)=>ok(Math.abs(a-b)<1e-6,m+': '+a+' != '+b),passed=[];
 function fixture(){const col=(id,x,y)=>({id,x,y,b:1000,d:1000,on:true,status:'上下贯通'}),beam=(id,a,z)=>({id,kind:'MB',a:{x:a[0],y:a[1]},z:{x:z[0],y:z[1]},b:400,d:500,on:true});return {format:'framing-app',version:1,name:'Bay regression',total:2,axes:{x:[{id:'1',gap:0},{id:'2',gap:6}],y:[{id:'A',gap:0},{id:'B',gap:12}]},defaults:{cb:1000,cd:1000,gap:3000,direction:'X',mb:400,sb:250,tb:600,tbd:1200,slab:200,wall:300},groups:[{end:'顶层',h:4,type:'F01',sh:500,min:0}],types:{F01:{mode:'manual',autoBeams101:false,beamLayout116:{main:false,secondary:true,mainDirection:'XY',secondaryDirection:'X',gap:3000,scope:'all'},building:{'0,0':true},opening:{},columns:[col('C1',.5,.5),col('C2',5.5,.5),col('C3',.5,11.5),col('C4',5.5,11.5),col('ROOT',.5,5)],walls:[],beams:[beam('M1',[.5,.5],[5.5,.5]),beam('M2',[.5,11.5],[5.5,11.5]),beam('M3',[.5,.5],[.5,11.5]),beam('M4',[5.5,.5],[5.5,11.5])],suppressed:[]}}};}
 for(const legacy of [false,true]){
  const p=fixture(),t=p.types.F01,before=Engine.generate(p),old=Engine.floorModel(before,1);ok(old.panels.length===1,'Initial single bay');Engine.freezeAutoBeams(p,'F01',old);if(legacy)for(const b of t.autoBeamSnapshot.secondary)delete b.bay171;
  t.beams.push({id:'CB1',kind:'CB',a:{x:.75,y:5},z:{x:5.5,y:5},b:300,d:null,widthMode:'manual',on:true});delete t.cbColumnWidth171;
  const r=Engine.generate(p),m=Engine.floorModel(r,1),cb=m.beams.find(b=>b.id==='CB1');near(cb.b,1,'Existing CB follows column after migration');ok(t.beams.find(b=>b.id==='CB1').widthMode==='column','Migration persisted');ok(m.panels.length===2,'CB closes two primary bays');
  const ys=m.beams.filter(b=>b.kind==='SB').map(b=>b.rawA[1]).sort((a,b)=>a-b);ok(ys.length===3,'Three replacement SBs');[2.75,5+6.5/3,5+13/3].forEach((y,i)=>near(ys[i],y,'Each bay spaced separately'));
  ok(new Set(m.beams.map(b=>b.id)).size===m.beams.length,'Unique member IDs');ok(m.beams.filter(b=>b.kind==='SB').every(b=>b.supportStatus==='connected'),'SBs supported');
  const autoCB=Engine.clone(p),autoModel=Engine.clone(m);autoModel.beams.find(b=>b.id==='CB1').source='auto';autoCB.types.F01.beams=autoCB.types.F01.beams.filter(b=>b.id!=='CB1');Engine.freezeAutoBeams(autoCB,'F01',autoModel);ok(autoCB.types.F01.autoBeamSnapshot.primary.some(b=>b.id==='CB1'),'CB stored as primary');const rebuilt=BeamLayout116.candidate(autoCB,'F01','secondary',{secondaryDirection:'X',gap:2500,scope:'all'});ok(Engine.floorModel(rebuilt.result,1).beams.some(b=>b.id==='CB1'),'Rebuilding SB preserves automatic CB');
  const guarded=Engine.clone(p),original=guarded.types.F01.autoBeamSnapshot.secondary;Loading.init(guarded);guarded.explorer.members['1|'+Loading.token('SB',original[0])]={L:8};const kept=Engine.floorModel(Engine.generate(guarded),1);ok(kept.issues.some(v=>JSON.stringify(v).includes('構件輸入')),'Custom SB input prevents silent replacement');ok(original.every(b=>kept.beams.some(v=>v.id===b.id&&JSON.stringify(v.rawA)===JSON.stringify(b.rawA)&&JSON.stringify(v.rawZ)===JSON.stringify(b.rawZ))),'Customized bay retains original SBs');
  const stable=JSON.stringify(m.beams);ok(JSON.stringify(Engine.floorModel(Engine.generate(Engine.clone(p)),1).beams)===stable,'Repeated regeneration stable');Engine.freezeAutoBeams(p,'F01',m);ok(t.autoBeamSnapshot.secondary.every(b=>b.bay171),'Saved SB bay metadata');ok(JSON.stringify(Engine.floorModel(Engine.generate(p),1).beams.map(b=>[b.id,b.rawA,b.rawZ]))===JSON.stringify(m.beams.map(b=>[b.id,b.rawA,b.rawZ])),'Freeze and reload retain positions');
  t.columns.find(c=>c.id==='ROOT').d=1500;let next=Engine.generate(p);for(const f of [1,2])near(Engine.floorModel(next,f).beams.find(b=>b.id==='CB1').b,1.5,'CB follows resized column on shared floors');
  Engine.editSize(p,'F01',{id:'CB1',kind:'CB',f:1},{b:700,d:null});near(Engine.floorModel(Engine.generate(p),1).beams.find(b=>b.id==='CB1').b,.7,'Later explicit manual width retained');Engine.editSize(p,'F01',{id:'CB1',kind:'CB',f:1},{b:null,d:null});near(Engine.floorModel(Engine.generate(p),1).beams.find(b=>b.id==='CB1').b,1.5,'Blank width restores column sizing');passed.push((legacy?'Legacy':'Tagged')+' saved SBs repaired per CB bay; migration, resize, override, reset and stable save');
 }
 for(const kind of ['MB','TB','CB','SB']){const p=fixture();p.types.F01.beams.push({id:'DIV',kind,a:{x:.75,y:5},z:{x:5.5,y:5},b:300,d:500,on:true});const m=Engine.floorModel(Engine.generate(p),1);ok(m.panels.length===(kind==='SB'?1:2),kind+' primary bay classification');}passed.push('MB/TB/CB divide bays; SB never divides a primary bay');
 return passed;
});assert.deepEqual(errors,[]);console.log(passed.join('\n'));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
