const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../../assets'),out=path.resolve('tmp/e2118');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{try{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')||file.endsWith('.mjs')?'text/javascript':'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:1600,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.dismiss());const url='http://127.0.0.1:'+server.address().port+'/';await page.goto(url);await page.waitForFunction(()=>window.StudioHost);await page.addScriptTag({content:fs.readFileSync(__dirname+'/boundary118-browser.js','utf8')});
 const result=await page.evaluate(()=>boundary118Tests());
 await page.locator('#file').setInputFiles({name:'synthetic.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(result.fixture))});await page.waitForFunction(()=>StudioHost.get().p.name==='Boundary regression U');
 await page.evaluate(()=>{const draw=Drawing.plan;Drawing.plan=(...args)=>window.plot118=draw(...args);StudioHost.navigate('beams');});await page.locator('#show-beam-directions118').waitFor();await page.waitForFunction(()=>plot118?.beamDirections.length>0);const projectBefore=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));
 const arrows=await page.evaluate(()=>plot118.beamDirections);assert(arrows.some(b=>b.a[0]===b.z[0]));assert(arrows.some(b=>b.a[1]===b.z[1]));
 await page.locator('#show-beam-directions118').uncheck();await page.waitForFunction(()=>plot118.beamDirections.length===0);assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),projectBefore);
 await page.locator('#show-beam-directions118').check();await page.waitForFunction(()=>plot118.beamDirections.length>0);await page.locator('#components input[data-kind=MB]').uncheck();await page.waitForFunction(()=>plot118.beamDirections.length===0);await page.locator('#components input[data-kind=MB]').check();await page.waitForFunction(()=>plot118.beamDirections.length>0);
 await page.screenshot({path:path.join(out,'beam-directions.png')});
 await page.locator('#show-beam-directions118').uncheck();await page.reload();await page.waitForFunction(()=>window.StudioHost);await page.evaluate(()=>StudioHost.navigate('beams'));assert(!(await page.locator('#show-beam-directions118').isChecked()));await page.evaluate(()=>StudioHost.navigate('checks'));assert(!(await page.locator('#beam-directions-control118').isVisible()));
 result.passed.push('Beam direction arrows: horizontal/vertical, toggle, layer visibility, reload preference, no project mutation, Beam page only');assert.deepEqual(errors,[]);delete result.fixture;fs.writeFileSync(path.join(out,'boundary-results.json'),JSON.stringify({...result,errors},null,2));console.log(JSON.stringify({passed:result.passed.length,errors}));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
