const path=require('path'),assert=require('assert/strict'),{context}=require('../../verification/integration143.cjs'),c=context(path.resolve(__dirname,'../..'));
const fixture=()=>{const col=(id,x,y)=>({id,x,y,b:1000,d:1000,on:true,status:'上下贯通'}),beam=(id,a,z)=>({id,kind:'MB',a:[...a],z:[...z],rawA:[...a],rawZ:[...z],b:.5,d:.6,widthMode:'manual'});return {format:'framing-app',version:1,name:'CB drawing support regression',total:2,axes:{x:[{id:'1',gap:0},{id:'2',gap:6}],y:[{id:'A',gap:0},{id:'B',gap:14}]},defaults:{cb:1000,cd:1000,gap:3000,direction:'X',mb:500,sb:250,tb:600,tbd:1200,slab:200,wall:300},groups:[{end:'顶层',h:4,type:'F01',sh:600,min:0}],types:{F01:{mode:'manual',cbColumnWidth171:true,autoBeams101:false,building:{'0,0':true},opening:{},columns:[col('TOP',.5,.5),col('BOTTOM',.5,13.5)],walls:[{id:'W',a:{x:5,y:.5},z:{x:5,y:13.5},b:300,on:true}],beams:[],suppressed:[],autoBeamSnapshot:{main:[beam('M1',[.5,.5],[.5,7]),beam('M2',[.5,7],[5,7]),beam('M3',[.5,7],[.5,13.5])],secondary:[]}}}};};
for(const transpose of [false,true])for(const reverse of [false,true]){
 const p=fixture(),t=p.types.F01;
 if(transpose){[p.axes.x,p.axes.y]=[p.axes.y,p.axes.x];for(const col of t.columns)[col.x,col.y]=[col.y,col.x];for(const w of t.walls)for(const q of [w.a,w.z])[q.x,q.y]=[q.y,q.x];for(const b of t.autoBeamSnapshot.main)for(const k of ['a','z','rawA','rawZ'])b[k].reverse();}
 if(reverse)for(const b of t.autoBeamSnapshot.main){[b.a,b.z]=[b.z,b.a];[b.rawA,b.rawZ]=[b.rawZ,b.rawA];}
 const out=c.run(`(()=>{const p=argument.p,r=Engine.generate(p),m=Engine.floorModel(r,1),axis=argument.transpose?0:1,geometry=JSON.stringify(r),loads=JSON.stringify(Loading.run(p,r,'B').rows),native=Drawing.svg(p,m,100,true,{}, {size:'A3',floor:1});
 const cb=m.beams.find(b=>b.id==='M2');if(cb.kind!=='CB')throw Error('fixture CB required');
 ReviewLayout191.move(p,m,[cb.kind+':'+cb.id],axis===0?.75:0,axis===1?.75:0);
 const map=ReviewLayout191.offsets(p,m.key),view=ReviewLayout191.model(m,map),legs=view.beams.filter(b=>b.id!=='M2'),ends=legs.map(b=>[b.a[axis],b.z[axis]].sort((a,z)=>a-z));
 const shapes=FramingSymbols98.members(p,m,1,r,x=>x,y=>y,1,{drawingOffsets191:map,labels:false}).shapes,poly=ReviewLayout191.beamPolygon(view.beams.find(b=>b.id==='M2')),edges=shapes.filter(s=>s.reviewBeamEdge197==='M2'),outline=edges.reduce((n,s)=>n+Math.hypot(s.x2-s.x,s.y2-s.y),0),expected=poly.reduce((n,a,i)=>{const z=poly[(i+1)%4];return n+Math.hypot(z[0]-a[0],z[1]-a[1]);},0),clipped=shapes.filter(s=>s.reviewBeamEdge197&&s.reviewBeamEdge197!=='M2').every(s=>!ReviewLayout191.insidePolygon([(s.x+s.x2)/2,(s.y+s.y2)/2],poly));
 ReviewLayout191.move(p,m,['MB:M1'],axis===0?.75:0,axis===1?.75:0);const together=ReviewLayout191.model(m,ReviewLayout191.offsets(p,m.key)).beams.find(b=>b.id==='M1');
 const saved=Engine.clone(p),reload=ReviewLayout191.model(Engine.floorModel(Engine.generate(saved),1),ReviewLayout191.offsets(saved,'F01'));ReviewLayout191.restore(p,'F01');
 return {ends,outline,expected,clipped,together:[together.a[axis],together.z[axis]],reload:reload.beams.find(b=>b.id==='M1')[argument.reverse?'a':'z'][axis],same:JSON.stringify(r)===geometry,sameLoads:JSON.stringify(Loading.run(p,r,'B').rows)===loads,sameNative:Drawing.svg(p,m,100,true,{}, {size:'A3',floor:1})===native,restore:JSON.stringify(ReviewLayout191.model(m,{}).beams.map(b=>[b.a,b.z]))===JSON.stringify(m.beams.map(b=>[b.a,b.z]))};})()`,{p,transpose,reverse});
 assert.deepEqual(JSON.parse(JSON.stringify(out.ends)),[[.5,7.75],[7.75,13.5]]);assert(Math.abs(out.outline-out.expected)<1e-8,'CB solid outline must stay complete');assert(out.together.includes(7.75)&&!out.together.includes(8.5),'batch movement must not double CB displacement');assert.equal(out.reload,7.75);for(const k of ['clipped','same','sameLoads','sameNative','restore'])assert(out[k],k);
}
const exclusions=c.run(`(()=>{const cb={id:'C',kind:'CB',a:[0,0],z:[4,0],b:.5},mb={id:'B',kind:'MB',a:[4,0],z:[4,5],b:.5},m={key:'F1',beams:[cb,mb],columns:[],walls:[]},p={};ReviewLayout191.move(p,m,['CB:C'],0,1);const map=ReviewLayout191.offsets(p,'F1'),view=q=>ReviewLayout191.model(q,map).beams.find(b=>b.id==='B').a;
 const near={...mb,a:[4,.01]},column={id:'P',x:4,y:0,b:1,d:1},ambiguous={...cb,id:'C2'};
 const root={id:'ROOT',x:0,y:0,b:1,d:1},chain={...m,columns:[root]},q={};ReviewLayout191.move(q,chain,['COL:ROOT'],0,1);const chainView=ReviewLayout191.model({...chain,beams:[cb,{...mb,a:[2,0],z:[2,5]}]},ReviewLayout191.offsets(q,'F1'));
 return {near:view({...m,beams:[cb,near]}),ambiguous:view({...m,beams:[cb,ambiguous,mb]}),column:view({...m,columns:[column]}),inherited:chainView.beams[1].a};})()`);
assert.deepEqual(JSON.parse(JSON.stringify(exclusions)),{near:[4,.01],ambiguous:[4,0],column:[4,0],inherited:[2,.5]});
console.log('PASS: CB support stretches/shortens attached MBs in both axes and endpoint orders; CB outline preserved, MB edges clipped; no double offset, reload/restore and model/load/native SVG unchanged; no nearby/ambiguous/direct-column rebinding and column-to-CB display propagation');
module.exports={p:fixture()};
