// Synthetic geometry and migration tests. No saved user project data.
function geometry120Tests(){
 const passed=[],assert=(v,m)=>{if(!v)throw Error(m);},near=(a,b,m)=>assert(Number.isFinite(a)&&Math.abs(a-b)<1e-7,m+': '+a+' != '+b),copy=Engine.clone;
 const fresh=()=>{const p=copy(loading115Tests().projects.slab);delete p.slabBoundary120;delete p.slabMigration120;return p;};
 const point=a=>({x:a[0],y:a[1]}),beam=(id,a,z,b=250)=>({id,kind:'MB',a:point(a),z:point(z),b,d:350,on:true});
 const key=r=>[r.x0,r.x1,r.y0,r.y1].map(x=>+x.toFixed(6)).join(','),area=rs=>rs.reduce((n,r)=>n+(r.x1-r.x0)*(r.y1-r.y0),0);
 // Independently sample the compressed grid, including every physical edge.
 function oracle(p){const r=Engine.generate(p),m=Engine.floorModel(r,1),solids=[...m.beams,...m.walls].map(Engine.rect).concat(m.columns.filter(c=>c.status!=='上层柱').map(Engine.columnRect)),boxes=solids.map(r=>({x0:r.x-r.w/2,x1:r.x+r.w/2,y0:r.y-r.d/2,y1:r.y+r.d/2})),holes=m.slabVoids||[],xs=[...new Set([...m.ts.flatMap(t=>[t.x0,t.x1]),...boxes.flatMap(b=>[b.x0,b.x1]),...holes.flatMap(b=>[b.x0,b.x1])])].sort((a,b)=>a-b),ys=[...new Set([...m.ts.flatMap(t=>[t.y0,t.y1]),...boxes.flatMap(b=>[b.y0,b.y1]),...holes.flatMap(b=>[b.y0,b.y1])])].sort((a,b)=>a-b),inside=(r,x,y)=>x>r.x0&&x<r.x1&&y>r.y0&&y<r.y1;
  let expected=0;for(let i=1;i<xs.length;i++)for(let j=1;j<ys.length;j++){if(xs[i]-xs[i-1]<1e-7||ys[j]-ys[j-1]<1e-7)continue;const x=(xs[i]+xs[i-1])/2,y=(ys[j]+ys[j-1])/2,free=m.ts.some(t=>t.state===1&&inside(t,x,y))&&!boxes.some(b=>inside(b,x,y))&&!holes.some(b=>inside(b,x,y)),count=m.slabs.filter(s=>s.rects.some(b=>inside(b,x,y))).length;assert(count===(free?1:0),'Net cells cover floor exactly once and never concrete/opening');if(free)expected+=(xs[i]-xs[i-1])*(ys[j]-ys[j-1]);}
  near(m.slabs.reduce((n,s)=>n+s.area,0),expected,'union area');for(const s of m.slabs){near(area(s.rects),s.area,'panel rect area');near(area(LoadRegions83.netSelfWeight(s,m)),s.area,'self weight is not deducted twice');}
  return {r,m,expected};
 }
 for(const width of [150,250,600]){const p=fresh();p.types.F1.columns.forEach(c=>c.b=c.d=width);p.types.F1.beams.forEach(b=>b.b=width);const {m,expected}=oracle(p);assert(m.slabs.length===1&&m.slabs[0].rectangular,'Inset perimeter closes one net rectangle');near(expected,(6-2*width/1000)*(4-2*width/1000),'known clear rectangle');const rows=Loading.run(p,Engine.generate(p),'B').rows.filter(r=>r.actions);const total=rows.reduce((n,r)=>n+r.actions.totalLive,0),target=(24-4*(width/1000)**2)*2,bound=rows.flatMap(r=>r.loading.lines).reduce((n,l)=>n+.0100001*(l.end-l.start),0);assert(total>=target-1e-7&&total-target<=bound+1e-7,'net slab plus beam-top live load conserved with rounding');}
 passed.push('Multiple perimeter widths: exact net rectangles, full beam weight, no double slab deduction, conserved reactions');
 const divided=fresh();divided.types.F1.beams.push(beam('DIVIDER',[3,0],[3,4]));const d=oracle(divided);assert(d.m.slabs.length===2,'physical through beam separates two panels');assert(d.m.slabs.every(s=>s.rectangular),'separate panels rectangular');
 const reverse=copy(divided);reverse.types.F1.beams.reverse().forEach(b=>[b.a,b.z]=[b.z,b.a]);const rev=oracle(reverse);assert(JSON.stringify(d.m.slabs.map(Loading.token.bind(null,'SLAB')))==JSON.stringify(rev.m.slabs.map(Loading.token.bind(null,'SLAB'))),'order and endpoint reversal keep stable slab identities');
 const short=copy(divided);short.types.F1.beams.at(-1).z.y=3;assert(oracle(short).m.slabs.length===1,'a real end gap remains connected');
 const deleted=copy(divided);deleted.types.F1.beams.pop();assert(oracle(deleted).m.slabs.length===1,'deleting separator rebuilds connected topology');
 const resized=copy(divided);resized.types.F1.beams.at(-1).b=600;near(oracle(resized).expected,d.expected-(.6-.25)*3.5,'resizing a beam changes net area by physical width');
 passed.push('Through beam, short beam, deletion, resizing and member reversal rebuild topology without artificial extension');
 for(const name of ['opening','notch','wideColumn','overlap','narrow']){const p=fresh(),t=p.types.F1;if(name==='opening')t.slabVoids=[{x0:2,x1:4,y0:1,y1:3}];if(name==='notch'){t.slabVoids=[{x0:0,x1:2,y0:1,y1:3}];}if(name==='wideColumn')t.columns.forEach(c=>c.b=c.d=500);if(name==='overlap')t.walls.push({id:'W',a:point([0,0]),z:point([6,0]),b:400,on:true});if(name==='narrow')t.beams.push(beam('NARROW',[.5,0],[.5,4]));const {m}=oracle(p);if(name==='narrow')assert(m.slabs.some(s=>s.x1-s.x0<.2),'genuine narrow panel retained');if(name==='wideColumn')assert(m.slabs.some(s=>!s.rectangular),'column notches are not silently filled');}
 passed.push('Openings, notches, wider columns, overlapping concrete and genuine narrow panels keep their exact physical union');
 const square=fresh();square.axes.x[1].gap=4;square.types.F1.columns.filter(c=>c.x===6).forEach(c=>c.x=4);square.types.F1.beams.forEach(b=>{if(b.a.x===6)b.a.x=4;if(b.z.x===6)b.z.x=4;});let sm=oracle(square).m,s=sm.slabs[0],st=Loading.token('SLAB',s);assert(Loading.slabDirection(square,1,st,s,sm)===null,'square requires explicit direction');let rows=Loading.run(square,Engine.generate(square),'B').rows;assert(rows.find(r=>r.kind==='SLAB').loadErrors.some(e=>e.includes('X 或 Y')),'square pending message');assert(rows.filter(r=>r.kind==='MB').every(r=>!r.actions&&r.loadErrors.some(e=>e.includes('X 或 Y'))),'missing square direction blocks downstream reactions');assert(SlabMarks83.layout(square,1,s,sm,100).every(x=>x.dir===null),'small slab markers agree with pending square');
 for(const dir of ['X','Y']){BeamLayout116.setDirections(square,'F1',[s],dir);const r=Engine.generate(square);sm=Engine.floorModel(r,1);s=sm.slabs[0];rows=Loading.run(square,r,'B').rows;assert(rows.filter(r=>r.kind==='MB').every(r=>r.actions),'chosen direction resolves square loading');assert(SlabMarks83.layout(square,1,s,sm,100).every(x=>x.dir===dir),'all diagram anchors use the saved direction');near(rows.filter(r=>r.actions).reduce((n,r)=>n+r.actions.totalLive,0),31.5,'square reactions conserve slab and beam-top live load');}
 passed.push('Square X/Y prompt blocks downstream false passes; choosing either direction restores conserved reactions and consistent arrows');
 const physical=d.m.beams.find(b=>b.id==='DIVIDER'),rect=Engine.rect(physical);assert(SlabGeometry120.face(physical,0,rect.x-rect.w/2),'actual side face identified');assert(!SlabGeometry120.face(physical,0,rect.x-rect.w/2-.001),'no tolerance bridge across a real gap');const cap=SlabGeometry120.face(physical,1,0);assert(cap&&Math.abs(cap[0]-(rect.x-rect.w/2))<1e-7&&Math.abs(cap[1]-(rect.x+rect.w/2))<1e-7,'end-cap contact is its actual width interval, transferred as a point by Loading');
 passed.push('Support lookup uses actual side/end faces without bridging gaps; end-cap width remains physical');
 // Emulate an old connected outline split into independent net panels.
 const p=copy(divided);delete p.slabBoundary120;const result=Engine.generate(copy(divided)),m=Engine.floorModel(result,1),old={rects:[{x0:0,x1:6,y0:0,y1:4}],area:24},oldToken=SlabGeometry120.token(old),oldSig=SlabGeometry120.signature(old);SlabGeometry120.decorate(m.slabs,[old]);
 p.types.F1.slabDirections116={[oldToken]:'Y'};p.types.F1.slabSizes=[{signature:oldSig,value:225}];p.explorer.members['1|'+oldToken]={direction:'Y',slabType:'SS',steel:{test:'kept'}};for(const k of ['selected','reportA','reportB'])p.explorer[k]['1|'+oldToken]=true;const region=LoadData.addArea(p,1);Object.assign(region,{panels:[oldToken],rects:undefined,dl:14,sdl:2,ll:3});
 SlabGeometry120.migrate(p,result);for(const n of m.slabs){const token=Loading.token('SLAB',n);assert(p.explorer.members['1|'+token].steel.test==='kept','manual input migrated');for(const k of ['selected','reportA','reportB'])assert(p.explorer[k]['1|'+token],'selection migrated '+k);assert(p.types.F1.slabDirections116[token]==='Y','manual direction migrated');assert(p.types.F1.slabSizes.some(v=>v.signature===SlabGeometry120.signature(n)&&v.value===225),'slab thickness migrated');assert(region.panels.includes(token),'region token migrated');}
 assert(!p.explorer.members['1|'+oldToken]&&p.slabMigration120.members['1|'+oldToken],'obsolete key archived, not orphaned');const saved=JSON.stringify(p);SlabGeometry120.migrate(p,result);assert(JSON.stringify(p)===saved,'migration idempotent');Engine.validate(copy(p));const reopened=Engine.generate(copy(p));assert(Engine.floorModel(reopened,1).slabs.every(s=>s.thickness===225&&s.direction116==='Y'),'saved thickness and direction survive regeneration');
 passed.push('One-to-many migration preserves inputs, A/B inclusion, checks, thickness, direction and load regions; archive, idempotence and reload verified');
 return {passed};
}
