// Actual-model regression for the approved Horizontal drawing, UI settings and report isolation.
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const out=path.resolve('tmp/e2133');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage({viewport:{width:1640,height:1150}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());await page.goto(pathToFileURL(path.resolve('FramingStudio/assets/index.html')).href);await page.waitForFunction(()=>window.StudioHost);
 const file=process.env.FRAMING_2015_FIXTURE||'output/HKIE_Calculation_Audit/2015_local_heights_E2128/HKIE_2015_Q3_TrialCheck_v2_E2.128.framing.json';assert(fs.existsSync(file),'Set FRAMING_2015_FIXTURE to the saved 2015 regression model');
 await page.locator('#file').setInputFiles(path.resolve(file));
 const core=await page.evaluate(()=>{
  const h=StudioHost.get(),p=h.p,m=h.result,H=HorizontalPath133,before=JSON.stringify(p),passed=[],ok=(x,msg)=>{if(!x)throw Error(msg);},same=(x,y,msg)=>ok(JSON.stringify(x)===JSON.stringify(y),msg),near=(a,b,msg)=>ok(Math.abs(a-b)<1e-7,msg+': '+a+' / '+b);
  const cuts=H.cuts(p,m),one=H.diagram(p,m,'one'),two=H.diagram(p,m,'two');near(cuts.one.at,29,'First cut preserved');near(cuts.two.at,8.25,'Cut through continuous wall, not X21 podium');ok(one.diagnostics.pair&&two.diagnostics.pair,'Both cuts use continuous walls');
  for(const d of [one,two])for(const a of d.shapes.filter(s=>s.role133==='axial')){const w=a.world,s=w.support;ok(w.x>=s.a-.001&&w.x<=s.b+.001&&w.z0>=s.z0&&w.z1<=s.z1,'Axial arrow lies inside actual wall extent');}
  const tb=one.shapes.find(s=>s.role133==='TB'),label=one.shapes.find(s=>s.role133==='TB-label');ok(tb&&label&&label.x>=tb.x-20&&label.x+label.w<=tb.x+tb.w+20,'TB label at actual transfer beam');ok(one.shapes.filter(s=>s.role133==='TB-label').length===1,'Split TB merged once');
  ok(!one.diagnostics.pressure.length&&one.diagnostics.pending.includes('Wind inputs required'),'Missing wind and no basement produce no sample pressures');
  passed.push('2015 cuts, real core-wall extents, no floating podium arrows, merged TB label, no invented wind or underground loads');
  const manual=Engine.clone(p);manual.explorer.loadPath84=H.legacy.settings(p,m);manual.explorer.loadPath84.horizontal133={autoCuts:false,faceAuto:false,sign:-1};const md=H.diagram(manual,m,'two');near(md.selection.at,21,'Manual cut retained');ok(!md.diagnostics.pair&&!md.shapes.some(s=>s.role133==='axial'),'X21 has no invented upper support');ok(md.selection.face===manual.explorer.loadPath84.face,'Manual Overall face honored');
  const reversed=H.diagram(manual,m,'one'),pos=one.shapes.filter(s=>s.role133==='axial'),neg=reversed.shapes.filter(s=>s.role133==='axial');for(let i=0;i<pos.length;i++){near(pos[i].x,neg[i].x,'Same axial member');near(pos[i].y,neg[i].y2,'Opposite axial direction');near(pos[i].y2,neg[i].y,'Opposite axial end');}ok(reversed.shapes.filter(s=>s.role133==='floor-force').every(s=>s.x>s.x2),'Negative floor arrows reverse');
  for(const kind of ['one','two','both']){const q=Engine.clone(p);q.explorer.loadPath84=H.legacy.settings(p,m);q.explorer.loadPath84.picks.horizontal=kind;const d=H.reportDiagram(q,m);near(d.height,kind==='both'?640:410,'Original report height contract');ok(d.shapes.filter(s=>s.fixed&&s.text==='Horizontal load').length===1,'Fixed mechanism exactly once');same(LoadPath84.reportDiagram(q,m,'vertical'),H.legacy.reportDiagram(q,m,'vertical'),'Vertical report preserved');}
  passed.push('Manual cuts and faces, reverse arrows, one/two/both reports, fixed mechanism once and unchanged Vertical diagram');
  const s=(kind,id,x,w,z0,z1)=>({kind,id,a:x-w/2,b:x+w/2,r:{x,y:0,w,d:.5},z0,z1,member:{}}),synthetic={height:30,solids:[]};
  const frame=[s('COL','tower-L',0,.6,0,30),s('COL','tower-R',10,.6,0,30),s('COL','podium',40,.6,0,6)];synthetic.solids=frame;const pair=H.axialPair(frame,synthetic,'Y');near(pair.x1,10,'Short outer podium excluded');
  const broken=[s('COL','L',0,.6,0,30),s('COL','R',10,.6,0,10),s('COL','R',10,.6,12,30)];ok(!H.axialPair(broken,{...synthetic,solids:broken},'Y'),'Missing storey not bridged');
  const disjoint=[s('WALL','L',0,.4,0,30),s('WALL','R',20,.4,0,30)];ok(!H.axialPair(disjoint,{...synthetic,solids:disjoint},'Y'),'Disconnected wall ends not assumed one core');
  const broad=[s('WALL','W',15,10,0,15),s('WALL','W',15,10,15,30)];const broadPair=H.axialPair(broad,{...synthetic,solids:broad},'Y');near(broadPair.x0,10,'Merged broad wall left edge');near(broadPair.x1,20,'Merged broad wall right edge');
  passed.push('Different models: short podium, frame-only, broken storey, disjoint walls and continuous in-plane wall');
  const newPages=ReportContent.references(p,m),render=LoadPath84.reportDiagram;let oldPages;try{LoadPath84.reportDiagram=H.legacy.reportDiagram;oldPages=ReportContent.references(p,m);}finally{LoadPath84.reportDiagram=render;}
  same(newPages.filter(q=>q.key!=='horizontal'),oldPages.filter(q=>q.key!=='horizontal'),'All unrelated report pages identical');const newH=newPages.find(q=>q.key==='horizontal'),oldH=oldPages.find(q=>q.key==='horizontal');for(const key of Object.keys(oldH).filter(k=>k!=='shapes'))same(newH[key],oldH[key],'Original Horizontal '+key+' preserved');
  same(JSON.parse(before),p,'Rendering preserves all project input');
  // Complete Overall inputs in an isolated synthetic copy only, never saved into user data.
  const q=Engine.clone(p);q.elevationLevels={...q.elevationLevels,base:0,basementFromNames:true,names:{...q.elevationLevels.names,0:'B1/F'}};q.overall={version:1,faces:{},automation:{weight:false,wind:false}};for(const f of ['B','D'])q.overall.faces[f]={input:{...Overall.defaults(f),mode:'UNIFORM',height:102.5,baseRL:0,leftEL:6,rightEL:6,leftGWL:4,rightGWL:3,basement:'Yes',gammaLeft:20,gammaRight:19,submergedLeft:10,submergedRight:9,gammaWater:9.81,phi:30,leftQ:12,rightQ:0},surchargeConfirmed:{leftQ:true,rightQ:true}};
  const input=OverallGeometry.input(q,'B'),machine=Overall.machine(input,'B'),ld=H.loading(q,'B',0,102.5);ok(ld.wind.length>0,'Valid uniform wind rendered');ok(ld.pressure.length===5,'Soil, water and left surcharge; right zero omitted: '+JSON.stringify(ld));
  for(const r of ld.pressure){const col=r.side==='L'?'B':'G',row={Soil:48,Water:47,Surcharge:49}[r.kind];near(r.basePressure,machine.safe(Overall.roles[3],col+row),'Original Overall base pressure');}
  const clip=H.loading(q,'B',2,3);ok(!clip.wind.length&&!clip.pending.includes('Wind inputs required'),'Valid wind above selected basement not called missing');const water=clip.pressure.find(r=>r.kind==='Water'&&r.side==='L');near(water.points[0].q,ld.pressure.find(r=>r.kind==='Water'&&r.side==='L').basePressure/2,'Partial-storey clipping uses original water pressure datum');ok(clip.pressure.every(r=>r.points.every(v=>v.z>=2&&v.z<=3)),'All underground profiles clipped to selection');
  q.overall.faces.B.input.gammaLeft=null;delete q.overall.faces.B.input.leftQ;q.overall.faces.B.input.gammaWater=null;const missing=H.loading(q,'B',0,102.5);ok(!missing.pressure.some(r=>r.side==='L'&&r.kind!=='Water'),'Missing explicit soil/q are not default triangles');ok(!missing.pressure.some(r=>r.kind==='Water'),'Missing water unit weight is pending');
  const full=Engine.clone(q);for(const face of ['B','D'])full.overall.faces[face].input={...input};full.overall.faces.B.input.leftQ=12;full.overall.faces.B.input.rightQ=0;full.overall.automation.wind=true;full.overall.faces.B.input.mode="LAYERED";const layered=H.loading(full,'B',0,102.5);ok(layered.input.mode==='LAYERED'&&layered.wind.length>1,'Automatic layered wind is read from Overall: '+JSON.stringify({mode:layered.input.mode,meta:layered.input._auto,count:layered.wind.length,pending:layered.pending}));
  const pressure=H.diagram(full,Engine.generate(full),'one');ok(pressure.shapes.filter(s=>s.role133==='pressure'&&s.side==='L').every(s=>s.x<s.x2),'Left pressure inward');ok(pressure.shapes.filter(s=>s.role133==='pressure'&&s.side==='R').every(s=>s.x>s.x2),'Right pressure inward');
  passed.push('Overall uniform/layered wind, original pressure values, inward L/R soil/water/surcharge, zero/missing inputs and clipped levels');passed.push('Report-content runtime equality and project immutability');
  window.fixtureHorizontal133=full;window.pagesHorizontal133=newPages;return {passed,cuts,pressureSVG:H.svg(pressure),wideSVG:H.svg(one),secondSVG:H.svg(two),references:newPages.filter(q=>['vertical','horizontal'].includes(q.key)),fixture:full};
 });
 console.log(JSON.stringify({core:core.passed}));
 await page.evaluate(()=>StudioHost.navigate('sections'));await page.locator('.hp133-controls').waitFor();const original=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('#lp84-h133-sign').selectOption('-1');assert.equal(await page.evaluate(()=>StudioHost.get().p.explorer.loadPath84.horizontal133.sign),-1);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),original);await page.locator('#lp84-h133-sign').selectOption('-1');await page.locator('#lp84-h133-cuts').uncheck();assert((await page.locator('.hp133-controls').textContent()).includes('X = 21 m'));await page.locator('#lp84-h133-face').uncheck();assert(await page.locator('#lp84-face').isEnabled());await page.locator('#lp84-face').selectOption('D');const saved=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('#file').setInputFiles({name:'horizontal133.framing.json',mimeType:'application/json',buffer:Buffer.from(saved)});await page.evaluate(()=>StudioHost.navigate('sections'));assert.equal(await page.locator('#lp84-h133-sign').inputValue(),'-1');assert(!(await page.locator('#lp84-h133-cuts').isChecked()));assert.equal(await page.locator('#lp84-face').inputValue(),'D');
 await page.locator('#lp84-h133-sign').selectOption('1');await page.locator('#lp84-h133-cuts').check();await page.locator('#lp84-h133-face').check();const card=page.locator('.wp-card').filter({has:page.getByRole('heading',{name:'Horizontal Load Path',exact:true})});await card.screenshot({path:path.join(out,'horizontal-wide.png')});await page.locator('.hp133-plan').screenshot({path:path.join(out,'plan.png')});await page.setViewportSize({width:1080,height:800});await card.screenshot({path:path.join(out,'horizontal-narrow.png')});assert(await card.evaluate(e=>e.scrollWidth<=e.clientWidth+2),'Card fits narrow viewport');
 core.passed.push('Actual UI: automatic/manual cuts, face selection, direction, undo, saved JSON reopen and narrow layout');
 fs.writeFileSync(path.join(out,'pressure.html'),'<body style="margin:0;background:white;width:1080px">'+core.pressureSVG+'</body>');fs.writeFileSync(path.join(out,'section1.html'),'<body style="margin:0;background:white;width:1080px">'+core.wideSVG+'</body>');fs.writeFileSync(path.join(out,'section2.html'),'<body style="margin:0;background:white;width:1080px">'+core.secondSVG+'</body>');for(const name of ['pressure','section1','section2']){await page.goto(pathToFileURL(path.join(out,name+'.html')).href);await page.locator('svg').screenshot({path:path.join(out,name+'.png')});}
 const native=path.resolve('tmp/e2132/native-column-A-0/job.json');if(fs.existsSync(native)){const job=JSON.parse(fs.readFileSync(native,'utf8'));job.preview=true;job.reportPages=core.references;job.fingerprint=crypto.createHash('sha256').update(JSON.stringify(job)).digest('hex');fs.mkdirSync(path.join(out,'native-report'),{recursive:true});fs.writeFileSync(path.join(out,'native-report/job.json'),JSON.stringify(job));}
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'horizontal133.json'),JSON.stringify({passed:core.passed,cuts:core.cuts,errors},null,2));console.log(JSON.stringify({passed:core.passed,errors}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
