const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{context}=require('../../verification/integration143.cjs'),fixture=require('./tributary187.cjs');
const root=path.resolve(__dirname,'../..'),c=context(root);c.ctx.setTimeout=setTimeout;c.ctx.clearTimeout=clearTimeout;
(async()=>{
 c.run(`globalThis.inc228={p:Engine.clone(argument)};inc228.p.total=2;inc228.p.groups[0].end='顶层';LoadData.setFloor(inc228.p,2,{usage:'Dormitory',dl:10,sdl:0,ll:2});`,fixture.p);
 const result=await c.run(`(async()=>{
 const base=inc228.p,run=(p,cache=null,advice=false)=>AuditRunner132.run(p,Engine.generate(p),{beamSummary:BeamLoadUI.summary211,includePassedBeams:true,recommendSB:advice,retainOutput226:true,capture228:true,reuse228:cache}),strip=a=>{const {cache228,stats228,...x}=a;return JSON.stringify(x);};
 const first=await run(base),cacheBefore=JSON.stringify([...first.cache228.design]),same=await run(base,first.cache228),results=[];
 if(same.stats228.calls!==0||same.stats228.changed!==0||strip(first)!==strip(same))throw Error('Identical run did not reuse current results');
 const variants={
 width:p=>p.types.F1.beams[0].b+=50,
 depth:p=>{p.types.F1.beams[0].d+=50;p.types.F1.beams[0].depthOverride184=p.types.F1.beams[0].d;},
 load:p=>LoadData.setFloor(p,2,{usage:'Dormitory',dl:10,sdl:5,ll:7}),
 material:p=>{Loading.init(p).settings={...Loading.settings(p),fcu:60};},
 steel:p=>{const m=Loading.members(p,Engine.generate(p),1).find(m=>m.kind==='MB');Loading.input(p,1,m.token);p.explorer.members[1+'|'+m.token]={steel:{C44:4,D44:32,E58:2,G58:10,H58:150,E76:2,G76:8,H76:250}};},
 invalidSupport:p=>{const m=Loading.members(p,Engine.generate(p),1).find(m=>m.kind==='MB');p.explorer.members[1+'|'+m.token]={supportA:'COL|missing'};},
 column:p=>p.types.F1.columns[0].b+=100,
 geometry:p=>p.types.F1.beams.splice(0,1),
 scope:p=>{p.explorer.selected={};p.explorer.reportA={};p.explorer.reportB={};}
 };
 for(const [name,edit] of Object.entries(variants)){const p=Engine.clone(base);edit(p);const before=JSON.stringify(p),cached=await run(p,first.cache228),fresh=await run(p);if(strip(cached)!==strip(fresh))throw Error(name+' differs from full recalculation');if(before!==JSON.stringify(p))throw Error(name+' mutated project');results.push({name,...cached.stats228});}
 const cancelled=await AuditRunner132.run(base,Engine.generate(base),{capture228:true,reuse228:first.cache228,cancelled:()=>true});if(cancelled!==null||cacheBefore!==JSON.stringify([...first.cache228.design]))throw Error('Previous cache mutated');
 return {same:same.stats228,results};
 })()`);
 assert(result.results.find(r=>r.name==='width').changed>0);assert(result.results.find(r=>r.name==='load').changed>0);assert(result.results.find(r=>r.name==='steel').changed>0);assert(result.results.some(r=>r.unchanged>0));
 console.log('PASS incremental/full parity for shared Framing dimensions, loads, material, reinforcement, support, columns, geometry and report scope; immutable previous cache/cancellation',JSON.stringify(result));
 // Exercise real TB sizing advice with cached design and candidate inputs.
 c.run(fs.readFileSync(path.join(__dirname,'loading115-browser.js'),'utf8'));
 const advice=await c.run(`(async()=>{const p=Engine.clone(loading115Tests().projects.slab),b=p.types.F1.beams[0];b.kind='TB';b.b=250;b.d=null;b.widthMode='manual';b.depthOverride184=250;let r=Engine.generate(p);const m=Engine.floorModel(r,1).beams.find(b=>b.id==='B1'),token=Loading.token('TB',m);p.explorer.members['1|'+token]={mode:'manual',beamSelfWeight:true,beamLoads:[{type:'line',a:0,b:Loading.beamSpan(m).value,dl:130,ll:10}]};const options={beamSummary:BeamLoadUI.summary211,includePassedBeams:true,recommendSB:true,retainOutput226:true,capture228:true};const baseline=await AuditRunner132.run(p,r,options),item=baseline.items.find(i=>i.tbAdvice221&&!i.tbAdvice221.reason);if(!item)throw Error('Advice fixture missing');const before=JSON.stringify(p);TBApply222.apply(p,r,item);r=Engine.generate(p);const inc=await AuditRunner132.run(p,r,{...options,reuse228:baseline.cache228}),fresh=await AuditRunner132.run(p,r,{...options,capture228:false}),clean=x=>{const {cache228,stats228,...other}=x;return JSON.stringify(other);};if(clean(inc)!==clean(fresh))throw Error('Advice parity');return inc.stats228;})()`);
 const upper=await c.run(`(async()=>{const p=Engine.clone(inc228.p);p.total=4;p.types.F2=Engine.clone(p.types.F1);p.groups=[{...p.groups[0],end:2,type:'F1'},{...p.groups[0],end:'顶层',type:'F2'}];for(let f=3;f<=4;f++)LoadData.setFloor(p,f,{usage:'Dormitory',dl:10,sdl:0,ll:2});const opts={beamSummary:BeamLoadUI.summary211,includePassedBeams:true,retainOutput226:true,capture228:true},first=await AuditRunner132.run(p,Engine.generate(p),opts);p.types.F1.beams[0].d+=50;p.types.F1.beams[0].depthOverride184=p.types.F1.beams[0].d;const model=Engine.generate(p),inc=await AuditRunner132.run(p,model,{...opts,reuse228:first.cache228}),full=await AuditRunner132.run(p,model,opts),clean=x=>{const {cache228,stats228,...rest}=x;return JSON.stringify(rest);};if(clean(inc)!==clean(full))throw Error('Upper floor force/area replay parity');p.transferTrusses=[{id:'inactive',name:'Inactive',enabled:false,bottomFloor:1,topFloor:2,sourceIds:[]}];const truss=await AuditRunner132.run(p,Engine.generate(p),opts),again=await AuditRunner132.run(p,Engine.generate(p),{...opts,reuse228:truss.cache228});return {stats:inc.stats228,truss:again.stats228.reusedFloors};})()`);assert.equal(upper.stats.reusedFloors,2);assert.equal(upper.truss,0);console.log('PASS unchanged upper floors and column area schedules replay identically; truss projects rebuild transfer',JSON.stringify(upper));
 const trial=await c.run(`(async()=>{const p=Engine.clone(loading115Tests().projects.slab);p.total=3;p.types.F2=Engine.clone(p.types.F1);p.groups=[{...p.groups[0],end:1,type:'F1'},{...p.groups[0],end:'顶层',type:'F2'}];const b=p.types.F1.beams[0];b.kind='TB';b.b=250;b.d=null;b.widthMode='manual';b.depthOverride184=250;const r=Engine.generate(p),m=Engine.floorModel(r,1).beams.find(b=>b.id==='B1'),token=Loading.token('TB',m);p.explorer.members['1|'+token]={mode:'manual',beamSelfWeight:true,beamLoads:[{type:'line',a:0,b:Loading.beamSpan(m).value,dl:130,ll:10}]};const opts={beamSummary:BeamLoadUI.summary211,includePassedBeams:true,recommendSB:true,retainOutput226:true},fast=await AuditRunner132.run(p,r,{...opts,capture228:true}),reference=await AuditRunner132.run(p,r,opts),clean=x=>{const {cache228,stats228,...other}=x;return JSON.stringify(other);};if(clean(fast)!==clean(reference))throw Error('Candidate trial upper-floor reuse changed advice');const advice=fast.items.filter(i=>i.tbAdvice221&&!i.tbAdvice221.reason);if(!advice.length)throw Error('Multi-floor trial did not produce TB advice');return {advice:advice.length,stats:fast.stats228};})()`);console.log('PASS multi-Framing candidate sizing equals uncached full solver',JSON.stringify(trial));
 const scopes=await c.run(`(async()=>{const p=Engine.clone(inc228.p),r=Engine.generate(p),original=ColumnAreas103.snapshot228,opts={beamSummary:BeamLoadUI.summary211,includePassedBeams:true,retainOutput226:true};const fast=await AuditRunner132.run(p,r,opts);ColumnAreas103.snapshot228=()=>()=>{};const reference=await AuditRunner132.run(p,r,opts);ColumnAreas103.snapshot228=original;if(JSON.stringify(fast)!==JSON.stringify(reference))throw Error('Scoped area cache differs from original path');let started=0,released=0,calls=0;ColumnAreas103.snapshot228=(...args)=>{started++;const release=original(...args);return ()=>{released++;release();};};await AuditRunner132.run(p,r,{...opts,cancelled:()=>++calls>2});ColumnAreas103.snapshot228=original;return {started,released};})()`);assert(scopes.started>0);assert.equal(scopes.started,scopes.released);
 console.log('PASS scoped immutable column-area hashing matches original path and releases on cancellation');
 console.log('PASS after TB application: loading, RC, deflection and size recommendations equal a full audit',JSON.stringify(advice));
})().catch(e=>{console.error(e);process.exitCode=1;});

