// Full-floor load selection and diagram presentation; synthetic projects only.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=path.resolve('FramingStudio/assets'),out=path.resolve('tmp/e2129');fs.mkdirSync(out,{recursive:true});
const baseline=execFileSync('git',['show','22684118dfaf41696f5cef14528f06082f8f565d:FramingStudio/assets/index.html'],{maxBuffer:30*1024*1024});
const server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost').pathname;if(url==='/baseline/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(baseline);return;}const file=path.resolve(root,'.'+(url==='/'?'/index.html':url));if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':'text/javascript');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:1700,height:1100}}),errors=[],passed=[];page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());const url='http://127.0.0.1:'+server.address().port;
 await page.goto(url);await page.waitForFunction(()=>window.StudioHost);await page.addScriptTag({content:fs.readFileSync(__dirname+'/loading115-browser.js','utf8')});
 const fixtures=await page.evaluate(()=>loading115Tests().projects);
 const old=await browser.newPage();await old.goto(url+'/baseline/');await old.waitForFunction(()=>window.StudioHost);
 const calculate=(pg,p)=>pg.evaluate(p=>{const r=Engine.generate(p);return JSON.stringify({geometry:r,loads:Loading.run(p,r,'B'),a:RCPlan.build(p,'A'),b:RCPlan.build(p,'B')});},p);
 for(const p of Object.values(fixtures))assert.equal(await calculate(page,p),await calculate(old,p),'Existing calculations and native report inputs unchanged');await old.close();passed.push('E2.128 geometry, loads and Section A/B native inputs remain identical for existing projects');
 const checks=await page.evaluate(fixtures=>{
  const check=(v,m)=>{if(!v)throw Error(m);},near=(a,b,m)=>check(Math.abs(a-b)<1e-7,m+': '+a+' / '+b),copy=Engine.clone,area=rs=>rs.reduce((n,r)=>n+LoadRegions83.area(r),0),p=copy(fixtures.slab);
  p.total=2;p.groups[0].end='顶层';LoadData.setFloor(p,2,LoadData.floor(p,1));p.axes.x=[{id:'1',gap:0},{id:'2',gap:3},{id:'3',gap:3}];p.axes.y=[{id:'A',gap:0},{id:'B',gap:2},{id:'C',gap:2}];Object.assign(p.types.F1.building,{'0,1':true,'1,0':true,'1,1':true});p.types.F1.opening['1,1']=true;
  let result=Engine.generate(p),m=Engine.floorModel(result,1);
  for(const [a,z,wanted]of [[[.5,.5],[.6,1.5],{x0:0,x1:3,y0:0,y1:2}],[[.5,.5],[5,3],{x0:0,x1:6,y0:0,y1:4}],[[5,3],[.5,.5],{x0:0,x1:6,y0:0,y1:4}],[[3.2,.5],[3.2,.5],{x0:3,x1:6,y0:0,y1:2}],[[0,0],[3,2],{x0:0,x1:3,y0:0,y1:2}]])check(JSON.stringify(LoadRegions83.axisBox(p,'F1',a,z))===JSON.stringify(wanted),'Axis rectangle '+JSON.stringify([a,z]));
  check(LoadRegions83.axisBox(p,'F1',[-2,-2],[-1,-1])===null,'Outside drag does not select a bay');
  const offset=copy(p);offset.axes.origin={x:-10,y:15};const shifted=LoadRegions83.axisBox(offset,'F1',[-9.5,15.5],[-9.4,16.5]);check(shifted.x0===-10&&shifted.x1===-7&&shifted.y0===15&&shifted.y1===17,'Offset and negative architectural coordinates');
  const rs=LoadRegions83.clipSurface([{x0:0,x1:3,y0:0,y1:2}],m),size=area(rs);near(size,6-.25*.25,'Bay includes beam tops, excludes one corner column');
  const floorArea=area(LoadRegions83.surface(m));near(floorArea,18-3*.25*.25,'Opening and column footprints deducted exactly');near(LoadGroups.overview(p,result,1).reduce((n,g)=>n+g.area,0),floorArea,'Legend covers the whole occupied surface');
  const draft={lo:1,hi:2,scope:'area',name:'Bay load',usage:'手动',dl:10,sdl:1.5,ll:5,panels:[],rects:rs,selectionRects:[{x0:0,x1:3,y0:0,y1:2}],replaceOverlap:true};LoadGroups.save(p,result,'F1',draft,null);
  for(const f of [1,2]){near(area(p.explorer.areas[f][0].rects),size,'Same Framing floor '+f);check(!LoadData.validate(p,f,m.slabs.map(s=>Loading.token('SLAB',s)),m).length,'Valid explicit area');}
  let pieces=LoadRegions83.pieces(p,1,{rects:LoadRegions83.surface(m)},LoadRegions83.surfaceRegions(p,1,m));near(pieces.reduce((n,r)=>n+LoadRegions83.area(r)*r.load.ll,0),size*5+(floorArea-size)*2,'Area load total from one source');
  const overlap=LoadRegions83.clipSurface([{x0:1.5,x1:3,y0:0,y1:2}],m);LoadGroups.save(p,result,'F1',{...draft,hi:1,name:'Replacement',rects:overlap,ll:7},null);near(area(p.explorer.areas[1].flatMap(a=>a.rects)),size,'Replacement does not duplicate coverage');near(area(p.explorer.areas[2][0].rects),size,'Other floor unchanged');
  pieces=LoadRegions83.pieces(p,1,{rects:LoadRegions83.surface(m)},LoadRegions83.surfaceRegions(p,1,m));near(pieces.reduce((n,r)=>n+LoadRegions83.area(r)*r.load.ll,0),(size-3)*5+3*7+(floorArea-size)*2,'Overlap replaced once, remainder retained');
  const areaSnapshot=JSON.stringify(p.explorer.areas);p.types.F1.beams.push({id:'NEW',kind:'SB',a:{x:3,y:0},z:{x:3,y:2},b:200,d:350,on:true});result=Engine.generate(p);LoadData.reconcile(p,result,Loading.token);check(JSON.stringify(p.explorer.areas)===areaSnapshot,'Beam mesh change preserves coordinate region');
  const reopened=copy(p);Engine.generate(reopened);check(JSON.stringify(reopened.explorer.areas)===areaSnapshot,'Save/reopen preserves area');
  // Use one saved surface patch to change both slab load and beam-top load.
  const loaded=copy(fixtures.slab),loadedResult=Engine.generate(loaded),loadedModel=Engine.floorModel(loadedResult,1),patch=LoadRegions83.clipSurface([{x0:0,x1:3,y0:0,y1:4}],loadedModel),pa=area(patch);
  LoadGroups.save(loaded,loadedResult,'F1',{...draft,hi:1,rects:patch,selectionRects:undefined,sdl:1.5,ll:5},null);
  const calculated=Loading.run(loaded,loadedResult,'B'),beamRows=calculated.rows.filter(r=>['MB','SB','TB','CB'].includes(r.kind)),liveTotal=beamRows.reduce((n,r)=>n+r.actions.totalLive,0),expected=pa*5+(24-4*.25*.25-pa)*2;
  check(liveTotal>=expected-1e-7&&liveTotal-expected<.3,'Saved floor area reaches beams without missing beam-top Q');
  const originalBeams=Loading.run(copy(fixtures.slab),Engine.generate(fixtures.slab),'B').rows.filter(r=>['MB','SB','TB','CB'].includes(r.kind)),top=r=>r.loading.automaticLines.filter(l=>l.surface126).reduce((n,l)=>n+l.q*(l.end-l.start),0);check(beamRows.reduce((n,r)=>n+top(r),0)>originalBeams.reduce((n,r)=>n+top(r),0),'Saved region drives beam-top Q');
  const withVoid=copy(p);withVoid.types.F1.slabVoids=[{x0:0,x1:1,y0:0,y1:1}];const voidResult=Engine.generate(withVoid);check(LoadData.validate(withVoid,1,Engine.floorModel(voidResult,1).slabs.map(s=>Loading.token('SLAB',s)),Engine.floorModel(voidResult,1)).length>0,'Changed physical surface still requires reconciliation');
  // Existing panel regions can be edited without swallowing a whole changed panel.
  const legacy=copy(fixtures.slab),lr=Engine.generate(legacy),lm=Engine.floorModel(lr,1),a=LoadData.addArea(legacy,1);a.panels=[Loading.token('SLAB',lm.slabs[0])];a.ll=9;const expanded=LoadRegions83.clipSurface(LoadRegions83.surfaceRegions(legacy,1,lm)[0].rects,lm),legacyBefore=JSON.stringify(legacy);
  LoadGroups.overview(legacy,lr,1);check(JSON.stringify(legacy)===legacyBefore,'Viewing legacy load region is read-only');LoadGroups.removeRegion(legacy,lr,1,[{x0:0,x1:2,y0:0,y1:4}]);const kept=legacy.explorer.areas[1][0];near(area(kept.rects),area(LoadRegions83.difference(expanded,[{x0:0,x1:2,y0:0,y1:4}])),'Partial removal retains exact legacy footprint');check(kept.panels.length===0,'Edited legacy region uses coordinates');
  const rows=[{start:0,end:.3,g:0,q:1.51,dl:0,sdl:0,sw:0,surface126:true,label:'梁顶 SDL / LL',auto:true},{start:.3,end:.6,g:0,q:1.51,dl:0,sdl:0,sw:0,surface126:true,label:'梁顶 SDL / LL',auto:true},{start:.6,end:1.5,g:0,q:1.51,dl:0,sdl:0,sw:0,surface126:true,label:'梁顶 SDL / LL',auto:true},{start:1.5,end:2,g:0,q:.76,dl:0,sdl:0,sw:0,surface126:true,label:'梁顶 SDL / LL',auto:true}],before=JSON.stringify(rows),merged=BeamLoadUI.displayRows(rows);
  check(merged.length===2&&merged[0].end===1.5&&merged[0].merged129===3,'Equal adjacent beam tops merge; genuine intensity step retained');check(JSON.stringify(rows)===before,'Underlying segments remain unchanged');near(merged.reduce((n,r)=>n+r.q*(r.end-r.start),0),rows.reduce((n,r)=>n+r.q*(r.end-r.start),0),'Merged display conserves integrated load');
  check(BeamLoadUI.displayRows([rows[0],{...rows[0],start:.5,end:.8}]).length===2,'Gap is not bridged');check(BeamLoadUI.displayRows([rows[0],{...rows[1],q:1.5101}]).length===2,'Different exact loads do not merge after rounding');check(BeamLoadUI.displayRows([rows[0],{...rows[1],surface126:false}]).length===2,'Slab/manual sources not merged with beam tops');
  for(const [a,z,side,reverse]of [[[0,0],[4,0],'左端',false],[[4,0],[0,0],'左端',true],[[0,0],[0,4],'上端',false],[[0,4],[0,0],'上端',true]]){const o=BeamLoadUI.orientation({a,z});check(o.startSide===side&&o.reverse===reverse,'Plan direction mapped');}
  return {p,size,floorArea,legacy,rows};
 },fixtures);passed.push('Axis-bay click/drag/reverse/outside, full surface including beam tops, openings/columns, multi-floor region save, replace-overlap, exact legacy removal, re-meshing/reopen and lossless diagram merging');
 async function open(p){await page.locator('#file').setInputFiles({name:'area129.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});}
 await open({...checks.p,explorer:fixtures.slab.explorer});await page.evaluate(()=>{const old=Drawing.plan;Drawing.plan=(...a)=>{window.options129=a[5];return window.plot129=old(...a);};StudioHost.navigate('loading');});
 await page.waitForFunction(()=>window.plot129);const beforeUI=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('#load-beam-reference129').check();await page.waitForFunction(()=>options129.loadBeamReference);assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),beforeUI);assert.equal(await page.locator('#components input[data-kind="MB"]').isVisible(),false);await page.locator('#load-beam-reference129').uncheck();
 await page.locator('[data-ex="lg-new"]').click();await page.locator('#lg-scope').selectOption('area');await page.locator('#lg-name').fill('Selected grid');await page.locator('#lg-usage').selectOption('手动');await page.locator('#lg-sdl').fill('1.5');await page.locator('#lg-ll').fill('5');
 const canvas=page.locator('#canvas');async function drag(a,z){const points=await page.evaluate(({a,z})=>[a,z].map(q=>({x:plot129.ox+q[0]*plot129.scale,y:plot129.oy+q[1]*plot129.scale})),{a,z}),box=await canvas.boundingBox();await page.mouse.move(box.x+points[0].x,box.y+points[0].y);await page.mouse.down();await page.mouse.move(box.x+points[1].x,box.y+points[1].y,{steps:4});await page.mouse.up();}
 await drag([.5,.5],[.6,1.5]);assert.equal(await page.locator('#lg-area129').textContent(),checks.size.toFixed(2));await page.locator('[data-ex="lg-save"]').click();assert.equal(await page.evaluate(()=>StudioHost.get().p.explorer.areas[1][0].panels.length),0);assert.equal(await page.evaluate(()=>StudioHost.get().p.explorer.areas[1][0].rects.reduce((n,r)=>n+LoadRegions83.area(r),0)),checks.size);
 const saved=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),beforeUI,'One undo restores exact project');await open(JSON.parse(saved));await page.evaluate(()=>StudioHost.navigate('loading'));await page.locator('.lg-manage > summary').click();await page.locator('[data-ex="lg-edit"]').filter({hasText:'Selected grid'}).click();assert.equal(await page.locator('#lg-area129').textContent(),checks.size.toFixed(2));await page.screenshot({path:path.join(out,'loading-area129.png'),fullPage:true});
 await page.locator('[data-ex="lg-clear"]').click();assert.equal(await page.locator('#lg-area129').textContent(),'0.00');await drag([3.5,2.5],[5,3.5]);assert.equal(await page.locator('#lg-area129').textContent(),'0.00','Opening has no loaded area');await drag([.5,.5],[5,3]);assert.equal(await page.locator('#lg-area129').textContent(),checks.floorArea.toFixed(2));await page.locator('[data-ex="lg-remove-mode"]').click();await drag([.5,.5],[.6,1.5]);assert.equal(await page.locator('#lg-area129').textContent(),(checks.floorArea-checks.size).toFixed(2));await page.locator('[data-ex="lg-cancel"]').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),saved,'Cancel changes no saved inputs');passed.push('Actual UI: hidden beam/slab targeting, reference toggle is display-only, snap selection, area readout, save, one-step undo, reopen/edit, opening, remove and cancel');
 // Exercise both horizontal and vertical beams drawn in reverse, with the root
 // at physical left/top. Numerical reactions and stored input distances stay A/B.
 for(const vertical of [false,true]){const p=JSON.parse(JSON.stringify(fixtures.cb)),b=p.types.F1.beams[0];b.a=vertical?{x:0,y:4}:{x:4,y:0};b.z={x:0,y:0};p.explorer.members={};p.explorer.selected={};p.explorer.reportB={};const prepared=await page.evaluate(p=>{const r=Engine.generate(p),b=Engine.floorModel(r,1).beams[0],t=Loading.token(b.kind,b);p.explorer.members['1|'+t]={fixedEnd:'z',mode:'manual',beamLoadMode:'manual',beamSelfWeight:false,beamLoads:[{name:'Known partial',type:'line',a:1,b:3,dl:6,ll:2},{name:'Tip force',type:'point',a:0,dl:3,ll:1}]};return {p};},p);await open(prepared.p);await page.evaluate(()=>StudioHost.navigate('beams'));await page.waitForFunction(()=>window.plot129);const spot=await page.evaluate(()=>{const h=StudioHost.get(),b=Engine.floorModel(h.result,1).beams[0];return {x:plot129.ox+(b.a[0]+b.z[0])/2*plot129.scale,y:plot129.oy+(b.a[1]+b.z[1])/2*plot129.scale};});await canvas.click({position:spot});await page.locator('.bl-plot').waitFor();await page.waitForFunction(()=>document.querySelector('.bl-plot')?.dataset.startEnd==='B');const svg=await page.locator('.bl-plot').textContent();assert(svg.includes('B · '+(vertical?'上端':'左端')+' · 0.00 m'));assert(svg.includes('B: DL 15.00 / LL 5.00 kN'));assert(svg.includes('固定端 M: 69.60 kNm'));assert.equal(Number(await page.locator('.beam-section129 output').first().textContent()),300);assert.equal(await page.locator('.framing-defaults129').getAttribute('open'),null);
  const dims=await page.locator('.bl-plot').evaluate(el=>{const w=el.viewBox.baseVal.width,d=el.querySelector('.bl-length129').getAttribute('d'),a=d.match(/M([\d.]+),.*H([\d.]+)/);return {ratio:Math.abs(+a[2]-a[1])/(w-56),fixed:[...el.querySelectorAll('path')].find(p=>p.getAttribute('stroke-width')==='5')?.getAttribute('d')};});assert(Math.abs(dims.ratio-.5)<1e-8,'2 m patch has half the 4 m beam width');assert(dims.fixed.startsWith('M28,'),'Fixed support on physical left/top');await page.screenshot({path:path.join(out,vertical?'beam-vertical129.png':'beam-horizontal129.png'),fullPage:true});}
 passed.push('Reverse horizontal/vertical CB: actual section, 2/4 proportional load length, physical left/top fixed support, A/B reactions and root moment unchanged');
 await page.locator('.bl-plot').screenshot({path:path.join(out,'beam-load-plot129.png')});
 assert(!(await page.locator('.bl-plot').textContent()).includes('板厚'));
 await page.setViewportSize({width:1180,height:800});await page.locator('.bl-plot').screenshot({path:path.join(out,'beam-load-narrow129.png')});
 await page.evaluate(()=>StudioHost.navigate('loading'));assert(!(await page.locator('#side').textContent()).includes('块板'),'Loading legend uses surface area');
 assert.deepEqual(errors,[]);const report={passed,errors};fs.writeFileSync(path.join(out,'loading129.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
