// Synthetic, non-project regression cases. Run with loading115.cjs.
function loading115Tests(){
 const passed=[];function ok(v,n){if(!v)throw Error(n);passed.push(n);}function near(a,b,n){ok(Number.isFinite(a)&&Math.abs(a-b)<1e-7,n+': '+a+' = '+b);}
 const point=(x,y)=>({x,y}),col=(id,x,y)=>({id,x,y,b:250,d:250,on:true,status:'上下贯通'}),beam=(id,kind,a,z,b=250,d=350)=>({id,kind,a:point(...a),z:point(...z),b,d,on:true,...(kind==='CB'?{widthMode:'manual'}:{})});
 function project(total=1){const p={format:'framing-app',version:1,name:'Loading regression',total,axes:{x:[{id:'1',gap:0},{id:'2',gap:6}],y:[{id:'A',gap:0},{id:'B',gap:4}]},defaults:{cb:500,cd:500,gap:3000,direction:'自动',mb:250,sb:250,tb:600,tbd:1200,slab:200,wall:300},groups:[],types:{}};
  for(let f=1;f<=total;f++){const key='F'+f;p.types[key]={mode:'manual',cbColumnWidth171:true,autoBeams101:false,building:{'0,0':true},opening:{},columns:[],walls:[],beams:[],suppressed:[],beamDepth:350};p.groups.push({end:f===total?'顶层':f,h:3.5,type:key,sh:350,min:0,headroom:2.5,em:.5});LoadData.setFloor(p,f,{usage:'Dormitory',dl:10,sdl:0,ll:2});}return p;}
 for(const v of [0,6.121,6.12,.25*.35*24.5,.1+.2,.000001])near(BeamLoads.normalized({g:v,q:0}).g,v,'retain input precision '+v);
 const p=project(),t=p.types.F1;t.columns=[col('C1',0,0),col('C2',6,0),col('C3',0,4),col('C4',6,4)];t.beams=[beam('B1','MB',[0,0],[6,0]),beam('B2','MB',[0,4],[6,4]),beam('B3','MB',[0,0],[0,4]),beam('B4','MB',[6,0],[6,4])];
 let model=Engine.generate(p),floor=Engine.floorModel(model,1);ok(floor.slabs.length===1,'one slab generated');const slab=floor.slabs[0],net=LoadRegions83.netSelfWeight(slab,floor),netArea=net.reduce((n,r)=>n+LoadRegions83.area(r),0);near(netArea,5.5*3.5,'slab clear-face area');
 // The independent Area audit retains physical floor loads. Design reactions are tested in slab-transfer177.cjs.
 const out=Loading.run(p,model,'B',true),sr=out.rows.find(r=>r.kind==='SLAB');near(sr.loading.selfWeightNetArea,netArea,'solver uses net area');const br=out.rows.filter(r=>['MB','SB','TB'].includes(r.kind));ok(br.every(r=>Math.abs(r.loading.sw-3.0625)<1e-10),'full height beam weight');ok(br.every(r=>r.actions),'four valid beam actions');
 const transferredG=br.reduce((v,r)=>v+r.actions.totalDead-r.loading.selfWeight,0),transferredQ=br.reduce((v,r)=>v+r.actions.totalLive,0);near(transferredG,netArea*.2*24.5,'net slab weight conserved without rounding');near(transferredQ,(6*4-4*.25*.25)*2,'live load includes beam tops once and excludes columns');
 for(const r of br){near(r.actions.dead.left+r.actions.dead.right,r.actions.totalDead,'dead reactions '+r.id);near(r.actions.live.left+r.actions.live.right,r.actions.totalLive,'live reactions '+r.id);for(const l of r.loading.lines)near(BeamLoads.factored(l).g,1.4*l.g,'line factors full precision DL');}
 const partial=Loading.actions(6,2.15,0,[{x:2,g:10.01,q:3.34}],false,[{start:1,end:4,g:4.12,q:1.24}]);near(partial.dead.right,(2.15*18+10.01*2+4.12*3*2.5)/6,'partial load right reaction');near(partial.live.left+partial.live.right,3.34+1.24*3,'partial live reaction sum');
 const cb=project(),ct=cb.types.F1;ct.columns=[col('ROOT',0,0)];ct.beams=[beam('CB1','CB',[0,0],[4,0],300,600)];let cm=Engine.generate(cb),c=Engine.floorModel(cm,1).beams[0],token=Loading.token(c.kind,c);cb.explorer.members['1|'+token]={fixedEnd:'a',mode:'manual',beamLoadMode:'manual',beamSelfWeight:true,beamLoads:[{name:'Partial',type:'line',a:1,b:3,dl:6.121,ll:2.221},{name:'P1',type:'point',a:2,dl:3.331,ll:.331},{name:'P2',type:'point',a:4,dl:1.111,ll:1.111}]};cb.explorer.selected['1|'+token]=true;cb.explorer.reportB['1|'+token]=true;
 const cr=Loading.run(cb,cm,'B').rows.find(r=>r.token===token);near(cr.loading.sw,3.675,'CB full weight');near(cr.actions.dead.M,3.675*8+6.121*2*2+3.331*2+1.111*4,'CB partial-load root moment');const cbPlan=RCPlan.build(cb,'B');ok(cbPlan.issues.length===0,'native CB accepts partial and multiple point loads: '+JSON.stringify(cbPlan.issues));ok(cbPlan.batches[0].fullLoads[0].kind==='CB','native CB full-load schedule');
 const tc=project(3);tc.types.F1.columns=[col('L',0,0),col('R',6,0)];tc.types.F1.beams=[beam('TB1','TB',[0,0],[6,0],600,1200)];tc.types.F2.columns=[col('TC',3,0)];tc.types.F3.columns=[col('TC',3,0)];let tm=Engine.generate(tc),tc2=Engine.floorModel(tm,2).columns.find(c=>c.id==='TC'),tt=Loading.token('COL',tc2);const own=tc.explorer.members['2|'+tt]={sectionAAreaOverrides115:{2:10,3:12}};
 const tcArea=()=>Reports.columnA(tc,{floor:2,token:tt,id:'TC'},tm),tbPoint=()=>Loading.run(tc,tm,'B').rows.find(r=>r.member.id==='TB1').loading.points.find(p=>p.label.endsWith(' TC'));
 ok(tcArea().errors.length===0,'TC area valid');near(tcArea().rows.reduce((v,x)=>v+x.area,0),22,'TC two floor areas');near(tbPoint().g,220,'TC to TB uses confirmed DL');near(tbPoint().q,44,'TC to TB uses confirmed LL');own.sectionAAreaOverrides115[2]=20;near(tbPoint().g,320,'TC area edit updates TB');
 const left=Engine.floorModel(tm,1).columns.find(c=>c.id==='L'),leftA=Reports.columnA(tc,{floor:1,token:Loading.token('COL',left),id:'L'},tm);near(leftA.rows.filter(x=>x.lo===2).reduce((v,x)=>v+x.area,0),10,'lower column receives half overridden floor 2');near(leftA.rows.filter(x=>x.lo===3).reduce((v,x)=>v+x.area,0),6,'lower column receives half overridden floor 3');
 own.sectionAAreaOverrides115[2]=0;near(tbPoint().g,120,'zero area removes only selected floor');delete own.sectionAAreaOverrides115[2];near(tcArea().rows.filter(x=>x.lo===2).reduce((v,x)=>v+x.area,0),24,'restore automatic area');near(tbPoint().g,360,'restored area reaches TB');
 tc.explorer.selected['2|'+tt]=true;near(tbPoint().g,360,'TB load independent of Check selection');
 const upperToken=Loading.token('COL',Engine.floorModel(tm,3).columns[0]);tc.explorer.members['3|'+upperToken]={sectionAAreaOverrides115:{3:30}};near(tcArea().rows.filter(x=>x.lo===3).reduce((v,x)=>v+x.area,0),12,'lower explicit override supersedes upper once');delete own.sectionAAreaOverrides115[3];near(tcArea().rows.filter(x=>x.lo===3).reduce((v,x)=>v+x.area,0),30,'upper override propagates after lower restore');near(tbPoint().g,540,'upper override flows through TC to TB');
 const rz=Engine.clone(cb);rz.types.F1.columns=[col('ROOT',4,0)];rz.explorer.members['1|'+token].fixedEnd='z';const zr=Loading.run(rz,Engine.generate(rz),'B').rows.find(r=>r.token===token);near(zr.actions.dead.M,3.675*8+6.121*2*2+3.331*2,'CB fixed at B mirrors point locations');near(zr.actions.totalDead,cr.actions.totalDead,'CB reversal preserves total load');
 const invalid=Engine.clone(cb);invalid.types.F1.columns=[];const ir=Loading.run(invalid,Engine.generate(invalid),'B').rows.find(r=>r.token===token);ok(!ir.actions&&ir.result.status==='INPUT REQUIRED','manual loads cannot bypass missing physical support');
 const regional=Engine.clone(p),rm=Engine.generate(regional),rc=Engine.floorModel(rm,1).columns.find(c=>c.id==='C1'),rt=Loading.token('COL',rc),region=LoadData.addArea(regional,1);Object.assign(region,{name:'Higher DL',dl:20,ll:4,rects:[{x0:0,x1:1.5,y0:0,y1:4}]});regional.explorer.members['1|'+rt]={sectionAAreaOverrides115:{1:12}};const ra=Reports.columnA(regional,{floor:1,token:rt,id:'C1'},rm);ok(ra.errors.length===0,'regional manual area remains valid');near(ra.rows.reduce((v,x)=>v+x.area,0),12,'regional area total');near(ra.rows.reduce((v,x)=>v+x.area*x.dl,0),180,'regional DL proportions retained');near(ra.rows.reduce((v,x)=>v+x.area*x.ll,0),36,'regional LL proportions retained');
 const corner=Engine.clone(p);corner.types.F1.columns=corner.types.F1.columns.filter(c=>c.id!=='C1');corner.types.F1.walls=[{id:'W1',a:point(0,0),z:point(0,2),b:300,on:true},{id:'W2',a:point(0,0),z:point(2,0),b:300,on:true}];const wm=Engine.generate(corner),wb=Engine.floorModel(wm,1).beams.find(b=>b.id==='B1'),ws=Loading.supportSummary(corner,wm,1,wb)[0];ok(ws.text.includes('W1')&&ws.text.includes('W2')&&!ws.text.includes('待确认'),'connected wall group shown as a valid support');
 return {passed,projects:{slab:p,cb,tc},cbPlan};
}
