const path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url'),{chromium}=require('playwright'),fixture=require('./tributary187.cjs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage({viewport:{width:1311,height:884}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve(__dirname,'../../assets/index.html')).href);
 await page.locator('#file').setInputFiles({name:'measure.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture.p))});
 await page.evaluate(()=>{const old=Drawing.plan;Drawing.plan=(...args)=>window.measurePlot=old(...args);StudioHost.navigate('beams');});
 await page.waitForFunction(()=>window.measurePlot);
 const baseline=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));
 const click=async(x,y,offset=0)=>{const q=await page.evaluate(({x,y,offset})=>({x:measurePlot.ox+x*measurePlot.scale+offset,y:measurePlot.oy+y*measurePlot.scale+offset}),{x,y,offset});await page.locator('#canvas').click({position:q});await page.waitForTimeout(40);};
 const dims=()=>page.evaluate(()=>measurePlot.measurements189);
 await page.locator('#measure189').click();await page.waitForTimeout(200);
 await click(1,2,2);await click(9,2,-2);await click(5,1);let d=await dims();assert.equal(d.length,1);assert.equal(d[0].value,8,'endpoint/column centre snapping');
 await page.locator('#measure-mode189').selectOption('X');await click(1,2);await click(9,6);await click(5,7);d=await dims();assert.equal(d[1].value,8);
 await page.locator('#measure-mode189').selectOption('Y');await click(1,2);await click(9,6);await click(0.5,4);d=await dims();assert.equal(d[2].value,4);
 await page.locator('#measure-mode189').selectOption('aligned');await click(1,2);await click(9,6);await click(5,5);d=await dims();assert(Math.abs(d[3].value-Math.sqrt(80))<1e-9);
 if(process.env.UI_SCREENSHOT)await page.locator('#canvas').screenshot({path:process.env.UI_SCREENSHOT});
 await page.locator('#canvas').focus();await page.keyboard.press('Delete');await page.waitForTimeout(80);assert.equal((await dims()).length,3);
 await click(5,2);await page.keyboard.press('Escape');assert.equal(await page.locator('#measure189').getAttribute('aria-pressed'),'true');assert.equal((await dims()).length,3);
 await page.keyboard.press('Control+z');await page.waitForTimeout(60);assert.equal((await dims()).length,2);
 const before=await page.evaluate(()=>({x:measurePlot.ox,y:measurePlot.oy,scale:measurePlot.scale}));const rect=await page.locator('#canvas').boundingBox();
 await page.keyboard.down('Space');await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+30,rect.y+rect.height/2+20);await page.mouse.up();await page.keyboard.up('Space');await page.waitForTimeout(100);
 const moved=await page.evaluate(()=>({x:measurePlot.ox,y:measurePlot.oy}));assert(Math.abs(moved.x-before.x)>10,'space drag pans');assert.equal((await dims()).length,2);
 await page.mouse.wheel(0,-150);await page.waitForTimeout(100);assert((await page.evaluate(()=>measurePlot.scale))>before.scale);assert.equal((await dims())[0].value,8);
 await page.keyboard.press('Escape');await page.waitForTimeout(80);assert.equal(await page.locator('#measure189').getAttribute('aria-pressed'),'false');assert.equal((await dims()).length,2);
 await page.locator('#measure189').click();await page.waitForTimeout(200);await page.locator('#three').click();await page.waitForTimeout(80);assert.equal(await page.locator('#measure189').getAttribute('aria-pressed'),'false');assert(await page.locator('#measure189').isDisabled());
 await page.locator('#plan').click();await page.waitForTimeout(80);assert.equal((await dims()).length,2);
 await page.locator('#measure189').click();await page.waitForTimeout(200);await page.locator('#measure-clear189').click();await page.waitForTimeout(80);assert.equal((await dims()).length,0);
 assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),baseline,'measurement operations never mutate project');
 assert.deepEqual(errors,[]);console.log('PASS: snapped/aligned/X/Y dimensions, placement, Esc/Delete/undo isolation, pan/zoom, 3D guard, clear, no project mutations');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
