// Read-only solver checks plus the real beam load diagram, using synthetic projects.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../../assets'),out=path.resolve('tmp/e2122');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{try{const f=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\//,'')||'index.html');res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':'text/javascript');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const page=await browser.newPage({viewport:{width:1400,height:1100}}),errors=[],passed=[];page.on('pageerror',e=>errors.push(e.stack));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.StudioHost);await page.addScriptTag({content:fs.readFileSync(__dirname+'/loading115-browser.js','utf8')});
await page.evaluate(()=>{window.reaction122Fixture=Engine.clone(loading115Tests().projects.cb);const target=document.createElement('div');target.id='reaction122';target.style='position:absolute;top:0;left:0;background:white;padding:20px;width:750px;z-index:5000';document.body.append(target);});
let columnForce;
for(const scenario of ['column','wall','column-child','wall-child','wall-missing','wall-child-missing-load']){
 const expected=await page.evaluate(scenario=>{BeamLoadUI.clear();const p=Engine.clone(reaction122Fixture),t=p.types.F1;t.slabVoids=[{x0:0,x1:6,y0:0,y1:4}];p.explorer.members={};p.explorer.selected={};p.explorer.reportB={};if(scenario.startsWith('wall')){t.columns=[];t.walls=scenario==='wall-missing'?[]:[{id:'W1',a:{x:0,y:0},z:{x:0,y:2},b:300,on:true}];}if(scenario.includes('child'))t.beams.push({id:'CHILD',kind:'CB',a:{x:4,y:0},z:{x:4,y:2},b:300,d:600,on:true});const r=Engine.generate(p),m=Engine.floorModel(r,1),c=m.beams.find(b=>b.id==='CB1'),token=Loading.token(c.kind,c);if(scenario.includes('child')){const child=m.beams.find(b=>b.id==='CHILD');p.explorer.members['1|'+Loading.token(child.kind,child)]={fixedEnd:'a',supportA:token,mode:'manual',udlDead:scenario.endsWith('missing-load')?null:10,udlLive:2};}p.explorer.selected['1|'+token]=true;const before=JSON.stringify(p),row=Loading.run(p,r).rows.find(x=>x.floor===1&&x.token===token),h={p,result:r,floor:1,selected:{kind:c.kind,id:c.id,member:c,token},data:Loading.input(p,1,token)};window.reaction122Context=h;document.getElementById('reaction122').innerHTML=BeamLoadUI.render(h,row);return {before,actions:row.actions,status:row.result.status,fail:row.result.fail,errors:row.loadErrors,root:Loading.cbRoot(p,r,1,c).fixedEnd};},scenario);
 await page.waitForFunction(()=>document.querySelector('#reaction122 .bl-plot text')&&!document.querySelector('#reaction122 .bl-auto-note').textContent.includes('尚未更新'));
 const plot=await page.locator('#reaction122 .bl-plot').textContent(),note=await page.locator('#reaction122 .bl-auto-note').textContent();
 if(scenario.includes('missing')){assert(!expected.actions);assert(plot.includes('反力待确认'));assert(!plot.includes('A: DL'));passed.push(scenario+': unresolved physical support or incoming loads still blocks reactions');}
 else {assert(expected.actions);assert(plot.includes('A: DL '+expected.actions.totalDead.toFixed(2)+' / LL '+expected.actions.totalLive.toFixed(2)));assert(!plot.includes('反力待确认'));if(scenario.includes('child')){assert.equal(expected.status,'INPUT REQUIRED');assert(note.includes('构件验算待补')&&note.includes('CHILD'));assert(plot.includes('竖向荷载固定端 M:'));}else{if(scenario==='column')columnForce=expected.actions.totalDead;else assert.equal(expected.actions.totalDead,columnForce);assert(!note.includes('构件验算待补'));}passed.push(scenario+': known reactions are shown; design status and warnings retained');}
 assert.equal(await page.evaluate(()=>JSON.stringify(reaction122Context.p)),expected.before,'UI inspection does not modify the project');
 if(scenario==='wall-child'){await page.locator('#reaction122 [data-bl-calc]').click();await page.waitForFunction(()=>document.querySelector('#reaction122 [data-bl-calc]')?.disabled===false);assert((await page.locator('#reaction122 .bl-plot').textContent()).includes('A: DL '+expected.actions.totalDead.toFixed(2)));assert((await page.locator('#reaction122 .bl-auto-note').textContent()).includes('构件验算待补'));await page.screenshot({path:path.join(out,'wall-cantilever-reaction.png'),fullPage:true});}
}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'reaction122.json'),JSON.stringify({passed,errors},null,2));console.log(JSON.stringify({passed,errors}));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
