const path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url'),{chromium}=require('playwright'),fixture=require('./review193.cjs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const page=await browser.newPage({viewport:{width:1117,height:884}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../../assets/index.html')).href);await page.locator('#file').setInputFiles({name:'selection.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture.p))});
 await page.evaluate(()=>{const old=Drawing.plan;Drawing.plan=(...a)=>window.plot193=old(...a);StudioHost.navigate('review');});await page.waitForTimeout(120);assert.equal(await page.locator('#review-layout191 tbody tr').count(),0);
 const canvas=page.locator('#canvas'),clear=()=>page.locator('[data-review191="none"]').click(),click=async(x,y)=>{const q=await page.evaluate(({x,y})=>({x:plot193.ox+x*plot193.scale,y:plot193.oy+y*plot193.scale}),{x,y});await canvas.click({position:q});},box=async(x0,y0,x1,y1)=>{const q=await page.evaluate(({x0,y0,x1,y1})=>{const r=document.querySelector('#canvas').getBoundingClientRect();return [r.x+plot193.ox+x0*plot193.scale,r.y+plot193.oy+y0*plot193.scale,r.x+plot193.ox+x1*plot193.scale,r.y+plot193.oy+y1*plot193.scale];},{x0,y0,x1,y1});await page.mouse.move(q[0],q[1]);await page.mouse.down();await page.mouse.move(q[2],q[3],{steps:5});await page.mouse.up();await page.waitForTimeout(60);};
 await page.locator('#review-filter191').selectOption('COL');await click(1,2);assert.equal(await page.locator('#review-layout191 tbody tr').count(),1);assert(await page.locator('[data-review-select191="COL:C0"]').isChecked());
 await page.locator('#review-filter191').selectOption('MB');await click(3,2);assert.equal(await page.locator('#review-layout191 tbody tr').count(),2);assert(await page.locator('[data-review-select191="MB:B1"]').isChecked());
 const baseline=await page.evaluate(()=>JSON.stringify(StudioHost.get().result));await page.locator('#review-distance191').fill('0.5');await page.locator('[data-review191="right"]').click();await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>StudioHost.get().p.drawingOffsets191.F1['COL:C0'].dx),.5);assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().result)),baseline);
 const moved=await page.evaluate(()=>plot193.hits.find(h=>h.kind==='COL'&&h.id==='C0').r.x);assert.equal(moved,1.5);
 if(process.env.UI_SCREENSHOT){await page.waitForTimeout(5500);await page.screenshot({path:process.env.UI_SCREENSHOT});}
 await page.locator('[data-review-select191="MB:B1"]').click();assert.equal(await page.locator('#review-layout191 tbody tr').count(),1);assert.equal(await page.locator('[data-review-select191="MB:B1"]').count(),0);
 await page.locator('[data-review191="restore"]').click();await clear();await page.locator('#review-filter191').selectOption('ALL');
 await box(.9,1.9,9.1,2.1);assert.equal(await page.locator('#review-layout191 tbody tr').count(),0,'touching/crossing beam and column fragments are not selected');
 await box(.5,1.5,9.5,2.5);assert.equal(await page.locator('#review-layout191 tbody tr').count(),3,'fully enclosed B1 and two columns only');assert.equal(await page.locator('[data-review-select191="MB:V2"]').count(),0);
 await clear();await box(9.5,2.5,.5,1.5);assert.equal(await page.locator('#review-layout191 tbody tr').count(),3,'reverse drag also uses complete containment');
 await clear();await page.locator('#review-filter191').selectOption('COL');await box(.5,1.5,9.5,2.5);assert.equal(await page.locator('#review-layout191 tbody tr').count(),2,'column filter applies to canvas selection');await canvas.focus();await page.keyboard.press('Escape');assert.equal(await page.locator('#review-layout191 tbody tr').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS: selected-only table, column+beam selection and movement, uncheck removes row, full containment both drag directions, type filter, reset and Esc');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
