const path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url'),{chromium}=require('playwright'),fixture=require('./review192.cjs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const page=await browser.newPage({viewport:{width:1117,height:884}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../../assets/index.html')).href);
 const p=structuredClone(fixture.p);p.types.F1.beams.find(b=>b.id==='V2').kind='CB';p.types.F1.noColumnZones=[{x0:2,y0:3,x1:3,y1:4}];await page.locator('#file').setInputFiles({name:'cb-support.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});
 await page.evaluate(()=>{const old=Drawing.plan;Drawing.plan=(...a)=>{window.opt192=a[5];return old(...a);};const canvas=FramingSymbols98.canvas;FramingSymbols98.canvas=(ctx,shapes)=>{window.shapes192=shapes;return canvas(ctx,shapes);};StudioHost.navigate('review');});await page.waitForTimeout(100);
 const before=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));assert(!(await page.locator('#show-no-column').isChecked()));assert.equal(await page.evaluate(()=>opt192.showNoColumn),false);assert.equal(await page.evaluate(()=>opt192.cbSupports192),true);
 const nav=async tab=>{await page.evaluate(t=>StudioHost.navigate(t),tab);await page.waitForTimeout(70);};await nav('regions');assert(await page.locator('#show-no-column').isChecked());assert.equal(await page.evaluate(()=>opt192.showNoColumn),true);
 await nav('columns');assert(!(await page.locator('#show-no-column').isChecked()));await page.locator('#show-no-column').check();await page.waitForTimeout(60);assert.equal(await page.evaluate(()=>opt192.showNoColumn),true);
 await nav('beams');assert(!(await page.locator('#show-no-column').isChecked()));await nav('regions');assert(await page.locator('#show-no-column').isChecked());await nav('columns');assert(await page.locator('#show-no-column').isChecked(),'manual choice belongs to its page');await nav('review');assert(!(await page.locator('#show-no-column').isChecked()));
 assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),before);
 if(process.env.UI_SCREENSHOT){await page.waitForTimeout(5600);await page.screenshot({path:process.env.UI_SCREENSHOT});}
 assert.deepEqual(errors,[]);console.log('PASS: region-only initial visibility, per-page manual overrides, CB support face in review, unchanged project');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
