const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{context}=require('../../verification/integration143.cjs'),c=context(path.resolve(__dirname,'../..'));
const seed=fs.readFileSync(path.join(__dirname,'slab-bay178.cjs'),'utf8').split('const result=c.run(`')[1].split('`);')[0],p=c.run(seed).p;
const out=c.run(`(()=>{const p=Engine.clone(argument),near=(a,b,m)=>{if(Math.abs(a-b)>1e-8)throw Error(m+': '+a+' != '+b);},up=BeamLoads.up;
 near(up(1.005),1.01,'up not nearest');near(up(6.860000000000001),6.86,'floating tolerance');near(BeamLoads.surface({sw:4.9245,sdl:1.111,ll:5.003}).sw,6.90,'single complete self-weight equation');
 for(const f of [1,2])LoadData.setFloor(p,f,{dl:10,sdl:0,ll:7.5});const result=Engine.generate(p),m=Engine.floorModel(result,1),slab=m.slabs[0],sr=Loading.inspectSlab(p,result,1,Loading.token('SLAB',slab));near(sr.loading.factored183.sw,6.86,'displayed slab pressure');for(const r of sr.slabReactions){near(r.ug183,8.41,'reaction uses 6.86 then 2.45 / 2');near(r.uq183,14.70,'live reaction');near(up(r.ug183+r.uq183),23.11,'sum uses displayed components');}
 const all=Loading.run(p,result,'B'),sb=all.rows.find(r=>r.floor===1&&r.kind==='SB'&&r.member.d===.6),a=sb.actions;for(const l of sb.loading.lines.filter(l=>l.slabLoad179)){near(l.ug183,8.41,'slab factored value reused');near(l.uq183,14.7,'LL reused');}
 near(a.left,up(a.factoredDead.left+a.factoredLive.left),'beam displayed sum');for(const v of [a.left,a.right,a.M,a.V,a.factoredDead.left,a.factoredLive.left])near(v*100,Math.round(v*100),'two decimal output');
 const mb=all.rows.find(r=>r.floor===1&&r.kind==='MB'&&r.loading?.points?.some(pt=>pt.label===sb.id));if(!mb)throw Error('no receiver');const point=mb.loading.points.find(pt=>pt.label===sb.id);near(point.ug183,a.factoredDead.left,'SB rounded reaction transferred');near(point.uq183,a.factoredLive.left,'SB Q transferred');near(BeamLoads.factored(point).g,a.factoredDead.left,'no second factoring');
 const effect=Loading.actions(4.25,3.68,0,[],false,[{start:0,end:4.25,g:6.01,q:6.13,ug183:8.41,uq183:9.8},{start:0,end:4.25,g:6.01,q:6.13,ug183:8.41,uq183:9.8}],{});near(effect.left,88.36,'exact staged 4.25 m example');near(effect.factoredDead.left,46.71,'rounded G reaction');near(effect.factoredLive.left,41.65,'rounded Q reaction');
 const explicit={x:1.1,g:100,q:100,ug183:1.01,uq183:2.02},e=Loading.actions(3.3,0,0,[explicit],false,[],{});near(e.factoredDead.left,.68,'reuse small explicit ULS despite large characteristic');near(e.factoredLive.left,1.35,'point location preserved');
 const cb=Loading.actions(3.3,0,0,[explicit],true,[],{});near(cb.left,3.03,'cantilever rounded reaction');near(cb.M,3.35,'cantilever sum of rounded G/Q moments');
 const scaled=Loading.beamSpanLoads({ratio:2,automatic:4,value:8},[{start:0,end:4,g:6,q:7,ug183:8.41,uq183:9.81}],[]).lines[0];near(BeamLoads.factored(scaled).g,4.21,'rescaled design intensity rounded before use');
 Loading.init(p).selected['1|'+sb.token]=true;const checked=Loading.run(p,result,'B').rows.find(r=>r.floor===1&&r.token===sb.token);near(checked.result.inputs.G23,a.M,'RC receives rounded moment');near(checked.result.inputs.G24,a.V,'RC receives rounded shear');
 const unusual=Engine.clone(p);unusual.defaults.slab=201;for(const f of [1,2])LoadData.setFloor(unusual,f,{dl:10,sdl:.333,ll:5.003});const ur=Engine.generate(unusual),us=Engine.floorModel(ur,1).slabs[0],row=Loading.inspectSlab(unusual,ur,1,Loading.token('SLAB',us));near(row.loading.sw,4.93,'rounded pressure is stored');near(row.loading.factored183.sw,6.90,'factored self-weight uses complete density times thickness equation');near(row.loading.factored183.sdl,.48,'SDL stages');near(row.loading.factored183.ll,8.02,'LL stages');for(const reaction of row.slabReactions){near(reaction.ug183,9.05,'reaction uses displayed 6.90 SW plus 0.48 SDL');near(reaction.uq183,9.83,'reaction uses rounded LL');}
 const before=Reports.columnA(p,{floor:1,id:m.columns[0].id,token:Loading.token('COL',m.columns[0])},result);if(before.errors.length)throw Error('Area errors');return {p,L:sr.loading.L,slabReaction:sr.slabReactions[0],beamReaction:effect.left};})()`,p);
assert.equal(out.L,2.45);console.log('PASS: ceil-2dp stages, 23.11 kN/m displayed sum, 4.25m beam 88.36 kN, inherited factored reactions, concentrated/cantilever/manual-span cases, column Area path');
if(process.env.FIXTURE183)fs.writeFileSync(process.env.FIXTURE183,JSON.stringify(out.p));
