// Synthetic regression and actual UI exercise; never writes a user project.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../../assets'),out=path.resolve('tmp/e2121');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{try{const f=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\//,'')||'index.html');res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':'text/javascript');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const page=await browser.newPage({viewport:{width:1600,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.StudioHost);await page.addScriptTag({content:fs.readFileSync(__dirname+'/loading115-browser.js','utf8')});
const result=await page.evaluate(()=>{
 const passed=[],assert=(v,m)=>{if(!v)throw Error(m);},near=(a,b,m)=>assert(Math.abs(a-b)<1e-6,m+': '+a+' / '+b),copy=Engine.clone,fixtures=loading115Tests().projects;
 function panel(transpose=false){const p=copy(fixtures.slab),t=p.types.F1;p.name='Slab panel E2.121';t.columns.filter(c=>c.x===0).forEach(c=>c.b=c.d=1000);const b=t.beams.find(b=>b.id==='B3');b.b=1000;b.a.y=.5;if(transpose){[p.axes.x,p.axes.y]=[p.axes.y,p.axes.x];for(const c of t.columns)[c.x,c.y]=[c.y,c.x];for(const b of t.beams)for(const q of [b.a,b.z])[q.x,q.y]=[q.y,q.x];}let r=Engine.generate(p);BeamLayout116.setDirections(p,'F1',Engine.floorModel(r,1).slabs,transpose?'Y':'X');return p;}
 const p=panel();for(const transpose of [false,true]){const p=panel(transpose),r=Engine.generate(p),rows=Loading.run(p,r).rows,s=rows.find(r=>r.kind==='SLAB');assert(!s.loadErrors.length,'Column-faced slab resolves both axes');const snapshot=JSON.stringify(p),inspection=Loading.inspectSlab(p,r,1,s.token);assert(JSON.stringify(inspection.slabReactions)===JSON.stringify(s.slabReactions),'Scoped panel reactions match full building');assert(JSON.stringify(p)===snapshot,'Slab inspection leaves project unchanged');assert(s.slabReactions.some(e=>e.supportType==='COL'),'Column gets a direct slab segment');for(const side of ['A','B'])near(s.slabReactions.filter(e=>e.side===side).reduce((n,e)=>n+e.length,0),s.loading.width,'Complete edge owned once');near(rows.filter(r=>r.kind==='COL').reduce((n,r)=>n+r.loading.live,0),(6*4-2*1*1-2*.25*.25)*2,'Column/beam overlap routes Q including beam tops once to base');const reversed=copy(p);reversed.types.F1.beams.forEach(b=>[b.a,b.z]=[b.z,b.a]);const reverse=Loading.run(reversed,Engine.generate(reversed)).rows;near(reverse.filter(r=>r.kind==='COL').reduce((n,r)=>n+r.loading.live,0),(6*4-2*1*1-2*.25*.25)*2,'Reversed endpoints conserve Q');}
 passed.push('Column faces in both axes; overlap counted once; endpoint reversal and total reaction balance');
 for(const kind of ['gap','upper','duplicate']){const q=copy(p),t=q.types.F1;if(kind==='gap')t.columns=t.columns.filter(c=>c.id!=='C1');if(kind==='upper')t.columns.find(c=>c.id==='C1').status='上层柱';if(kind==='duplicate')t.columns.push({...t.columns.find(c=>c.id==='C1'),id:'COPY'});const r=Engine.generate(q),rows=Loading.run(q,r).rows;assert(rows.some(r=>r.loadErrors.some(e=>/支承|重叠|未完整/.test(e))),'Actual gaps and ambiguous columns stay pending '+kind);assert(!rows.find(r=>r.id==='B1').actions,'Bad support must block downstream beam '+kind);}
 passed.push('Real gaps, upper-only columns and ambiguous columns remain blocked');
 const short=copy(fixtures.slab),st=short.types.F1;st.columns=[{id:'L',x:0,y:0,b:300,d:300,on:true,status:'上下贯通'},{id:'R',x:1,y:0,b:300,d:300,on:true,status:'上下贯通'}];st.beams=[{id:'SHORT',kind:'SB',a:{x:0,y:0},z:{x:1,y:0},b:300,d:350,on:true}];let r=Engine.generate(short),b=Engine.floorModel(r,1).beams[0];near(b.d*1000,350,'Explicit short SB depth retained');near(Engine.floorModel(Engine.generate(copy(short)),1).beams[0].d*1000,350,'Depth survives reopen');const designed=SectionB.beam({kind:'SB',L:1,b:300,h:350,fcu:45,fire:2,M:.1295,V:.518,T:0});assert(!JSON.stringify(designed).includes('SB!G53'),'No G53 at actual depth');let message='';try{SectionB.beam({kind:'SB',L:1,b:300,h:100,fcu:45,fire:2,M:.1295,V:.518,T:0});}catch(e){message=e.message;}assert(message.includes('有效截面'),'Invalid shallow section diagnosed before formula');st.beams[0].d=null;assert(Engine.floorModel(Engine.generate(short),1).beams[0].d<.35,'Unspecified SB still uses automatic sizing');
 passed.push('Manual 350 mm short-beam depth, reopen, automatic fallback and invalid effective section validation');
 const base=copy(fixtures.tc);base.total=2;base.groups=base.groups.slice(0,2);base.groups[1].end='顶层';delete base.types.F3;for(const t of Object.values(base.types))t.slabVoids=[{x0:0,x1:6,y0:0,y1:4}];base.explorer.members={};base.explorer.selected={};let tr=Engine.generate(base),up=Engine.floorModel(tr,2).columns[0];base.explorer.members['2|'+Loading.token('COL',up)]={mode:'manual',dead:100,live:20};
 const sums=[];for(const displayed of [false,true]){const q=copy(base);if(displayed)q.types.F1.columns.push({...q.types.F2.columns[0],id:'TC_display',status:'上层柱'});const rr=Loading.run(q,Engine.generate(q)).rows,tb=rr.find(r=>r.id==='TB1');assert(tb.actions,'Transfer beam has actions '+JSON.stringify(tb.loadErrors));near(tb.loading.points.filter(v=>v.label.endsWith(' TC')).reduce((n,v)=>n+v.g,0),100,'Upper column counted once');sums.push(tb.actions.totalDead);assert(!rr.some(r=>r.floor===1&&r.id==='TC_display'),'Display-only column is not a sink');}near(sums[0],sums[1],'Upper display does not change forces');
 const offset=copy(base);offset.types.F2.columns[0].y=.2;const offsetR=Engine.generate(offset),offsetCol=Engine.floorModel(offsetR,2).columns[0];offset.explorer.members={['2|'+Loading.token('COL',offsetCol)]:{mode:'manual',dead:100,live:20}};const offsetRows=Loading.run(offset,offsetR).rows,offsetTB=offsetRows.find(r=>r.id==='TB1');assert(!offsetTB.actions,'Off-node TC remains unconfirmed even if its section overlaps the TB');assert(!offsetTB.loading.points.some(v=>v.label.endsWith(' TC')),'No offset point load fabricated from width');assert(offsetTB.loadErrors.some(e=>e.includes('未找到下层柱或唯一指定 TB')),'Potential receiving TB is blocked until node/support is resolved');
 const multi=copy(base);multi.types.F1.beams.push({...multi.types.F1.beams[0],id:'TB2'});const mr=Loading.run(multi,Engine.generate(multi));assert(mr.issues.some(x=>x.msg.includes('相接：TB1、TB2')),'Multiple TB landing requests explicit resolution');assert(mr.rows.filter(x=>x.kind==='TB').every(x=>!x.actions),'No double counted transfer across ambiguous TB');
 passed.push('Transfer column ignores upper display, routes G/Q once, ambiguous TBs remain pending');
 return {passed,fixture:fixtures.slab};
});
await page.locator('#file').setInputFiles({name:'slab-ui.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(result.fixture))});await page.evaluate(()=>{const old=Drawing.plan;Drawing.plan=(...a)=>window.plot121=old(...a);StudioHost.navigate('beams');});await page.getByRole('button',{name:'选择 / 删除',exact:true}).click();const spot=await page.evaluate(()=>{const s=Engine.floorModel(StudioHost.get().result,1).slabs[0];return {x:plot121.ox+(s.x0+s.x1)/2*plot121.scale,y:plot121.oy+(s.y0+s.y1)/2*plot121.scale};});await page.locator('#canvas').click({position:spot});await page.locator('.slab-panel121').waitFor();await page.waitForFunction(()=>document.querySelector('.slab-panel121')?.textContent.includes('主筋 T'));
assert(!(await page.locator('.slab-panel121').innerText()).includes('INPUT REQUIRED'));await page.locator('#sp-thickness121').fill('180');await page.locator('#sp-thickness121').press('Tab');await page.waitForFunction(()=>Engine.floorModel(StudioHost.get().result,1).slabs[0].thickness===180);await page.locator('[data-sp-dir="X"]').click();await page.waitForFunction(()=>Engine.floorModel(StudioHost.get().result,1).slabs[0].direction116==='X');await page.locator('[data-sp-fold="check"] summary').first().click();await page.locator('#ex-steel-mode').selectOption('MANUAL');await page.locator('#ex-slab-dia').selectOption('16');await page.locator('[data-ex="steel"]').click();await page.waitForFunction(()=>Object.values(StudioHost.get().p.explorer.members).some(o=>o.steel?.F35===16));assert(!Object.values(await page.evaluate(()=>StudioHost.get().p.explorer.selected)).some(Boolean),'Viewing does not select reports/checks');await page.screenshot({path:path.join(out,'slab-ui-app.png'),fullPage:true});await page.evaluate(()=>StudioHost.navigate('checks'));assert.equal(await page.locator('#ex-slab-dia').inputValue(),'16','Member Check sees the same reinforcement');assert.deepEqual(errors,[]);result.passed.push('Beam page selects slabs with slab fill hidden; automatic calculation, thickness, direction and shared steel edits; no report/check selection side effects');delete result.fixture;fs.writeFileSync(path.join(out,'slab121.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});



