const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=path.resolve('FramingStudio/assets'),out=path.resolve('tmp/e2131');fs.mkdirSync(out,{recursive:true});
const baseline=execFileSync('git',['show','ec5ca64d11db7b5754d82b4ec74ba605957944f7:FramingStudio/assets/index.html'],{maxBuffer:30*1024*1024});
const server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost').pathname;res.setHeader('Content-Type',url.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');if(url==='/baseline/'){res.end(baseline);return;}const f=path.resolve(root,'.'+(url==='/'?'/index.html':url));if(!f.startsWith(root+path.sep))throw Error();res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:1700,height:1100}}),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());const url='http://127.0.0.1:'+server.address().port;
 await page.goto(url);await page.waitForFunction(()=>window.StudioHost);for(const name of ['loading115-browser.js','slab131-browser.js'])await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,name),'utf8')});
 const results=await page.evaluate(()=>slab131Tests());console.log(JSON.stringify({core:results.passed}));fs.writeFileSync(path.join(out,'core131.json'),JSON.stringify(results,null,2));
 // The real 2015 project is evaluated from a copy, never opened/saved over its original file.
 const projectPath='output/HKIE_Calculation_Audit/2015_local_heights_E2128/HKIE_2015_Q3_LocalHeights_v2_E2.128.framing.json',project=fs.existsSync(projectPath)?JSON.parse(fs.readFileSync(projectPath,'utf8')):null;
 const metric=(p)=>{const r=Engine.generate(p);for(const f of r.floors)for(const m of Loading.members(p,r,f.n))p.explorer.selected[f.n+'|'+m.token]=m.kind!=='COL'||m.member.status!=='上层柱';const result=Loading.run(p,r),rows=result.rows;return {geometry:JSON.stringify(r),counts:rows.reduce((n,r)=>(n[r.result.status]=(n[r.result.status]||0)+1,n),{}),slab01:rows.filter(r=>r.floor===1&&r.id==='SL-01').map(r=>({loading:r.loading,status:r.result.status,errors:r.loadErrors})),byKind:rows.reduce((n,r)=>{const k=r.kind+' '+r.result.status;n[k]=(n[k]||0)+1;return n;},{}),localTB:rows.filter(r=>r.floor===4&&r.id==='TB_014').map(r=>({depth:r.member.d*1000,limit:LocalHeights96.beamAllowance(p,r.floor,r.member)}))};};
 if(project){const old=await browser.newPage();await old.goto(url+'/baseline/');await old.waitForFunction(()=>window.StudioHost);let before,after;if(process.env.SKIP_2015&&fs.existsSync(path.join(out,'model2015.json'))){({before,after}=JSON.parse(fs.readFileSync(path.join(out,'model2015.json'),'utf8')));}else{before=await old.evaluate(metric,project);after=await page.evaluate(metric,project);assert.equal(after.geometry,before.geometry,'Entire project geometry unchanged');delete before.geometry;delete after.geometry;}await old.close();fs.writeFileSync(path.join(out,'model2015.json'),JSON.stringify({before,after},null,2));console.log(JSON.stringify({model2015:{before,after}}));}
 async function open(p){await page.locator('#file').setInputFiles({name:'slab131.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await page.evaluate(()=>{const original=Drawing.plan;if(!window.plot131installed){Drawing.plan=(...args)=>window.plot131=original(...args);window.plot131installed=true;}StudioHost.navigate('beams');});await page.getByRole('button',{name:'选择 / 删除',exact:true}).click();}
 async function select(){const spot=await page.evaluate(()=>{const h=StudioHost.get(),s=Engine.floorModel(h.result,h.floor).slabs[0],r=s.rects[0];return {x:plot131.ox+(r.x0+r.x1)/2*plot131.scale,y:plot131.oy+(r.y0+r.y1)/2*plot131.scale};});await page.locator('#canvas').click({position:spot});await page.locator('#ex-slab-span131').waitFor();await page.waitForFunction(()=>document.querySelector('.slab-panel121 [data-sp-fold="check"]')?.textContent.includes('Section B'));}
 if(project){const localHeights=await page.evaluate(p=>{const r=Engine.generate(p);return r.floors.flatMap(f=>Engine.floorModel(r,f.n).beams.filter(b=>(b.displayId||b.id)==='TB_014'||b.id==='TB_014').map(b=>({floor:f.n,name:FloorLevels.name(p,f.n),framing:f.type,id:b.id,token:Loading.token(b.kind,b),depth:b.d*1000,limit:LocalHeights96.beamAllowance(p,f.n,b)})));},project);fs.writeFileSync(path.join(out,'local-heights131.json'),JSON.stringify(localHeights,null,2));console.log(JSON.stringify({localHeights}));const local=localHeights.find(b=>b.depth===3200&&b.limit===3200);assert(local,'2015 local TB has 3200 mm allowance');
 const heightProject=JSON.parse(JSON.stringify(project));heightProject.explorer.selected[local.floor+'|'+local.token]=true;await open(heightProject);await page.evaluate(f=>{StudioHost.viewFloor(f);StudioHost.navigate('checks');},local.floor);await page.evaluate(token=>{const b=[...document.querySelectorAll('[data-ex=choose]')].find(b=>b.dataset.token===token);if(!b)throw Error('TB selection unavailable');b.click();},local.token);assert(!(await page.locator('#side').textContent()).includes('小于梁深'),'No false global height warning');await page.evaluate(local=>StudioHost.transact(()=>{const h=StudioHost.get(),b=h.p.types[local.framing].beams.find(b=>b.id===local.id);b.d=3300;}),local);await page.evaluate(token=>{const b=[...document.querySelectorAll('[data-ex=choose]')].find(b=>b.dataset.token===token);if(!b)throw Error('TB selection unavailable');b.click();},local.token);assert((await page.locator('#side').textContent()).includes('3200 mm，小于梁深 3300 mm'),'Actual local height exceedance remains visible');results.passed.push('Actual 2015 TB_014 uses local 3200 mm allowance; a 3300 mm depth correctly warns');}
 await open(results.uiProject);await select();const start=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));assert.equal(await page.locator('#ex-slab-span131').inputValue(),'3.7');assert(await page.locator('#ex-slab-span131').getAttribute('readonly')!==null);
 await page.locator('#ex-slab-span-mode').selectOption('manual');await page.locator('#ex-slab-span131').fill('0');assert(await page.locator('[data-ex="slab-span-save131"]').isDisabled());assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),start);
 await page.locator('#ex-slab-span131').fill('4.137');await page.locator('#ex-slab-width131').fill('5.125');await page.evaluate(()=>StudioHost.navigate('beams'));assert.equal(await page.locator('#ex-slab-span131').inputValue(),'4.137','Unsaved span survives result refresh');assert.equal(await page.locator('#ex-slab-width131').inputValue(),'5.125');await page.locator('[data-ex="slab-span-save131"]').click();await page.waitForFunction(()=>document.querySelector('[data-sp-fold="check"]')?.textContent.includes('4.14'));const saved=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));const Ls=await page.evaluate(()=>{const h=StudioHost.get();return Loading.run(h.p,h.result).rows.filter(r=>r.kind==='SLAB').map(r=>r.loading.L);});assert.deepEqual(Ls,[4.137,4.137]);
 await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),start);await select();await open(JSON.parse(saved));await select();assert.equal(await page.locator('#ex-slab-span131').inputValue(),'4.137');
 await page.locator('[data-sp-dir="X"]').click();await page.waitForFunction(()=>document.querySelector('#ex-slab-span131')?.value==='4.137');assert.equal(await page.locator('#ex-slab-width131').inputValue(),'5.125');await page.locator('[data-ex="slab-span-auto131"]').click();assert.equal(await page.locator('#ex-slab-span131').inputValue(),'5.7');await page.locator('[data-ex="slab-span-save131"]').click();await page.waitForFunction(()=>document.querySelector('[data-sp-fold="check"]')?.textContent.includes('5.70'));
 results.passed.push('Actual UI: auto/manual L/B, invalid input, shared floors, X/Y, one-step undo, JSON reopen and auto restore');
 await page.locator('#ex-slab-span-mode').selectOption('manual');await page.locator('#ex-slab-span131').fill('3.125');await page.locator('[data-ex="slab-span-save131"]').click();await page.waitForFunction(()=>document.querySelector('[data-sp-fold="check"]')?.textContent.includes('3.13'));await page.locator('[data-sp-fold="check"] summary').first().click();await page.locator('.slab-span131').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'slab-span131.png')});await page.evaluate(()=>StudioHost.navigate('checks'));assert.equal(await page.locator('#ex-slab-span131').inputValue(),'3.125');
 const checkBefore=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.evaluate(()=>{const original=Loading.run;Loading.run=(...args)=>window.checkOutput131=original(...args);});await page.locator('#ex-slab-span131').fill('3.625');await page.locator('[data-ex="slab-span-save131"]').click();await page.waitForFunction(()=>window.checkOutput131?.rows.some(r=>r.kind==='SLAB'&&r.loading.L===3.625));const checkResult=await page.evaluate(()=>{const h=StudioHost.get(),out=window.checkOutput131;return {L:out.rows.filter(r=>r.kind==='SLAB').map(r=>r.loading.L),C2:out.rows.find(r=>r.floor===h.floor&&r.kind==='SLAB').result.inputs?.C2,reports:[h.p.explorer.reportA,h.p.explorer.reportB]};});assert.deepEqual(checkResult.L,[3.625,3.625]);assert.equal(checkResult.C2,3625);assert.deepEqual(checkResult.reports,[JSON.parse(checkBefore).explorer.reportA,JSON.parse(checkBefore).explorer.reportB]);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),checkBefore,'Member Check save is one undo step');
 results.passed.push('Member Check save executes selected slab Check with shared Span, preserves report choices and supports one-step undo');
 await open(results.pendingProject);await page.locator('.summary-issues131 summary').click();await page.locator('[data-ex="audit-run131"]').click();await page.waitForFunction(()=>document.querySelector('.summary-issues131')?.textContent.includes('已检查'));await page.locator('[data-audit-filter131="kind"]').selectOption('COL');assert((await page.locator('.summary-issues131').textContent()).includes('TRANSFER PENDING'));const link=page.locator('[data-ex="audit-locate131"]').first();const target=await link.getAttribute('data-token');await link.click();await page.locator('.column-panel123').waitFor();await page.waitForFunction(()=>document.querySelector('.column-panel123')?.getAttribute('aria-busy')==='false');assert((await page.locator('#side').textContent()).includes('柱受力'));await page.locator('.summary-issues131').screenshot({path:path.join(out,'issue-list131.png')});
 results.passed.push('Member Check shares saved slab L; real full-building issue list filters and locates column while preserving Area check');
 await page.setViewportSize({width:1180,height:820});await page.locator('.summary-issues131').screenshot({path:path.join(out,'issue-list-narrow131.png')});assert(await page.locator('.summary-issues131 table').evaluate(e=>e.scrollWidth<=e.parentElement.clientWidth+1),'Issue list fits narrow panel');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'slab131.json'),JSON.stringify({passed:results.passed,errors},null,2));console.log(JSON.stringify({passed:results.passed,errors}));
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
