// Slab design dimensions, physical transfer and independent Area paths.
function slab131Tests(){
 const fixture=loading115Tests().projects,copy=Engine.clone,passed=[],ok=(v,m)=>{if(!v)throw Error(m);},near=(a,b,m)=>ok(Number.isFinite(a)&&Math.abs(a-b)<1e-7,`${m}: ${a} / ${b}`);
 const model=p=>Engine.generate(p),run=p=>Loading.run(p,model(p),'B'),slab=(p,f=1)=>Loading.members(p,model(p),f).find(m=>m.kind==='SLAB');
 function set(p,L,width=null,selfWeight='span',f=1){const s=slab(p,f);Loading.saveFramingSupports(p,f,s.token,{slabSpan131:L===null?null:{L,width,selfWeight}},['slabSpan131']);p.explorer.selected[f+'|'+s.token]=true;return s.token;}
 const result=(p,f=1)=>run(p).rows.find(r=>r.floor===f&&r.kind==='SLAB'),sum=(row,k)=>row.slabReactions.reduce((n,r)=>n+r[k]*r.length,0),select=p=>{const s=slab(p);p.explorer.selected['1|'+s.token]=true;return s;};
 const corner=copy(fixture.slab);corner.types.F1.columns.forEach(c=>c.b=c.d=800);const physical=JSON.stringify(model(corner)),c=select(corner);
 ok(!c.member.rectangular,'Physical column notches retained');ok(SlabGeometry120.designRectangle(c.member,Engine.floorModel(model(corner),1)),'Boundary column cuts allow regular design panel');
 for(const dir of ['X','Y']){BeamLayout116.setDirections(corner,'F1',[c.member],dir);const row=result(corner);ok(row.result.inputs&&!row.loadErrors.length,'Notched panel check '+dir+': '+JSON.stringify(row.loadErrors));near(row.loading.L,(dir==='X'?5.5:3.5)+.2,'Controlling effective span '+dir);const expected=SectionB.slab({kind:'SLAB',id:row.id,L:row.loading.L,h:200,fcu:45,fire:2,dl:0,sdl:0,ll:2,dlIncludesSelfWeight:false});ok(JSON.stringify(row.result.values)===JSON.stringify(expected.values),'Original slab solver values '+dir);near(sum(row,'q'),row.member.area*2,'Notched physical Q retained');}
 passed.push('Column cut-outs preserve net polygon/area and automatically check both X/Y using controlling effective span');
 for(const kind of ['opening','edge','internalColumn','shortBeam']){const p=copy(fixture.slab),t=p.types.F1;if(kind==='opening')t.slabVoids=[{x0:2,x1:4,y0:1,y1:3}];if(kind==='edge')t.slabVoids=[{x0:0,x1:2,y0:1,y1:3}];if(kind==='internalColumn')t.columns.push({id:'ISLAND',x:3,y:2,b:600,d:600,on:true,status:'上下贯通'});if(kind==='shortBeam')t.beams.push({id:'SHORT',kind:'SB',a:{x:3,y:0},z:{x:3,y:3},b:250,d:350,on:true});const s=select(p);ok(!SlabGeometry120.designRectangle(s.member,Engine.floorModel(model(p),1)),kind+' not silently rectangular');ok(result(p).result.status==='INPUT REQUIRED',kind+' requires explicit design');}
 passed.push('Real openings, edge notches, internal column islands and stopped beams retain automatic warnings');
 const p=copy(fixture.slab);select(p);LoadData.setFloor(p,1,{dl:10,sdl:1.25,ll:3});const auto=result(p),geometry=JSON.stringify(model(p));
 for(const [L,B] of [[2.731,4.125],[5.371,6.127]]){set(p,L,B);const rr=result(p);ok(rr.result.inputs,'Manual check inputs exist');near(rr.loading.L,L,'Saved span');near(rr.result.inputs.C2,L*1000,'Excel solver manual C2');near(rr.loading.selfWeightArea,L*B,'Manual self-weight area');ok(JSON.stringify(model(p))===geometry,'Manual dimensions do not move framing');const target=L*B*4.9+rr.member.area*1.25,tol=rr.slabReactions.reduce((n,e)=>n+e.length*.010001,0);ok(sum(rr,'g')>=target-1e-7&&sum(rr,'g')-target<tol,'Manual self weight and SDL conserved');near(sum(rr,'q'),sum(auto,'q'),'LL area unchanged');for(const sec of ['A','B']){p.explorer['report'+sec]={'1|unused':false,['1|'+rr.token]:true};const plan=RCPlan.build(p,sec);ok(!plan.issues.length,'Native plan '+sec);near(plan.batches[0].cells.B34,L,'Native original L field');}
  set(p,L,B,'net');const net=result(p);ok(JSON.stringify(net.slabReactions)===JSON.stringify(auto.slabReactions),'Net-area mode preserves transfer exactly');
 }
 set(p,null);ok(JSON.stringify(result(p).loading)===JSON.stringify(auto.loading),'Automatic restore exact calculation');
 passed.push('Manual L/B updates original A/B Check inputs and self-weight; floor SDL/LL and geometry unchanged; net option and auto restore verified');
 const cs=copy(fixture.slab),st=slab(cs);for(const edge of ['left','right','top','bottom']){Loading.saveFramingSupports(cs,1,st.token,{slabType:'CS',csFixedEdge:edge},['slabType','csFixedEdge']);set(cs,2.137,3.125);const rr=result(cs);ok(rr.result.kind==='CS'&&rr.rootMoments.length,'CS check and root transfer '+edge);near(rr.result.inputs.C2,2137,'CS manual L');const target=2.137*3.125*4.9,tol=rr.slabReactions.reduce((n,e)=>n+e.length*.010001,0);ok(sum(rr,'g')>=target-1e-7&&sum(rr,'g')-target<tol,'CS total weight '+edge);ok(rr.slabReactions.every(r=>r.side===(['left','top'].includes(edge)?'A':'B')),'Only fixed edge receives load');}
 passed.push('Four cantilever fixed edges share the same manual span, top-steel calculation and actual root transfer');
 const pending=copy(fixture.slab);pending.types.F1.beams=pending.types.F1.beams.filter(b=>b.id!=='B2');let sr=select(pending);BeamLayout116.setDirections(pending,'F1',[sr.member],'Y');ok(result(pending).result.status==='INPUT REQUIRED','Missing auto support fails');set(pending,3.7,5.5);const manual=result(pending);ok(manual.result.inputs&&!manual.loadErrors.length,'Manual slab can check independently');ok(manual.transferErrors.some(s=>s.includes('支承边')),'Actual load path remains pending');ok(run(pending).rows.some(r=>r.kind==='MB'&&!r.actions),'Unresolved beam path not waived');pending.explorer.reportB={['1|'+manual.token]:true};ok(!RCPlan.build(pending,'B').issues.length,'Independent manual slab accepted by native check');
 passed.push('Manual fallback checks the slab without manufacturing support or suppressing downstream transfer errors');
 for(const value of [{L:0,width:1,selfWeight:'span'},{L:-1,width:1,selfWeight:'net'},{L:'4',width:1,selfWeight:'span'},{L:4,width:-1,selfWeight:'span'},{L:4,width:1,selfWeight:'bad'},[],7]){const q=copy(fixture.slab),s=select(q);Loading.saveFramingSupports(q,1,s.token,{slabSpan131:value},['slabSpan131']);const rr=result(q);ok(rr.loading.L===null&&rr.result.status==='INPUT REQUIRED','Bad imported override cannot fall back silently');q.explorer.reportA={['1|'+s.token]:true};ok(!RCPlan.build(q,'A').batches.length,'Invalid L not reported as valid');}
 const shared=copy(fixture.slab);shared.total=2;shared.groups[0].end='顶层';LoadData.setFloor(shared,2,LoadData.floor(shared,1));const t=set(shared,4.137);near(result(shared,2).loading.L,4.137,'Shared framing');shared.explorer.members['2|'+t].slabSpan131={L:5,width:null,selfWeight:'net'};ok(result(shared).loadErrors.some(s=>s.includes('冲突')),'Conflict blocked');set(shared,null);near(result(shared,2).loading.L,3.7,'Shared restore');
 passed.push('Invalid imported span/width/basis, shared-framing conflicts, automatic restore and save/reopen persistence');
 const columns=copy(pending),cr=model(columns);for(const col of Loading.members(columns,cr,1).filter(m=>m.kind==='COL'))columns.explorer.selected['1|'+col.token]=true;let rows=run(columns).rows.filter(r=>r.kind==='COL');ok(rows.some(r=>r.loading.transferErrors?.length),'Broken physical path retained separately');ok(rows.every(r=>r.result.inputs&&!r.loadErrors.length),'Area columns check despite upstream missing support');LoadData.setFloor(columns,1,{dl:null,sdl:0,ll:2});ok(run(columns).rows.filter(r=>r.kind==='COL').every(r=>r.result.status==='INPUT REQUIRED'),'Actual Area DL missing still blocks');
 const tc=copy(fixture.tc);tc.types.F1.slabVoids=[{x0:0,x1:6,y0:0,y1:4}];const tb=run(tc).rows.find(r=>r.id==='TB1');ok(tb.actions,'Valid Area TC reaches TB without upper slab errors: '+JSON.stringify(tb.loadErrors));ok(run(tc).rows.some(r=>r.floor>1&&r.kind==='SLAB'&&r.loadErrors.length),'Upper slab still incomplete');const point=tb.loading.points.find(r=>r.label.endsWith(' TC')),a=Reports.columnA(tc,{floor:2,token:Loading.token('COL',Engine.floorModel(model(tc),2).columns[0]),id:'TC'},model(tc));near(point.g,a.rows.reduce((n,x)=>n+x.area*x.count*(x.dl+x.sdl),0),'TC Area G');near(point.q,a.rows.reduce((n,x)=>n+x.area*x.count*x.ll,0),'TC Area Q');LoadData.setFloor(tc,3,{dl:null,sdl:0,ll:2});ok(!run(tc).rows.find(r=>r.id==='TB1').actions,'Invalid Area column load still blocks TB');
 passed.push('Area column checks and TC → TB loads ignore unrelated reaction errors but reject genuine Area input errors');
 const auditProject=copy(pending),before=JSON.stringify(auditProject),audit=Loading.audit(auditProject,model(auditProject));ok(JSON.stringify(auditProject)===before,'Full audit does not change selections/inputs');ok(audit.items.some(i=>i.path==='传荷'&&i.kind==='COL'),'Audit separates column load-path issue');ok(!audit.items.some(i=>i.path==='Check'&&i.kind==='COL'&&i.status==='INPUT REQUIRED'),'Audit column Check not polluted');ok(audit.items.every(i=>i.floor&&i.framing&&i.id&&i.reasons.length),'Actual issue identity available');
 passed.push('Full-building audit uses real results and separate Check/transfer states, preserves selections and links to real tokens');
 return {passed,uiProject:shared,manualProject:p,cornerProject:corner,pendingProject:pending,tcProject:tc};
}
