const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const{context}=require('../../verification/integration143.cjs'),c=context(path.resolve(__dirname,'../..'));
const result=c.run(`(()=>{const ok=(v,m)=>{if(!v)throw Error(m);},near=(a,b,m)=>ok(Math.abs(a-b)<1e-7,m+': '+a+' vs '+b),col=(id,x,y)=>({id,x,y,b:1500,d:1500,on:true,status:'上下贯通'}),p={format:'framing-app',version:1,name:'Centre bay178',total:2,axes:{x:[{id:'1',gap:0},{id:'2',gap:5.5}],y:[{id:'A',gap:0},{id:'B',gap:13.75}]},defaults:{cb:1500,cd:1500,gap:3000,direction:'X',mb:1500,sb:250,tb:600,tbd:1200,slab:200,wall:300},groups:[{end:1,h:5,type:'F1',sh:3000,min:0,headroom:1.5,em:.5},{end:'顶层',h:4,type:'F1',sh:2000,min:0,headroom:1.5,em:.5}],types:{F1:{mode:'manual',autoBeams101:true,building:{'0,0':true},opening:{},columns:[col('C1',0,0),col('C2',5.5,0),col('C3',0,13.75),col('C4',5.5,13.75)],walls:[],beams:[],suppressed:[],beamDepth:600}}};for(const f of [1,2])LoadData.setFloor(p,f,{dl:10,sdl:0,ll:7.5});
 let r=Engine.generate(p),m=Engine.floorModel(r,1);ok(m.slabs.length===5,'five panels');ok(m.beams.filter(b=>b.kind==='SB').length===4,'four SB');
 for(const s of m.slabs){near(Loading.slabSpan(s,'Y',m).effective,2.45,'equal centre spans');const d=Drawing.info(p,r,'F1',1,{kind:'SLAB',id:s.id,slabId:s.id});ok(d.rows.some(([label,value])=>label.includes('支承中心距')&&value==='4.000 × 2.450 m'),'dialog centre size');}
 const sorted=[...m.slabs].sort((a,b)=>a.y0-b.y0);near(sorted[0].y1-sorted[0].y0,1.575,'edge clear');near(sorted[1].y1-sorted[1].y0,2.2,'internal clear');for(const f of [1,2])for(const b of Engine.floorModel(r,f).beams)near(b.d,b.kind==='SB'?.6:f===1?3:2,'SB depth separated from floor');
 Engine.freezeAutoBeams(p,'F1',m);const raw=JSON.stringify(m.beams.map(b=>[b.id,b.a,b.z]));p.types.F1.beamDepth=800;r=Engine.generate(p);for(const f of [1,2])for(const b of Engine.floorModel(r,f).beams)near(b.d,b.kind==='SB'?.8:f===1?3:2,'snapshot SB update');ok(raw===JSON.stringify(Engine.floorModel(r,1).beams.map(b=>[b.id,b.a,b.z])),'depth leaves spacing intact');
 const drawn=p.types.F1.autoBeamSnapshot.secondary.shift();p.types.F1.beams.push({id:drawn.id,kind:'SB',a:{x:drawn.rawA[0],y:drawn.rawA[1]},z:{x:drawn.rawZ[0],y:drawn.rawZ[1]},b:250,d:null,on:true});r=Engine.generate(p);near(Engine.floorModel(r,1).beams.find(b=>b.id===drawn.id).d,.8,'drawn SB default');p.types.F1.beams[0].d=450;r=Engine.generate(p);near(Engine.floorModel(r,1).beams.find(b=>b.id===drawn.id).d,.45,'explicit SB depth retained');
 delete p.types.F1.beamDepth;r=Engine.generate(p);near(p.types.F1.beamDepth,600,'clear resets SB default');near(Engine.floorModel(r,1).beams.find(b=>b.kind==='MB').d,3,'reset leaves main depth');
 const out=Loading.run(p,r,'B'),sb=out.rows.filter(row=>row.floor===1&&row.kind==='SB');ok(sb.every(row=>row.actions&&row.loading.lines.some(line=>line.label.startsWith('SL-'))),'slab loads reach SB');const mb=out.rows.filter(row=>row.floor===1&&row.kind==='MB');ok(mb.some(row=>row.loading.points.some(pt=>sb.some(s=>s.id===pt.label))),'SB reactions reach main beams');
 const cm=Engine.floorModel(r,1).columns[0],token=Loading.token('COL',cm),area=Reports.columnA(p,{floor:1,id:cm.id,token},r);ok(!area.errors.length,'column tributary Area path valid');return {p,passed:['2.45 m equal bays with different beam widths; 1.575/2.200 net spans explain screenshot','Dialog shows 4.000 × 2.450 m for both edge and internal slabs','SB default works for automatic, frozen and drawn beams; explicit overrides retained','MB follows different floor Structural Zones independently of SB setting','Spacing unchanged by depth edits and save/reopen','Slab line loads reach SB; SB reactions reach primary beams; column Area path retained']};})()`);
console.log(result.passed.join('\n'));
if(process.env.FIXTURE178)fs.writeFileSync(process.env.FIXTURE178,JSON.stringify(result.p));
