const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=path.resolve('FramingStudio/assets'),out=path.resolve('tmp/e2130');fs.mkdirSync(out,{recursive:true});
const baseline=execFileSync('git',['show','d2877c6a43110faa893e7d7bf7054154dfbd91e5:FramingStudio/assets/index.html'],{maxBuffer:30*1024*1024});
const server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost').pathname;if(url==='/baseline/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(baseline);return;}const file=path.resolve(root,'.'+(url==='/'?'/index.html':url));if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':'text/javascript');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:1700,height:1080}}),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());const url='http://127.0.0.1:'+server.address().port;
 await page.goto(url);await page.waitForFunction(()=>window.StudioHost);for(const name of ['loading115-browser.js','span130-browser.js'])await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,name),'utf8')});const result=await page.evaluate(()=>span130Tests());
 const old=await browser.newPage();await old.goto(url+'/baseline/');await old.waitForFunction(()=>window.StudioHost);const calc=(pg,p)=>pg.evaluate(p=>{const r=Engine.generate(p);return JSON.stringify({geometry:r,loads:Loading.run(p,r,'B'),a:RCPlan.build(p,'A'),b:RCPlan.build(p,'B')});},p);
 for(const p of Object.values(result.fixtures))assert.equal(await calc(page,p),await calc(old,p));await old.close();result.passed.push('Existing E2.129 geometry, load calculation and native A/B jobs exactly unchanged without manual span');
 async function open(p){await page.locator('#file').setInputFiles({name:'span130.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await page.evaluate(()=>StudioHost.navigate('beams'));await page.getByRole('button',{name:'选择 / 删除',exact:true}).click();}
 await page.evaluate(()=>{const original=Drawing.plan;Drawing.plan=(...args)=>window.plot130=original(...args);});
 async function select(id='B2'){const point=await page.evaluate(id=>{const h=StudioHost.get(),b=Engine.floorModel(h.result,h.floor).beams.find(b=>b.id===id);return {x:plot130.ox+(b.a[0]+b.z[0])/2*plot130.scale,y:plot130.oy+(b.a[1]+b.z[1])/2*plot130.scale};},id);await page.locator('#canvas').click({position:point});try{await page.locator('#ex-beam-span').waitFor({timeout:3000});}catch(e){await page.screenshot({path:path.join(out,'selection-error.png')});console.log(JSON.stringify({point,side:await page.locator('#side').textContent(),errors}));throw e;}}
 await open(result.uiProject);await select();const before=await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),automatic=await page.locator('#ex-beam-span').inputValue();assert.equal(automatic,'6.000');assert(await page.locator('[data-ex="beam-span-auto130"]').isDisabled());
 await page.locator('#ex-beam-span').fill('0');assert(await page.locator('[data-ex="beam-support-save117"]').isDisabled());assert(await page.locator('[data-beam-span-error]').isVisible());assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),before);
 await page.locator('#ex-beam-span').fill('7.319');await page.locator('[data-ex="beam-support-save117"]').click();await page.waitForFunction(()=>document.querySelector('.bl-plot')?.dataset.diagramLength==='7.319');
 const saved=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));assert.notEqual(saved,before);const lengths=await page.evaluate(()=>{const h=StudioHost.get();return Loading.run(h.p,h.result,'B').rows.filter(r=>r.member.id==='B2').map(r=>r.loading.L);});assert.deepEqual(lengths,[7.319,7.319]);assert.equal(await page.locator('.beam-support-span130').getAttribute('data-mode'),'manual');
 await page.waitForFunction(()=>document.querySelector('.bl-plot')?.textContent.includes('ULS:'));const figure=await page.locator('.bl-plot').textContent(),expected=await page.evaluate(()=>{const h=StudioHost.get(),r=Loading.run(h.p,h.result,'B').rows.find(r=>r.member.id==='B2'&&r.floor===h.floor);return `A: DL ${r.actions.dead.left.toFixed(2)} / LL ${r.actions.live.left.toFixed(2)} kN`;});assert(figure.includes(expected),'UI reactions equal solver (no second rounding of mapped line loads)');
 await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),before);await select();assert.equal(await page.locator('#ex-beam-span').inputValue(),automatic);await open(JSON.parse(saved));await select();assert.equal(await page.locator('#ex-beam-span').inputValue(),'7.319');
 await page.locator('[data-ex="beam-span-auto130"]').click();assert.equal(await page.locator('#ex-beam-span').inputValue(),automatic);assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),saved,'Restore awaits normal Save Support');await page.locator('[data-ex="beam-support-save117"]').click();assert.equal(await page.locator('#ex-beam-span').inputValue(),automatic);await page.waitForFunction(()=>document.querySelector('.bl-plot')?.dataset.diagramLength==='6');
 result.passed.push('Actual Support UI: invalid input, save/shared floors, chart and reaction update, one-step undo, JSON reopen and restore automatic');
 // Editing support span preserves pending load drafts, and an out-of-range patch suppresses reactions.
 await page.locator('[data-bl-mode="extra"]').click();await page.locator('[data-bl-add]').click();await page.locator('[data-bl-field="b"]').fill('5.5');await page.locator('[data-bl-field="dl"]').fill('2');await page.locator('[data-bl-field="ll"]').fill('1');await page.locator('#ex-beam-span').fill('3.731');await page.locator('[data-ex="beam-support-save117"]').click();assert.equal(await page.locator('[data-bl-field="b"]').inputValue(),'5.50');await page.waitForFunction(()=>document.querySelector('.bl-error')?.textContent.includes('位置须在'));assert(!(await page.locator('.bl-plot').textContent()).includes('ULS:'));
 const blocked=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('[data-ex="beam-loading-save117"]').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),blocked,'Invalid load not saved');await page.locator('[data-bl-field="b"]').fill('3.5');await page.locator('[data-ex="beam-loading-save117"]').click();try{await page.waitForFunction(()=>document.querySelector('.bl-plot')?.textContent.includes('ULS:'));}catch(e){console.log(await page.locator('.beam-load-editor').textContent());console.log(await page.evaluate(()=>JSON.stringify(StudioHost.get().p.explorer.members)));throw e;}
 result.passed.push('Unsaved load drafts survive span changes; out-of-range manual/extra positions block results and save until corrected');
 await page.locator('.beam-support-step117').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'span-support130.png'),fullPage:true});await page.setViewportSize({width:1180,height:820});await page.locator('.beam-support-step117').screenshot({path:path.join(out,'span-support-narrow130.png')});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'span130.json'),JSON.stringify({passed:result.passed,errors},null,2));fs.writeFileSync(path.join(out,'native-case130.json'),JSON.stringify(await page.evaluate(p=>RCPlan.build(p,'B'),result.manualProject),null,2));console.log(JSON.stringify({passed:result.passed,errors}));
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
