// Summary Check UI and calculation parity using synthetic projects only.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'../../assets'),out=path.resolve('tmp/e2123');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{try{const f=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\//,'')||'index.html');res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':'text/javascript');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:1640,height:1150}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.StudioHost);await page.addScriptTag({content:fs.readFileSync(__dirname+'/loading115-browser.js','utf8')});
 const verified=await page.evaluate(()=>{
  const fixtures=loading115Tests().projects,passed=[],copy=Engine.clone,assert=(v,m)=>{if(!v)throw Error(m);},near=(a,b,m)=>assert(Math.abs(a-b)<1e-7,m+': '+a+' / '+b);
  const base=copy(fixtures.slab);base.name='Summary Check · Column';base.total=3;base.groups=[{...base.groups[0],end:'顶层'}];for(let f=1;f<=3;f++)LoadData.setFloor(base,f,{usage:'Dormitory',dl:9+f,sdl:.5,ll:2});
  function inspect(p,f=1,id='C1'){
   const result=Engine.generate(p),selected=Loading.members(p,result,f).find(m=>m.id===id&&m.kind==='COL'),h={p,result,floor:f,key:result.floors[f-1].type,selected,data:Loading.input(p,f,selected.token)},before=JSON.stringify(p),actual=ColumnPanel123.inspect(h),check=copy(p);check.explorer.selected={...check.explorer.selected,[f+'|'+selected.token]:true};
   const expected=Loading.run(check,result).rows.find(r=>r.floor===f&&r.token===selected.token);assert(JSON.stringify(actual.row.result)===JSON.stringify(expected.result),'Same result as Member Check');assert(JSON.stringify(p)===before,'Inspection does not edit inputs or Check/A/B selections');
   if(!actual.schedule.errors.length){near(actual.schedule.totalG,expected.loading.dead,'Same column G');near(actual.schedule.totalQ,expected.loading.live,'Same column Q');}return {h,...actual};
  }
  const a=inspect(base),own=a.schedule.rows[0];near(a.schedule.totalG,a.schedule.rows.reduce((n,r)=>n+r.G,0),'G sums over floors');near(own.upperG,a.schedule.rows.slice(1).reduce((n,r)=>n+r.G,0),'Upper excludes current floor');near(own.totalG,own.G+own.upperG,'Current plus upper');assert(Object.hasOwn(a.row.result.inputs,'C28'),'Axial check available');near(a.row.result.inputs.C28,(1.4*a.schedule.totalG+1.6*a.schedule.totalQ)*Loading.settings(base).columnProject,'Original project factor applied');passed.push('Three-floor G/Q, current/upper totals, original factor and Member Check parity');
  const overridden=copy(base);overridden.explorer.members['1|'+a.h.selected.token]={sectionAAreaOverrides115:{2:12}};const ov=inspect(overridden);near(ov.schedule.rows.find(r=>r.floor===2).area,12,'Saved manual area reused');assert(ov.schedule.totalG>a.schedule.totalG,'Area updates cumulative G');passed.push('Saved per-floor area override is reused without duplicated input');
  const missing=copy(base);missing.explorer.floors[2].dl=null;const bad=inspect(missing);assert(bad.row.result.status==='INPUT REQUIRED','Missing Loading stays pending');assert(bad.schedule.totalG===null&&bad.schedule.totalQ===null,'Incomplete totals are not fabricated');
  const unsupported=copy(base);unsupported.types.F1.columns=unsupported.types.F1.columns.filter(c=>c.id!=='C2');const gap=inspect(unsupported);assert(gap.row.result.status==='INPUT REQUIRED','Unresolved transfer stays pending');passed.push('Missing loads and unresolved support do not display a passing check');
  inspect(copy(fixtures.tc),2,'TC');passed.push('Transfer column result and shared area schedule match existing Member Check');
  window.summary123Fixture=base;window.summary123Expected={G:a.schedule.totalG,Q:a.schedule.totalQ,N:a.row.result.inputs.C28};
  return {passed,fixture:base,expected:window.summary123Expected};
 });
 await page.locator('#file').setInputFiles({name:'summary-ui.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(verified.fixture))});
 await page.evaluate(()=>{const old=Drawing.plan;Drawing.plan=(...a)=>{window.summary123Options=a[5];return window.summary123Plot=old(...a);};StudioHost.navigate('beams');});
 await page.getByRole('button',{name:'选择 / 删除',exact:true}).click();
 async function select(kind,id){await page.waitForFunction(()=>window.summary123Plot);const spot=await page.evaluate(({kind,id})=>{const h=StudioHost.get(),m=Loading.members(h.p,h.result,h.floor).find(m=>m.kind===kind&&(!id||m.id===id)),c=m.member,pos=kind==='COL'?[Engine.columnRect(c).x,Engine.columnRect(c).y]:kind==='SLAB'?[(c.x0+c.x1)/2,(c.y0+c.y1)/2]:[(c.a[0]+c.z[0])/2,(c.a[1]+c.z[1])/2];return {x:summary123Plot.ox+pos[0]*summary123Plot.scale,y:summary123Plot.oy+pos[1]*summary123Plot.scale};},{kind,id});await page.locator('#canvas').click({position:spot});}
 const menu=await page.locator('#nav [data-tab]').evaluateAll(bs=>bs.map(b=>[b.dataset.tab,b.textContent.trim()]));const index=menu.findIndex(b=>b[0]==='beams');assert(menu[index][1].includes('Summary Check'));assert.equal(menu[index-1][0],'loading');assert.equal(menu[index+1][0],'checks');
 const saved=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await select('COL','C1');await page.waitForFunction(()=>document.querySelector('.column-panel123')?.getAttribute('aria-busy')==='false');
 assert((await page.locator('.cp-total').textContent()).includes(verified.expected.N.toFixed(2)));assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),saved);assert.equal(await page.locator('[data-cp-fold="geometry"], [data-cp-fold="check"]').count(),0);assert((await page.locator('.cp-current').textContent()).includes('63.00'));
 assert.equal(await page.evaluate(()=>summary123Plot.columnAreaBadge?.area),6,'Plan labels the same current-floor area used for G/Q');assert.equal(await page.evaluate(()=>summary123Options.columnLoadArea?.id),'C1');assert.equal(await page.evaluate(()=>summary123Plot.columnAreaBadge?.overlayOverlap),0,'Area label does not cover plan controls');assert(!(await page.locator('.column-panel123').textContent()).includes('各荷载区域'),'Redundant load-region table removed');
 await page.locator('[data-cp-fold="schedule"] > summary').click();assert.equal(await page.locator('.column-panel123 > details[data-cp-fold="schedule"] > .cp-content > .table-wrap > table > tbody > tr').count(),3);
 await page.locator('[data-cp-fold="schedule"] > summary').click();await page.screenshot({path:path.join(out,'summary-column-app.png'),fullPage:true});
 const columnToken=await page.evaluate(()=>Loading.members(StudioHost.get().p,StudioHost.get().result,1).find(m=>m.kind==='COL'&&m.id==='C1').token);
 await page.evaluate(token=>StudioHost.transact(()=>{const p=StudioHost.get().p,k='1|'+token;p.explorer.members[k]={...(p.explorer.members[k]||{}),sectionAAreaOverrides115:{1:12}};}),columnToken);await page.waitForFunction(()=>document.querySelector('.column-panel123')?.getAttribute('aria-busy')==='false');assert.equal(await page.evaluate(()=>summary123Plot.columnAreaBadge?.area),12,'Saved manual area shown on plan');assert((await page.locator('.cp-current').textContent()).includes('126.00'),'Manual area and displayed G use the same schedule');
 await page.evaluate(token=>StudioHost.transact(()=>{delete StudioHost.get().p.explorer.members['1|'+token].sectionAAreaOverrides115;}),columnToken);await page.waitForFunction(()=>document.querySelector('.column-panel123')?.getAttribute('aria-busy')==='false');assert.equal(await page.evaluate(()=>summary123Plot.columnAreaBadge?.area),6,'Automatic area restored');
 await page.evaluate(()=>StudioHost.transact(()=>LoadData.setFloor(StudioHost.get().p,3,{usage:'Dormitory',dl:15,sdl:.5,ll:2})));await page.waitForFunction(()=>document.querySelector('.column-panel123')?.getAttribute('aria-busy')==='false');assert(!(await page.locator('.cp-total').textContent()).includes('= '+verified.expected.N.toFixed(2)+' kN'),'Loading edit refreshes displayed axial force');
 await page.locator('[data-cp-member]').click();assert.equal(await page.locator('#nav [data-tab="checks"]').getAttribute('aria-pressed'),'true');assert((await page.locator('#side').textContent()).includes('C1'));await page.evaluate(()=>StudioHost.navigate('beams'));await select('SLAB');await page.waitForFunction(()=>document.querySelector('.slab-panel121')?.textContent.includes('主筋 T'));assert.equal(await page.locator('.column-panel123').count(),0);assert.equal(await page.evaluate(()=>summary123Options.columnLoadArea),null,'Slab selection clears column area');
 await select('MB','B1');await page.locator('.bl-plot').waitFor();assert.equal(await page.locator('.slab-panel121').count(),0);await select('COL','C2');await page.waitForFunction(()=>document.querySelector('.column-panel123')?.getAttribute('aria-busy')==='false');assert((await page.locator('.column-panel123 h3').textContent()).includes('C2'));
 await page.evaluate(()=>{const h=StudioHost.get();StudioHost.transact(()=>h.p.types.F1.columns.find(c=>c.id==='C2').status='上层柱');});assert((await page.locator('.column-panel123').textContent()).includes('上层柱的投影'));assert.equal(await page.locator('[data-cp-status]').count(),0);await page.waitForFunction(()=>summary123Options.columnLoadArea===null);assert.equal(await page.evaluate(()=>summary123Options.columnLoadArea),null,'Upper-only column has no current-floor tributary area');
 assert(!Object.values(await page.evaluate(()=>StudioHost.get().p.explorer.selected)).some(Boolean),'Viewing never selects a Check/report');assert.deepEqual(errors,[]);
 verified.passed.push('Actual app navigation, column picking, current-floor highlight, no duplicate geometry/check blocks, floor table, live refresh, Member Check shortcut, beam/slab switching and upper-only column state');delete verified.fixture;fs.writeFileSync(path.join(out,'summary123.json'),JSON.stringify({...verified,errors},null,2));console.log(JSON.stringify({...verified,errors}));
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
