// Shared node locations, actual slab edges, manual support persistence and responsive audit.
const fs=require('fs'),path=require('path'),assert=require('assert'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const out=path.resolve('tmp/e2132'),root=path.resolve('FramingStudio/assets');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage({viewport:{width:1600,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());await page.goto(pathToFileURL(root+'/index.html').href);await page.waitForFunction(()=>window.StudioHost);for(const name of ['loading115-browser.js','slab131-browser.js'])await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,name),'utf8')});
 const core=await page.evaluate(async()=>{
  const legacy=slab131Tests(),p=legacy.uiProject,passed=[...legacy.passed],ok=(v,m)=>{if(!v)throw Error(m);},near=(a,b,m)=>ok(Math.abs(a-b)<1e-7,m+': '+a+' / '+b),r=Engine.generate(p),model=Engine.floorModel(r,1),c=model.slabs[0],token=Loading.token('SLAB',c),dir=Loading.slabDirection(p,1,token,c),o=Loading.input(p,1,token),base=SlabSupport132.plan(c,dir,model,o);
  ok(base.rows.length&&!base.errors.length,'Actual boundaries complete');const values=base.rows.map(e=>({side:e.side,face:e.face,start:e.start,end:e.end,target:e.value})),save={direction:dir,segments:values},automatic=Loading.inspectSlab(p,r,1,token);Loading.saveFramingSupports(p,1,token,{slabSupports132:save},['slabSupports132']);const manual=Loading.inspectSlab(p,r,1,token);ok(!manual.transferErrors.length,'Saved physical segment targets accepted');near(manual.slabReactions.reduce((v,x)=>v+x.q*x.length,0),automatic.slabReactions.reduce((v,x)=>v+x.q*x.length,0),'Manual preserves total Q');ok(JSON.stringify(Loading.input(p,2,token).slabSupports132)===JSON.stringify(save),'Same framing shares supports');
  for(const bad of [{direction:dir==='X'?'Y':'X',segments:values},{direction:dir,segments:[...values,values[0]]},{direction:dir,segments:[{...values[0],target:'MB|not-found'}]},{direction:dir,segments:[{...values[0],start:values[0].start-3}]},{direction:dir,segments:7},{direction:dir,segments:[null]},7]){const plan=SlabSupport132.plan(c,dir,model,{...o,slabSupports132:bad});ok(plan.errors.length,'Malformed/stale/manual ambiguity stays pending');}
  const segment=base.rows.find(e=>e.hit.type==='BEAM'),b=segment.hit.member,copy=Engine.clone(model),original=copy.beams.find(x=>x.id===b.id),duplicate=Engine.clone(original),axis=dir==='X'?1:0;duplicate.id=duplicate.displayId='OVERLAP';duplicate.rawA[axis]+=.001;copy.beams.push(duplicate);const ambiguous=SlabSupport132.plan(c,dir,copy,o);ok(ambiguous.errors.length,'Overlapping actual supports remain ambiguous');const resolved=SlabSupport132.plan(c,dir,copy,{...o,slabSupports132:save});ok(!resolved.errors.length,'Manual original target resolves ambiguity');
  const custom=Engine.clone(r);Object.assign(Engine.floorModel(custom,1),copy);const chosen=Engine.clone(save),value=SlabSupport132.value({member:duplicate,type:'BEAM'});chosen.segments=chosen.segments.map(s=>s.target===SlabSupport132.value(segment.hit)?{...s,target:value}:s);const changed=Engine.clone(p);Loading.saveFramingSupports(changed,1,token,{slabSupports132:chosen},['slabSupports132']);const changedRows=Loading.run(changed,custom).rows,slabRow=changedRows.find(r=>r.floor===1&&r.kind==='SLAB'),receiver=changedRows.find(r=>r.floor===1&&r.member.id==='OVERLAP');ok(!slabRow.transferErrors.length&&slabRow.slabReactions.some(s=>s.supportId==='OVERLAP'),'Saved manual target used in real transfer');ok(receiver.loading.automaticLines.some(s=>s.label===c.id&&s.q>0),'Selected receiver actually receives slab load');
  const span=Loading.slabCalculation(c,dir,copy,{...o,slabSpan131:null,slabSupports132:save});ok(!span.errors.length,'Manual support also resolves automatic span: '+JSON.stringify(span));
  for(const kind of ['MB','SB','TB'])for(const vertical of [false,true])for(const reverse of [false,true])for(const width of [.25,1.2,3]){let u=[0,0],v=vertical?[0,10]:[10,0],q=vertical?[0,3]:[3,0];if(reverse)[u,v]=[v,u];const beam={kind,b:width,d:1,a:[u[0]+.6,u[1]+.6],z:[v[0]+.6,v[1]+.6],rawA:u,rawZ:v};near(Loading.contact(q,beam).x,reverse?7:3,'Reference point independent of section width and offset');ok(!Loading.contact(vertical?[.1,3]:[3,.1],beam),'Off-line beam contact cannot be invented from section');const loads=Loading.beamSpanLoads(Loading.beamSpan(beam,{beamSpan:8}),[],[{x:Loading.contact(q,beam).x,g:10,q:5}]);near(loads.points[0].x,(reverse?7:3)*.8,'Manual beam span scales node station once');}
  passed.push('MB/SB/TB reference nodes, width/offset independence, X/Y, reversed ends and manual span mapping');
  passed.push('Actual slab segments, manual override, auto span, shared framing, stale direction, missing targets, overlaps and invalid imported records');
  const snapshot=JSON.stringify(p),expected=Loading.audit(p,r),actual=await AuditRunner132.run(p,r);ok(JSON.stringify(actual)===JSON.stringify(expected),'Batched audit matches synchronous results');ok(JSON.stringify(p)===snapshot,'Audit preserves all project/report selections');passed.push('Batched/synchronous full check parity and project/report immutability');
  return {passed,project:p,saved:save};
 });console.log(JSON.stringify({core:core.passed}));
 async function open(p){await page.locator('#file').setInputFiles({name:'support132.framing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await page.evaluate(()=>{if(!window.supportPlot132){const original=Drawing.plan;Drawing.plan=(...args)=>window.plot132=original(...args);window.supportPlot132=true;}StudioHost.navigate('beams');});await page.getByRole('button',{name:'选择 / 删除',exact:true}).click();}
 async function select(){const spot=await page.evaluate(()=>{const h=StudioHost.get(),s=Engine.floorModel(h.result,h.floor).slabs[0],r=s.rects[0];return {x:plot132.ox+(r.x0+r.x1)/2*plot132.scale,y:plot132.oy+(r.y0+r.y1)/2*plot132.scale};});await page.locator('#canvas').click({position:spot});await page.locator('#ex-slab-support-mode132').waitFor();await page.waitForFunction(()=>document.querySelector('.slab-panel121 [data-sp-fold=loads]')?.textContent.includes('支承反力'));}
 await open(core.project);await select();await page.locator('.slab-support132').scrollIntoViewIfNeeded();assert.equal(await page.locator('#ex-slab-support-mode132').inputValue(),'manual');const before=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('[data-ex=slab-support-auto132]').click();assert(!(await page.evaluate(()=>Object.values(StudioHost.get().p.explorer.members).some(o=>o.slabSupports132))));await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),before);await select();
 await page.locator('[data-ex=slab-support-auto132]').click();const auto=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('#ex-slab-support-mode132').selectOption('manual');const target=page.locator('[data-slab-target132]').first(),value=await target.locator('option').nth(1).getAttribute('value');await target.selectOption(value);await page.evaluate(()=>StudioHost.navigate('beams'));assert.equal(await target.inputValue(),value,'Draft survives refresh');await page.locator('[data-ex=slab-support-save132]').click();await page.waitForFunction(()=>Object.values(StudioHost.get().p.explorer.members).some(o=>o.slabSupports132));const saved=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(StudioHost.get().p)),auto);await open(JSON.parse(saved));await select();assert.equal(await target.inputValue(),value,'Saved segment survives JSON reopen');await page.locator('.slab-support132').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'slab-support132.png')});await page.setViewportSize({width:1120,height:820});await page.locator('.slab-support132').screenshot({path:path.join(out,'slab-support-narrow132.png')});assert(await page.locator('.slab-support132 table').evaluate(e=>e.scrollWidth<=e.parentElement.clientWidth+2),'Support table fits');await page.setViewportSize({width:1600,height:1080});
 core.passed.push('Real support UI: auto/manual, selection, shared save, refresh draft, undo, JSON reopen and narrow layout');
 const projectFile='output/HKIE_Calculation_Audit/2015_local_heights_E2128/HKIE_2015_Q3_TrialCheck_v2_E2.128.framing.json';
 if(fs.existsSync(projectFile)){
  const trial=JSON.parse(fs.readFileSync(projectFile,'utf8'));
  const diagnosis=await page.evaluate(source=>{const p=Engine.clone(source),r=Engine.generate(p),m=Engine.floorModel(r,3),slabs=[],assert=(v,m)=>{if(!v)throw Error(m);};for(const id of ['SL-08','SL-26','SL-41','SL-56','SL-71','SL-89','SL-107']){const s=m.slabs.find(s=>s.id===id),t=Loading.token('SLAB',s);Loading.saveFramingSupports(p,3,t,{slabSpan131:{L:3,width:null,selfWeight:'net'}},['slabSpan131']);const rr=Loading.inspectSlab(p,r,3,t);assert(!rr.transferErrors.length,id+' physical supports complete');const G=rr.slabReactions.reduce((v,e)=>v+e.g*e.length,0),Q=rr.slabReactions.reduce((v,e)=>v+e.q*e.length,0),targetG=s.area*(s.thickness*.0245+LoadData.floor(p,3).sdl),tol=rr.slabReactions.reduce((v,e)=>v+e.length*.01001,0);assert(Math.abs(Q-s.area*LoadData.floor(p,3).ll)<tol,id+' LL conserved');assert(G>=targetG-1e-6&&G-targetG<tol,id+' G conserved');slabs.push({id,status:rr.result.status,errors:rr.transferErrors,G,Q});}
   const rows=Loading.run(p,r,'B',false,3).rows,tb=rows.find(r=>r.id==='TB_004'),cap=tb.loading.automaticPoints.filter(x=>x.label==='SL-08');assert(cap.length&&cap.every(x=>x.x===0&&x.g>0),'TB end-cap receives slab force as point at reference origin');assert(rows.filter(r=>r.loading?.automaticLines).every(r=>r.loading.automaticLines.every(l=>l.end>l.start)),'No zero-length slab loads');
   const upper=Engine.floorModel(r,4),columns=['C02','C16'].map(id=>{const c=upper.columns.find(c=>c.id===id),q=Loading.columnLoadPoint(p,upper,c),hits=m.beams.filter(b=>b.kind==='TB'&&Loading.contact(q,b));assert(hits.length===1&&Loading.contact(q,hits[0]).x===4,'Column reference station 4m');return {id,point:q,TB:hits[0].id,x:4};});return {project:p,slabs,columns,cap};},trial);
  const diagnostic=diagnosis.project;delete diagnosis.project;fs.writeFileSync(path.join(out,'model-reproductions132.json'),JSON.stringify(diagnosis,null,2));
  await open(diagnostic);await page.locator('.summary-issues131 summary').click();await page.locator('[data-ex=audit-run131]').click();await page.locator('[data-ex=audit-cancel132]').click();assert((await page.locator('[data-audit-progress132]').textContent()).includes('取消'));await page.locator('[data-ex=audit-run131]').click();await page.evaluate(()=>StudioHost.transact(()=>StudioHost.get().p.name+=' test edit'));await page.waitForFunction(()=>document.querySelector('[data-audit-progress132]')?.textContent.includes('输入已改变'));assert(await page.locator('[data-ex=audit-run131]').isEnabled());
  const checkSnapshot=await page.evaluate(()=>JSON.stringify(StudioHost.get().p));await page.evaluate(()=>{const original=AuditRunner132.run;AuditRunner132.run=async(...args)=>window.auditResult132=await original(...args);window.auditTicks132=[];window.auditClock132=setInterval(()=>auditTicks132.push(performance.now()),25);});const began=Date.now();await page.locator('[data-ex=audit-run131]').click();await page.waitForFunction(()=>document.querySelector('[data-audit-progress132]')?.textContent==='检查完成',{},{timeout:180000});const elapsed=Date.now()-began,check=await page.evaluate(()=>{clearInterval(auditClock132);return {statuses:auditResult132.items.reduce((n,v)=>(n[v.status]=(n[v.status]||0)+1,n),{}),count:document.querySelector('.summary-issues131').textContent.match(/已检查 (\d+)/)?.[1],ticks:auditTicks132.length,maxGap:Math.max(0,...auditTicks132.slice(1).map((t,i)=>t-auditTicks132[i])),same:JSON.stringify(StudioHost.get().p)};});assert.equal(check.same,checkSnapshot);delete check.same;assert.equal(check.count,'4310');assert(check.ticks>50,'Main UI yielded while checking 4310 members');await page.locator('.summary-issues131').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'full-check132.png')});fs.writeFileSync(path.join(out,'full-check132.json'),JSON.stringify({elapsed,...check},null,2));console.log(JSON.stringify({fullBuilding:{elapsed,...check}}));core.passed.push('2015 seven stepped slabs transfer conserved load; TB end-cap point load and both reference-node columns reproduced');core.passed.push('4310-member real UI full check, cancel, stale-input rejection, progress, responsive timer and input/report preservation');
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'support132.json'),JSON.stringify({passed:core.passed,errors},null,2));console.log(JSON.stringify({passed:core.passed,errors}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
