const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert/strict'),vm=require('vm');
const repo=process.argv[2]||path.resolve(__dirname,'../..'),base='87018f5593a07d7e8f4356c1f88f3f4e7dbd963a',root=path.join(repo,'FramingStudio'),out=path.join(repo,'tmp/release203');fs.mkdirSync(out,{recursive:true});
const show=p=>cp.execFileSync('git',['show',base+':'+p],{cwd:repo,maxBuffer:40e6});
const tracked=cp.execFileSync('git',['ls-tree','-r','-z','--name-only',base,'FramingStudio'],{cwd:repo,encoding:'utf8'}).split('\0').filter(Boolean);
const allowed=new Set(['FramingStudio/source/app.js','FramingStudio/source/FramingStudio.cs','FramingStudio/source/app.manifest','FramingStudio/source/sync-web.py','FramingStudio/verification/ui172.cjs','FramingStudio/assets/index.html','FramingStudio/version.json','FramingStudio/FramingStudio.exe']);
let identical=0;for(const p of tracked){if(allowed.has(p))continue;assert(fs.readFileSync(path.join(repo,p)).equals(show(p)),p+' changed against E2.202');identical++;}
const html=fs.readFileSync(path.join(root,'assets/index.html'),'utf8'),before=show('FramingStudio/assets/index.html').toString('utf8');
const norm=s=>s.replace(/\r\n/g,'\n').replace(/^\uFEFF/,'').trim();
for(const m of html.matchAll(/\/\* studio-source:([a-z0-9.-]+):start \*\/[\s\S]*?\/\* studio-source:\1:end \*\//g)){
 const body=m[0].split(':start */')[1].split('/* studio-source:')[0];assert.equal(norm(body),norm(fs.readFileSync(path.join(root,'source',m[1]),'utf8')),m[1]+' bundle');
}
const strip=s=>norm(s).replace(/<(style|script)>\/\* studio-source:ui-polish173\.(?:css|js):start \*\/[\s\S]*?:end \*\/<\/\1>\n/g,'').replace(/\/\* studio-source:(measure189|review-layout191)\.js:start \*\/[\s\S]*?\/\* studio-source:\1\.js:end \*\/\n/g,'').replace(/\/\* studio-source:app\.js:start \*\/[\s\S]*?\/\* studio-source:app\.js:end \*\//,'APP').replace(/E2\.(202|203)/g,'VERSION');
assert.equal(strip(html),strip(before),'Only UI module/app/version differ in bundled HTML; report content unchanged');
for(const p of fs.readdirSync(path.join(root,'source')).filter(x=>x.endsWith('.js'))) new vm.Script(fs.readFileSync(path.join(root,'source',p),'utf8'),{filename:p});
const U=require(path.join(root,'source/ui-polish173.js'));for(const [s,u]of [['结构高度 mm','mm'],['X 向轴距 (m)','m'],['层高 m','m'],['柱项目系数',''],['楼顶 mPD','mPD']])assert.equal(U.unitOf(s),u);assert(U.suspicious('m',3300));assert(U.suspicious('mm',.6));assert.equal(U.suspicious('m',9.3),'');
assert.equal(JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8')).version,'E2.203');
const tests=['verification/ui173.cjs','verification/truss-core-tests.cjs','verification/integration143.cjs','verification/downstream143.cjs',...['unified-dimensions201','secondary-split200','drawing-cb198','drawing-support197','column-main194','selection195','review193','review192','review-layout191','tributary187','column-load-centres186','self-weight185','beam-surface184','rounding183','depth-factors180','beam-independent179','slab-bay178','slab-transfer177','slab-centres175','unified-members175','column-anchors174','support-cantilever173'].map(n=>'source/tests/'+n+'.cjs')];
const results=[];for(const test of tests){const full=path.join(root,test);if(!fs.existsSync(full))throw Error('Missing test '+test);const start=Date.now();const r=cp.spawnSync(process.execPath,[full],{cwd:repo,encoding:'utf8',timeout:180000,maxBuffer:8e6});fs.writeFileSync(path.join(out,path.basename(test)+'.log'),(r.stdout||'')+'\n'+(r.stderr||''));results.push({test,exit:r.status,ms:Date.now()-start});console.log((r.status===0?'PASS ':'FAIL ')+test+' '+(Date.now()-start)+'ms');}
const report={baseline:base,unchangedFiles:identical,checks:['E2.202 calculation/report/native template files byte-identical','Bundled report content unchanged','Source/bundle sync','JavaScript syntax','Units and warnings'],tests:results};fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({unchangedFiles:identical,tests:results.length,failed:results.filter(r=>r.exit!==0)}));if(results.some(r=>r.exit!==0))process.exitCode=1;
