const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert/strict'),vm=require('vm');
const repo=path.resolve(__dirname,'../..'),root=path.join(repo,'FramingStudio'),out=path.join(repo,'tmp/release205'),base='014dcde54c91a6c72f665a2ad808576aca3ae571';fs.mkdirSync(out,{recursive:true});
const show=p=>cp.execFileSync('git',['show',base+':'+p],{cwd:repo,maxBuffer:40e6});
const tracked=cp.execFileSync('git',['ls-tree','-r','-z','--name-only',base,'FramingStudio'],{cwd:repo,encoding:'utf8'}).split('\0').filter(Boolean);
const allowed=new Set(['FramingStudio/source/loading.js','FramingStudio/source/explorer-ui.js','FramingStudio/source/FramingStudio.cs','FramingStudio/source/app.manifest','FramingStudio/assets/index.html','FramingStudio/version.json','FramingStudio/FramingStudio.exe']);
let identical=0;for(const p of tracked){if(allowed.has(p))continue;assert(fs.readFileSync(path.join(repo,p)).equals(show(p)),p+' changed against E2.204');identical++;}
const html=fs.readFileSync(path.join(root,'assets/index.html'),'utf8'),before=show('FramingStudio/assets/index.html').toString('utf8'),norm=s=>s.replace(/\r\n/g,'\n').replace(/^\uFEFF/,'').trim();let bundled=0;
for(const m of html.matchAll(/\/\* studio-source:([a-z0-9.-]+):start \*\/[\s\S]*?\/\* studio-source:\1:end \*\//g)){const body=m[0].split(':start */')[1].split('/* studio-source:')[0];assert.equal(norm(body),norm(fs.readFileSync(path.join(root,'source',m[1]),'utf8')),m[1]+' bundle');bundled++;}assert.equal(bundled,36);
const strip=s=>norm(s).replace(/\/\* studio-source:(?:loading|explorer-ui)\.js:start \*\/[\s\S]*?\/\* studio-source:(?:loading|explorer-ui)\.js:end \*\//g,'SUMMARY_MODULE').replace(/E2\.(204|205)/g,'VERSION');assert(strip(html)===strip(before),'All other bundled content, including reports, unchanged');
for(const p of fs.readdirSync(path.join(root,'source')).filter(x=>x.endsWith('.js')))new vm.Script(fs.readFileSync(path.join(root,'source',p),'utf8'),{filename:p});
assert.equal(JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8')).version,'E2.205');
const loading=fs.readFileSync(path.join(root,'source/loading.js'),'utf8'),oldLoading=show('FramingStudio/source/loading.js').toString('utf8');assert.equal(loading.split(' // Summary-only classification:')[0],oldLoading.split(' function audit(p,r)')[0],'Loading calculations before audit unchanged');assert.equal(loading.slice(loading.indexOf(' function inspectSlab(')).replace('{auditChecks205,','{'),oldLoading.slice(oldLoading.indexOf(' function inspectSlab(')),'Loading calculations after audit unchanged');
if(process.argv.includes('--preservation-only')){console.log(JSON.stringify({unchangedFiles:identical,bundledModules:bundled,loadingCalculationsUnchanged:true}));process.exit(0);}
const tests=['verification/integration143.cjs',...['summary-sections205','summary-sections205-ui','audit-filters169','apply-column-advice','member-depth204-ui','beam-surface184'].map(n=>'source/tests/'+n+'.cjs')];
const results=[];for(const test of tests){const start=Date.now(),r=cp.spawnSync(process.execPath,[path.join(root,test)],{cwd:repo,encoding:'utf8',timeout:180000,maxBuffer:8e6});fs.writeFileSync(path.join(out,path.basename(test)+'.log'),(r.stdout||'')+'\n'+(r.stderr||''));results.push({test,exit:r.status,ms:Date.now()-start});console.log((r.status===0?'PASS ':'FAIL ')+test);if(r.status!==0)console.log((r.stdout||'')+(r.stderr||''));}
const report={baseline:base,unchangedFiles:identical,bundledModules:bundled,tests:results};fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({unchangedFiles:identical,tests:results.length,failed:results.filter(r=>r.exit!==0)}));if(results.some(r=>r.exit!==0))process.exitCode=1;
