const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert/strict'),vm=require('vm');
const repo=path.resolve(__dirname,'../..'),root=path.join(repo,'FramingStudio'),out=path.join(repo,'tmp/release204'),base='5d18359d7110709b14fcecf431e23b88509791f6';fs.mkdirSync(out,{recursive:true});
const show=p=>cp.execFileSync('git',['show',base+':'+p],{cwd:repo,maxBuffer:40e6});
const tracked=cp.execFileSync('git',['ls-tree','-r','-z','--name-only',base,'FramingStudio'],{cwd:repo,encoding:'utf8'}).split('\0').filter(Boolean);
const allowed=new Set(['FramingStudio/source/app.js','FramingStudio/source/FramingStudio.cs','FramingStudio/source/app.manifest','FramingStudio/source/tests/full-structural-depth.cjs','FramingStudio/assets/index.html','FramingStudio/version.json','FramingStudio/FramingStudio.exe']);
let identical=0;for(const p of tracked){if(allowed.has(p))continue;assert(fs.readFileSync(path.join(repo,p)).equals(show(p)),p+' changed against E2.203');identical++;}
const html=fs.readFileSync(path.join(root,'assets/index.html'),'utf8'),before=show('FramingStudio/assets/index.html').toString('utf8'),norm=s=>s.replace(/\r\n/g,'\n').replace(/^\uFEFF/,'').trim();let bundled=0;
for(const m of html.matchAll(/\/\* studio-source:([a-z0-9.-]+):start \*\/[\s\S]*?\/\* studio-source:\1:end \*\//g)){const body=m[0].split(':start */')[1].split('/* studio-source:')[0];assert.equal(norm(body),norm(fs.readFileSync(path.join(root,'source',m[1]),'utf8')),m[1]+' bundle');bundled++;}assert.equal(bundled,36);
const strip=s=>norm(s).replace(/\/\* studio-source:app\.js:start \*\/[\s\S]*?\/\* studio-source:app\.js:end \*\//,'APP').replace(/E2\.(203|204)/g,'VERSION');assert.equal(strip(html),strip(before),'All other bundled content, including reports, unchanged');
for(const p of fs.readdirSync(path.join(root,'source')).filter(x=>x.endsWith('.js')))new vm.Script(fs.readFileSync(path.join(root,'source',p),'utf8'),{filename:p});
assert.equal(JSON.parse(fs.readFileSync(path.join(root,'version.json'),'utf8')).version,'E2.204');
const tests=['verification/ui173.cjs',...['member-depth204-ui','auto-type199-ui','beam-depth184-ui','full-structural-depth','unified-dimensions201-ui','unified-dimensions201','beam-surface184','depth-factors180','self-weight185','secondary-split200'].map(n=>'source/tests/'+n+'.cjs')];
const results=[];for(const test of tests){const start=Date.now(),r=cp.spawnSync(process.execPath,[path.join(root,test)],{cwd:repo,encoding:'utf8',timeout:180000,maxBuffer:8e6});fs.writeFileSync(path.join(out,path.basename(test)+'.log'),(r.stdout||'')+'\n'+(r.stderr||''));results.push({test,exit:r.status,ms:Date.now()-start});console.log((r.status===0?'PASS ':'FAIL ')+test);if(r.status!==0)console.log((r.stdout||'')+(r.stderr||''));}
const report={baseline:base,unchangedFiles:identical,bundledModules:bundled,tests:results};fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({unchangedFiles:identical,tests:results.length,failed:results.filter(r=>r.exit!==0)}));if(results.some(r=>r.exit!==0))process.exitCode=1;
